### ISSUE TITLE
Truncate "SpecialVersion" to overcome NuGet limitation of 20 characters

### ISSUE THREAD

**Issue by augustoproiete** [OctopusDeploy/Issues#1183]
We need the ability to deploy (from Octopus) _any_ feature branch and we need an easy way to find the branch we want to deploy when creating a new release in Octopus.

The convention we use is PackageId.SemVer-BranchName. E.g.:
- MyApp.1.0.4-JIRA-1238-aa-some-meaningful-description 
- MyApp.1.0.3-JIRA-1231-bb-some-meaningful-description 
- MyApp.1.0.2-JIRA-1235-bb-some-meaningful-description 
- MyApp.1.0.1-JIRA-1234-cc-some-meaningful-description 
- etc.

Where "aa, bb, cc" are the initials of the developers who sent the pull-request, and the JIRA ticket number is part of the branch name (also convention).

---

Links:

NuGet imposes artificial max string length of 20 characters for "SpecialVersion" (aka pre-release)
https://nuget.codeplex.com/workitem/3426

Octopack Version number is too short
http://help.octopusdeploy.com/discussions/problems/16456-octopack-version-number-is-too-short

**Comment by cfontan** [comment]
Was there ever anything done with this?

**Comment by caioproiete** [comment]
@cfontan: Yes, @PaulStovell merged my pull-request back in 2014: https://github.com/OctopusDeploy/Octo.exe/pull/47, so I'd expect this issue to not exist in any recent release of Octo.exe.

Are you having this issue today?

**Comment by cfontan** [comment]
I am. I saw the merge.. I'm jot sure why..

**Comment by caioproiete** [comment]
@cfontan Unfortunately the code that truncates the version for NuGet got removed on commit [6f20cc0](https://github.com/OctopusDeploy/OctopusClients/commit/6f20cc0b4e038118e0891855c1c958860ac1cab1#diff-73263f94d72d13c0b4ea48c5d1cbb8d1L87) by @MJRichardson 

@MJRichardson Any plans to add this back in? Happy to send a new PR with the code adapted to use `NuGetVersion` instead of `SemanticVersion` as it is now.
