### ISSUE TITLE
Spaces in values/names break Linux deployments

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1214]
E.g. `/home/user/.tentacle/applications/dev/octo library/octopuslibrary` causes our deployment scripts to try and use the incorrect path to the uploaded package and where to extract it to.

**Comment by zentron** [comment]
Im not sure this is really a problem (any more?) If the user has a script where this variable is used then they can wrap in quotes. Otherwise they may need to genuinely use the variable as-is to further append a deeper path.
Do you have a specific case where this is causing problems or is this just a pre-mono issue?
