### ISSUE TITLE
Allow Octopus to have non-ascii characters in projects and packages 

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1252]
I have some serious problems with auto deploy octopus release via Team City.

I have a project in VS with a non-ascii character in the project name say

MyProjectÅ

However in my project settings I have specified assembly name

MyProjectAA

When I compile my solution in get

MyProjectAA.dll

But when its packed via octopack on team city the nuget package becomes

MyProjectÅ..nupkg

During deploy via TeamCity when running
Running command: octo.exe create-release --server .......

it is not able to find the package. In my team city output i says
[14:48:33]Finding latest NuGet package for step: Deploy MyProjectAA [14:48:33]Could not find any packages with ID 'MyProject†' in the feed ....

Source: http://help.octopusdeploy.com/discussions/problems/25769

**Comment by PaulStovell** [comment]
Thanks for getting in touch. We've decided to close this item because we believe it is fixed in the latest supported Octopus release. For more information on the reasons why, or if you think this was a mistake, please see this page on [why was my issue closed](http://octopusdeploy.com/roadmap/why-was-this-closed).
