### ISSUE TITLE
High CPU usage and package file expansion issue

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1256]
We have experienced the same timeout when our Octopus package went from 900Mb to 970Mb. After downloading and compiled the pre-release of the Nuget 3.0 exe respecting the timeout value of the push command, we manage to resolve the problem.

However, we observe that there are network traffic for uploading the package for about a minute. The following 5 minutes we observe a lot of CPU and memory usage on the octopus server. The memory usage on Octopus.Server.exe was almost 9 GB at the maximum during this “post processing”. CPU Usage was up to apx 70%. Our Octopus server is configured with 16GB memory and two cores of 2.4 GHz and we use an Enterprise licensed Octopus Server with version 2.5.9.554

Source: http://help.octopusdeploy.com/discussions/problems/19309 (see last comment)

**Comment by ChaseFlorell** [comment]
I still had very high CPU usage while running 2.6.
Installing the latest version seems to bring that usage back down, but that could also be simply because the service was restarted... Only time will tell.

http://help.octopusdeploy.com/discussions/problems/30856-publishing-to-internal-feed-seems-slugish
