### ISSUE TITLE
Registering Tentacles causes error immediately blocking deployments

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1342]
We register new Tentacles automatically when they power on using "tentacle.exe register-with". Lately the Tentacles have been registering fine and appear in the GUI, but within seconds display the following error:

Pipefish.PipefishException: The request failed: BadRequest
The incoming request was on a communication link (subscription) that is no longer valid. Reset connectivity to perform a new handshake and reestablish communication.
at Pipefish.Transport.SecureTcp.MessageExchange.Client.ClientWorker.PerformExchange() in y:\work\3cbe05672d69a231\source\Pipefish.Transport.SecureTcp\MessageExchange\Client\ClientWorker.cs:line 335 at Pipefish.Transport.SecureTcp.MessageExchange.Client.ClientWorker.Run() in y:\work\3cbe05672d69a231\source\Pipefish.Transport.SecureTcp\MessageExchange\Client\ClientWorker.cs:line 182

If I hit reset in the GUI they reconnect no problem, but this manual intervention breaks our deployment automation.

Any ideas what could cause the communication link to immediately become invalid after registering?

The command I'm using to register is:

tentacle.exe register-with --instance "$instance" --server "$server" --name "$machineName" --publicHostName "$extName" --apiKey="$octAPI" --role "$role" --environment "$octEnv" --comms-style TentaclePassive --console

Source: http://help.octopusdeploy.com/discussions/problems/26441

**Comment by PaulStovell** [comment]
All fixed in 3.0

**Comment by ShaneCal** [comment]
Hi Paul,
We're running Octopus 2.6 and are hitting the same problem with Tentacle automation. I can't seem to find the release this bug was fixed in, can you post the exact release?

**Comment by PaulStovell** [comment]
Hi @ShaneCal,

It was fixed in the first 3.0 release, since we refactored Octopus to no longer use Pipefish (the component mentioned in the stack trace), and the whole issue around "The incoming request was on a communication link (subscription) that is no longer valid. Reset connectivity to perform a new handshake and reestablish communication" will no longer exist in 3.0 since we don't use that component anymore. So any 3.x version will have this issue fixed. 

Hope this helps!
