### ISSUE TITLE
2.6 run steps in parallel - skipped steps bug

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1406]
If you have two steps set to run in parallel and the first step is skipped, the second will never run.

Source: http://help.octopusdeploy.com/discussions/problems/28508

**Comment by vanessalove** [comment]
There is also an ordering bug - if you set a not-first step to run in parallel with the previous step, and then reorder it remembers this and the deployment never starts
Source: https://octopusdeploy.uservoice.com/admin/tickets/2583

**Comment by vanessalove** [comment]
We will also have to be aware if a previous step only runs on specific environments and that environment isn't being deployed to, will the next step ever run?

**Comment by boksasp** [comment]
Any progress on this? I'm just guessing that you are working on fixing it since you have classified it as a bug.

My use case is that we sometimes want to retry specific steps after a failed deploy. As of now, all of our steps except post-deploy email notification are run in parallell. So retrying just one of the steps isn't really an option as long as this bug is present.

Thanks for an awesome product!

Best regards,
Trond

**Comment by antonsw** [comment]
Also eagerly awaiting this fix please.

**Comment by megrogan** [comment]
Yes please fix ASAP

**Comment by lonevvolf** [comment]
Too bad this didn't make it into 2.6.1 as this is basically also a stalling bug.

**Comment by erichexter** [comment]
+1
