### ISSUE TITLE
Investigate cancelling tasks causing Octopus to queue everything and stall

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1431]
Source: http://help.octopusdeploy.com/discussions/problems/29265
Also reported by Brent on call

**Comment by jennales** [comment]
Any updates on this issue?

**Comment by lkremerlogmein** [comment]
Please fix this issue! Affects heavily us as one Octopus instance servers different projects, and due to this bug, all of the deplyoments can be affected.

**Comment by jennales** [comment]
Hi Paul -

Today I saw that I had a task that had been sitting in a "deploying" state for one month.  I was afraid to cancel it because then I would have to shut down the Octopus server and run the repair script.  Today, I got tired of seeing it sitting there and took the chance of cancelling it.  It worked!  I had no issues with it getting stuck in a queued state, didn't have to click 'cancel' again to get it to actually cancel, and I was able to successfully deploy other projects after I cancelled it.  

So it seems that this is no longer an issue for me.  I didn't do any updates to Octopus, other than a normal Windows update a few days ago.

Thanks to you and Vanessa for all of your help.

- Jenna
