### ISSUE TITLE
Possible browser - change password - issues

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1455]
two cases of change password feature not working - investigate if we can!

Source: http://help.octopusdeploy.com/discussions/problems/29488
http://help.octopusdeploy.com/discussions/problems/29407

**Comment by wes-novack** [comment]
Was there a resolution on this? We're still seeing issues getting the message "You must be logged in to perform this action. Please provide a valid API key or log in again."

This appears to be due to session/cookie issues, because if you clear your cookies or use a Chrome Ignito window, then the login works fine.

**Comment by vanessalove** [comment]
@wes-novack sorry for the dalay, this one isn't due to logging in or sessions, was simply creating a user or changing their passwords.
Session and cookies have been changed in 3.0

**Comment by vanessalove** [comment]
Confirmed again for FF39. https://octopusdeploy.uservoice.com/admin/tickets/5436
So far FF is the only culprit - so what addon/extension password manager is messing with this?

**Comment by mausch** [comment]
I'm having this issue with FF43, Octopus 3.2.10
