### ISSUE TITLE
Make NuGet package extractor include .nuspec files

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1483]
https://twitter.com/choudeshell/status/567747552234471424

Only issue is keeping backwards compatibility: websites etc. might not want their .nuspec files extracted to the package root because they might then be served by IIS. Possible solutions: 

1. We don't extract nuspecs by default, instead a special variable could be used
2. We decide whether to extract based on the package contents (not sure exactly what)

**Comment by choudeshell** [comment]
For ASP.NET 5 (XRE) based applications, dependent libraries are expressed as expanded/uncompressed NuGet packages with a requirement that the given dependent NuGet package's NuSpec file is present within the expansion. This causes issues with OctopusDeploy since:

1. XRE-based deployment NuGet packages are difficult to create since the default behavior of both NuGet and Octo is to strip/not include non-manifest (dependency) NuSpec files in the Deployment NuGet package. 

2. When deploying XRE-based Deployment NuGet packages, non-manifest (dependency) NuSpec files are not written to the filesystem creating a broken (non-working) deployment

To remedy these issues:

1. Octopus-Tools (Octo) should not have a hard dependency on Nuget.Core. It should instead have a hard dependency on a forked version of NuGet.Core that allows creation of NuGet packages that allow for multiple NuSpec files. This modified behavior would be flagged via an argument. 

2. Octopus Deploy should have a special variable `SpecialVariables.Tentacle.Agent.HandleDeploymentAsZip` where the Deployment Nuget package is handle as a glorified Zip file; expanding the package without regards of what it contains (constrained by existing Octopus Deploy variables). This would essentially skip the comparison in `LightWeightPackageExtractor` that checks to see if the computed part is a manifest (NuSpec) file.
