### ISSUE TITLE
Bug in IIS script for non-SNI bindings

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1510]
mfrank found this bug:

http://help.octopusdeploy.com/discussions/problems/16520

```
Changing line 180 and 149 to if ($hasThumb.Length -eq $null) should resolve this issue.
```

**Comment by Flash1232** [comment]
Might it be that this issue was introduces again?
I have an Octopus Server running with two bindings: http://deploys.domain.com and https://deploys.domain.com (using deploys.domain.com certificate).
Now in the IIS on the same machine there is a Website called "issues.domain.com" which has another two bindings: issues.domain.com:80 and issues.domain.com:443 using issues.domain.com certificate. The problem is that everytime I either re-bind Octopus Server or the website, the opposite website's certificate gets replaced aswell.

Is this a bug or is it not? I didn't tick "requires SNI" on the website.

Thanks in advance!
