### ISSUE TITLE
Showing both prompt variables when having same name but different scope

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1524]
If we have two prompt variables with the same name and one of them has a scope and the other doesnt, we show both on the deployment screen. During the deployment, the correct value is used (the one from the scoped variable), but we should only be showing the most specific prompt variable on the deployment screen.

**Comment by zentron** [comment]
Could you provide further background for this? 

I could imagine a case where both prompted variables need to be provided since one is scoped to a single machine, and another is unscoped.
In the case where the deployment takes place on multiple machines we may need both values depending on which machine is being deployed to.

Perhaps what is needed instead is better indication on the deployment screen as to the scoping of the prompted variables listed.

**Comment by Dalmirog** [comment]
@zentron I agree with improving the indication. Worth asking @PaulStovell his thoughts as he asked me to submit this one in a call we had

**Comment by zentron** [comment]
The proposed solution is to provide a UI label if the same prompted variable shows for multiple environments since this will be pushed back to the API in different parts of the JSON. All other instances will only show 1

**Comment by zentron** [comment]
By design if a user expects to have the same named promoted variable show up multiple times on the deployment screen, they can provide a different label on the variables page. The correct variable value will then be set in the correct deployment context.

![image](https://cloud.githubusercontent.com/assets/1830666/11388274/246ce958-9380-11e5-9c1e-5b228e28851f.png)
