### ISSUE TITLE
Add ability to set login cookie timeout

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1526]
Have a variable to set login timeout for inactive users. Needs to slide so they are not logged out while active!

See https://octopusdeploy.uservoice.com/admin/tickets/3732/

**Comment by DragonSpawn** [comment]
I'm curious about the information about this in uservoice, but I can't view it since it's an admin link :)

**Comment by Damovisa** [comment]
Hi @DragonSpawn,

This came out of a support email where there's some sensitive information, so I can't open that up for you - the link is really just for us internally.

Essentially, we're talking about the browser session timeout. There was a request to be able change the timeout value so you'd have to log in after a customizable period of inactivity.

**Comment by DragonSpawn** [comment]
Thanks for sharing @Damovisa. The cookie not having a sliding window is probably the largest pet peeve I have with OD, which is still pretty good if that's the worst annoyance I have :)
When it logs me out on my phone it always annoys me since then I have to go fetch my password again (and the octopus deploy login page doesn't trigger the "Want me to remember your password?" dialog (which is pet peeve no 2) on the phone either so it just becomes an annoyance whenever it happens).

**Comment by Damovisa** [comment]
Note: We revisited the cookie policy, however have not allowed a customisable expiry period.
The new mechanism will support load-balanced clusters with the upcoming High Availability offering.

The three scenarios are:
1. You log in and keep a window open (which makes regular requests to the Octopus Server in the background). Every 1min, you get a new cookie which keeps you logged in until you close the window (or the browser stops making requests).
2. You log in then close the window. Your cookie will last 20min, after which time you’ll have to log in again if you open it back up. If you open Octopus in 15min, you’ll be logged in automatically, then it will behave as per point 1.
3. You log in and choose “Keep me logged in”. You’re given a cookie that’s valid for 20 days. After that point you’ll have to log in again.
