### ISSUE TITLE
Proxy expects 100

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1528]
I have an issue that our squid proxy doesn't like contacting the octopus server when trying to setup a new tentacle.

The proxy returns a 417 error

This apparently is due to the octopus server inserting an Expect-100 continue http header

This is explained here

http://stackoverflow.com/questions/566437/http-post-returns-the-err...

In our case we can adjust the proxy to ignore this error. However there maybe other networks where the proxy will choke on this that we can't tell to ignore the error. We do have control over the octopus server itself though. So is there anyway to stop the octopus server inserting this header.

Link to add per Paul's request: https://slack-redir.net/link?url=http%3A%2F%2Fhaacked.com%2Farchive%2F2004%2F05%2F15%2Fhttp-web-request-expect-100-continue.aspx%2F

Source: http://help.octopusdeploy.com/discussions/problems/31994

**Comment by jaybeeelsdon** [comment]
Hi. This is Justin. I was the one who first asked about this and then Dalmirog created an issue for it. I see it's now closed. Does this mean it's now fixed. If so do I just need to update the server with latest version. I just want to check before doing so as I'd rather not go through the pain of updating the server as it's otherwise working fine if the fix isn't in the latest release. Cheers Justin
