### ISSUE TITLE
Improve IIS binding addition

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1582]
Currently Octopus deletes all the bindings on the site and adds the ones that were declared on the Nuget Package Deploy step.

This could be improved by only adding/removing the extra/missing bindings.

Source: http://help.octopusdeploy.com/discussions/problems/32973

**Comment by Dalmirog** [comment]
Perhaps adding an option to "Create if doesnt exist, but dont update if it does!" close to this one
![capture](https://cloud.githubusercontent.com/assets/6180562/7495599/5f98fc64-f3e5-11e4-9fc4-3c5bae6df02a.JPG)

This would save time to users with apps with many complicated bindings

**Comment by DamianMac** [comment]
We've had more of a think about this and it doesn't make sense to make these changes. I think we currently do it the "right" way.

If you follow a "proper" (for want of a better word) automation strategy (which is the goal), then all the configs should be stored in a tool (i.e. Octopus) and it should be the source of truth for your IIS bindings.

IIS shouldn't have bindings that Octopus doesn't know about because leads to special snowflake environments that can't be repeated. So dumping them and recreating is the best behaviour.

Doing them one by one would lead to the problem of orphaned bindings because if one was removed from Octopus we wouldn't know to delete it.

Doing them one by one also doesn't really get around the site not responding for a few milliseconds, if that's a serious issue though it's where load balancers and rolling deployments come into the picture.

**Comment by PaulStovell** [comment]
I think the point here is just that we shouldn't delete something we're about to re-add in a few milliseconds - i.e., compare the bindings that are currently there, then only make the deletes/adds needed to get it into the state Octopus expects, rather than the naive "clear" + "re-add".

**Comment by DavidDeSloovere** [comment]
As the original poster of the discussion, I don't think you are currently doing it the "right" way. No offense.
 
But I'm sure Paul gets it: Being selective on clearing the bindings and just adding new ones.
Also, this would be backwards compatible.

**Comment by jmalczak** [comment]
I can say that clearing bindings is an issue for me since we add bindings to web sites programaticaly. So we have a site which has to be available under many urls and users create those bindings from our another web app. So let's say user goes to one app and create subdomain, this also requires creating iis binding for this newly created subdomain. So there is no way for me to put those user created bindings in Octopus itself since everything is dynamic. Those backup and restore steps solve the issue for me now.

**Comment by mjrichardson** [comment]
release note:IIS bindings preserved (i.e. not removed and re-added) if no changes required.
