### ISSUE TITLE
Account permissions after 2.6 migration

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1628]
When you restore a 2.6 backup into 3.0, there are a few permissions that don't get set for admins. An admin doesn't have AccountView / AccountEdit etc as they didn't exist in 2, and because they're an admin you can't fix this.

A migration needs to union permissions rather than overwrite.

**Comment by IanMercer** [comment]
Rob has the fix for this. The permissions are now 'unioned' between the imported and the existing user.

**Comment by zentron** [comment]
I don't think we would want to union the users linked to a specific team since their Ids may no longer match and existing ones should already be getting mapped over.
Instead I've updated the `UserRole` document to combine all `GrantedPermissions` as some of these permissions are new.

Fix is contained in changeset OctopusDeploy@4c697db07f182579b697b57f533574806e7afc11 and OctopusDeploy@fbaebaa74021803712b39466fa2ebc3d8d2f8c3f
