### ISSUE TITLE
Sensitive variables in offline drops

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1648]
Currently secure variables are stored in the variables JSON file as plain text. We'll encrypt the values with a key so that they aren't available to view for people without the key. While it doesn't stop the rogue admin from setting new keys and then re-deploying, it does at least ensure that someone who gets the package by accident (e.g., wrong email address, stolen USB drive) won't be able to view them without the key. 

Each offline drop machine in Octopus can have a secret key associated with it. This is set from the machine details page. 

When Octopus generates the variable JSON files, if there are sensitive variables, it will use this key to encrypt them. If the offline drop machine doesn't have a key set but there are sensitive variables, the deployment will fail with a friendly message explaining to the user where to set the key. 

When Calamari runs the deployment, it will prompt for the user to provide the key if any sensitive variables were found (TBD: does the batch file prompt or does Calamari?)

**Comment by IanMercer** [comment]
Should the key be per-machine or per-project? Having to change it for 20 machines would be painful.

Should the key be a simple password, or a split public-key / private-key pair so that half can be put on the destination machines and half on the server? Doing the latter would remove the need for any user input during install and could make the offline drops more secure (octopus admins couldn't decrypt them as all they have is the public key).

**Comment by mjrichardson** [comment]
Would a better approach be to package the entire drop into an OPC archive, and encrypt that?

**Comment by zentron** [comment]
It makes sense that potentially the batch file prompts for password if its any sensitive variables are found so that it can take place once per "deployment" which itself may be made of multiple steps.

Another thought is that this bootstrapping process that decrypts values could also be responsible for taking output values from each step and passing it through to the variable files for the subsequent steps to provide similar functionality to normal tentacles. Admittedly little out of scope for this issue but worth keeping in mind.

**Comment by PaulStovell** [comment]
We actually floated the public/private key idea here (it's similar to how Tentacle works) but I think managing the private key is too difficult on Windows (given we're not meant to install anything on the destination machines). Sadly it would be much nicer from a security POV. 

Archiving the whole drop and encrypting that sounds good to me.

**Comment by Damovisa** [comment]
I like the idea of a simple password that can be used per drop target. Straightforward and relatively secure.

It does have the side-effect that secure variables can't be provided in the JSON file after the deployment package has been generated. Variables would either have to be "insecure" so they could be changed in the JSON file, or set within Octopus prior to package generation. I don't think that's a big deal though.

**Comment by mjrichardson** [comment]
How does this sound for an approach:

- When the offline target is created, ask for a password.
- When creating the batch, for each step, write any sensitive variables into a separate encrypted json file (e.g. `step1.variables.secret`).
- Add a parameter to Calamari (e.g. `-encryptionKey`) which it will use to decrypt and combine the sensitive variables with the regular variables.

So the first thing the batch file will do is prompt for a password, which it will then pass to Calamari.  If there are no sensitive-variables, the batch file will not prompt for a password.

**Comment by PaulStovell** [comment]
Works for me. So the JSON file will still just be key/value, but the whole JSON object is encrypted?

**Comment by mjrichardson** [comment]
Correct. But only the sensitive variables (if any are present).  So for a given step you would have:
- `OfflineTarget.Acme.DeployWebSite.variables.json` (regular json file containing all non-sensitive variables)
- `OfflineTarget.Acme.DeployWebSite.variables.secret` (encrypted json file containing sensitive variables)

With only the second being encrypted. The thought was, this will give the best of both worlds. Being able to view and modify (non-sensitive) variables, and having sensitive variables protected.
