### ISSUE TITLE
Active Directory sign in error

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1652]
From a customer :

Signing in for the first time shows a unique constraint violation: This is due to the sign-in button issuing two requests, so you have a race condition , one always loses and displays the unique constraint error and then the other succeeds and logs you in. I was going to dig into why it was issuing two but stopped when I saw two click handlers from two minified js files. Figured if it was worth it you guys could do that much faster then I could.

**Comment by PaulStovell** [comment]
The issue was that the login form gets submitted twice (whether AD or not) due to a faulty Angular directive. When new AD users sign in for the first time, an account gets created, thus the validation issue (the unique constraint message no longer appears, it will just say the user already exists). 

Fixed by ensuring the form can't be submitted twice.
