### ISSUE TITLE
Migrator to handle export and import of historical data

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1655]
Currently Octopus.Migrator handles only 'configuration' data and no 'historical' data.

Releases should be included in the export data and should be imported.

Releases will be placed in a directory Releases/{Project Name}/{Version}

The directory will include the Release document (release.json), the project variables snapshot and the deployment process snapshot.

**Comment by PaulStovell** [comment]
There's two parts to this:

1. Importing 2.6 historical data (required for 3.0)
2. Exporting and importing 3.0 data (we can live without this for now)

I'd focus on 1 first.

**Comment by IanMercer** [comment]
[Fixed by OctopusDeploy/OctopusDeploy/pull/243]

**Comment by PaulStovell** [comment]
Reopening this because, as I understand, there are a few things we aren't importing which are essential to do before we can ship 3.0 properly. 

Here's a complete list of what we need:

 - [ ] Releases
 - [ ] Deployments
 - [ ] ServerTasks
 - [ ] Artifacts associated with server tasks, and their attachment content
 - [ ] Activity logs (these are stored in a separate file in the backup, they need to be split and converted - Paul can explain differences)
 - [ ] Events

These aren't important for 3.0 -> 3.0 migration, but they are essential for 2.6 migrations. If someone has a 2.6 server, and upgrade to 3.0, there should be no data loss. 

It may be that we can't support re-importing etc. for these, and if that's the case we'll have to accept it, but we should at least explore what's possible.
