### ISSUE TITLE
Octopack cannot run in parallel:  OctoPack error OCTONUGET: Can not access a closed Stream

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1684]
It appears that if a complicated build is running that runs in parallel and tries to use Octopack a stream error occurs.

Can this be investigated? A workaround found?

Source: http://help.octopusdeploy.com/discussions/problems/34714

**Comment by zentron** [comment]
This issue appears to be due to a bug\issue  with NuGet.exe as described in the ticket https://github.com/NuGet/NuGet.CommandLine/issues/18
Will need to keep an eye on NuGet to see if/when this gets fixed

**Comment by mcintyre321** [comment]
@zentron The link above doesn't work anymore. Is there any update on this issue, or somewhere to track this issue?

Not being able to do parallel builds severaly impacts our build times.

**Comment by zentron** [comment]
@mcintyre321 the issue appears to have moved to https://github.com/NuGet/Home/issues/1282 .
Please follow this ticket for updates to the NuGet team's progress. From our side of things there is very little we can do until the underlying issue is fixed by them. 
That being said we are in the process of supporting non NuGet packages in the in-built feed which may provide a work around for this particular issue. Keep an eye on our company blog posts for more updates!

**Comment by BertLamb** [comment]
@zentron Can you take a look at PR https://github.com/OctopusDeploy/OctoPack/issues/79 which should pull in the NuGet fix and solve this issue from an Octopack perspective?
