### ISSUE TITLE
Validation errors in migrator should fail import, not just appear as warnings

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1695]

**Comment by Damovisa** [comment]
http://community.octopusdeploy.com/t/after-upgrade-to-3-0-could-not-login-to-the-system/354

**Comment by IanMercer** [comment]
This is currently "by design". For 3.0 imports there is a `-force` option on the command line (but not in the UI). 3.0 imports will fail if they fail validation but the user can override it by adding the -force option to the command line.

For 2.6 imports there are many things that will no longer validate but which used to be OK (because 2.6 did not validate many fields that 3.0 does validate).

If a user has backed up 2.6, upgraded to 3.0 and then their import fails, what are they to do? Reinstall 2.6, fix the validation error, backup, upgrade to 3.0 again and then try again only to hit another validation error. That's a very long loop to go round to try to fix all the validation errors you may have. Instead we allow the import of any 2.6 backup but as soon as they try to edit they will have to fix the problem.

I'll look at the specific administrator account migration issue although I suspect it is already fixed - we were failing validation on domain accounts in one release of 3.0.

**Comment by IanMercer** [comment]
I made two changes to address the reported issue here: (i) migration now never overwrites a user account. If you already have a 3.0 user it will never try to change their password or other settings during an import; (ii) 2.6 users being imported without a display name now get one set to their username.

**Comment by PaulStovell** [comment]
Good enough for me!
