### ISSUE TITLE
Id field of NugetPackage table in database for v3 needs to be varchar(301), not varchar(50)

### ISSUE THREAD

**Issue by graemechristie** [OctopusDeploy/Issues#1697]
Currently, using a long packagename + long version results in 

![image](https://cloud.githubusercontent.com/assets/1361894/8537892/80fca314-2497-11e5-8ad6-c7167c198b5b.png)

on nuget push.

In your schema the  dbo.NugetPackage.Id column is only varchar(50), but it is a concatenation of PackageId (varchar(50)) -dot- Version (Varchar (250)), so it should at least be varchar (301).

**Comment by michaelnoonan** [comment]
Hi @graemechristie.

Thanks for getting in touch. As it turns out `Nuget.Core` internally limits the length of Nuget PackageId to 100 characters and Special Version to 20 characters.

So we've set `dbo.NugetPackage.Id` to `150` and `dbo.NugetPackage.PackageId` to `100` to match.

See https://github.com/OctopusDeploy/Issues/issues/1668 and the referenced community conversation.

Feel free to reopen the issue if you don't think this is suitable.

Hope that helps!
Mike
