### ISSUE TITLE
Hydra will not install over Tentacle that had 2.0 (even if auto updated to 2.6)

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1825]
The other scenario I run into couple of tentacles is that "C:\Program Files\Octopus Deploy\Tentacle\" already existed with old version 2.0 while tentacle itself been auto-updated and located in "C:\Octopus\Applications...\Octopus.Tentacle\2.6.5.1010\"

In that case Hydra failed to install Tentacle 3.0 cause it thought that tentacle is still 2.0 and must be upgraded to 2.6.

**Comment by Damovisa** [comment]
This might be fixed with #1824

**Comment by Damovisa** [comment]
We won't be able to fix this:

If the last MSI install for a tentacle was 2.0, that instance will have been installed under a specific user account. Because Hydra needs to run as System, it won't find the previous installation and therefore won't be able to uninstall it.

Because our auto-upgrades bypassed the MSI process, it's possible for a Tentacle to be running a 2.6 Tentacle, while Windows thinks the version is 2.0.

To remedy, the user who originally installed 2.0 will need to log onto the machine. From there, they can run `Hydra.exe` directly (easiest way), or uninstall and reinstall the 3.0 Tentacle MSI manually.
