### ISSUE TITLE
Steps not running in parallel even with OctopusBypassDeploymentMutex

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1838]
Octopus version: 3.0.10.2278

This is still not working even after #1736 

![parallel](https://cloud.githubusercontent.com/assets/6180562/9064853/e0fc408a-3aa4-11e5-96e4-118bfbb2d9eb.JPG)

Both steps are scripts running `start-sleep -seconds 10`

**Comment by PaulStovell** [comment]
http://help.octopusdeploy.com/discussions/problems/36271

**Comment by zentron** [comment]
@Dalmirog bug above is due to trailing space in the DeploymentMutex variable
![image](https://cloud.githubusercontent.com/assets/1830666/9158055/87b3528a-3f53-11e5-801b-81d67a1aae0c.png)
The issue linked to by @PaulStovell appears to be due to parallel steps of the same package+machine interacting with each other in their installation directory.

Will address trimming spaces from variables as part of this ticket

**Comment by zentron** [comment]
Release Note: Trailing spaces on variable names removed when persisted
