### ISSUE TITLE
Improve performance of events queries

### ISSUE THREAD

**Issue by Damovisa** [OctopusDeploy/Issues#1845]
In instances with a large number of Events, querying the Events table results in a `LIKE` statement for related documents.

We should move RelatedDocumentIds to its own table rather than a pipe-separated string so we can index.

Suggestions so far:
 * Stored Proc for saving Events that does the related document ID splitting and inserts
 * Build queries in the `ListEventsResponder` to query the join table.

**Comment by IanMercer** [comment]
May impact Export/Import too.

**Comment by PaulStovell** [comment]
Plan of attack: 

 1. We'll keep the pipe separated string, but also add a join table
 2. Queries can use the join table for filtering instead of LIKE
 3. Some kind of "InsertListener" will  take care of copying the values into the join table

The reason to keep the pipe separated string is firstly for backwards compatibility, in case the customer downgrades. But also, because when selecting, we can do something like:

```
SELECT DISTINCT ev.* from EventReference er where er.RelatedDocumentId = @related
    INNER JOIN Event ev on ev.Id = er.Id
```

Assuming there are 100 matching events, and 5 related documents per event, this would only read back the 100 events, and yet the RelatedDocumentIds collection on an event can still be populated from the pipe-separated string. 

Without that column we'd have to bring back 500 records and then roll them up to fill the collection property. 

Also, pages like Configuration -> Audit don't query on events, and yet they need to show the related documents, so again keeping this column simplifies things.

**Comment by PaulStovell** [comment]
After making this change on the demo server (200k events) we went from an average response time of 1+ seconds to 18ms:

![Performance of /api/events](https://cloud.githubusercontent.com/assets/47085/9249951/b856a674-420c-11e5-9266-5c445e8d7a2c.png)
