### ISSUE TITLE
Old deploy.ps1 is executed if it was on the deployment path prior to the deployment.

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1880]
If `deploy.ps1` was on the deployment path prior to the deployment (and the path wasn't purged), the script gets executed. Only the `deploy.ps1` file that was extracted from the current nuget package should be executed. If there wasn't a `deploy.ps1` file on the current package, and there was one on the deployment path already, it still shouldn't be executed as it was part of an old release, correct?

Octopus Version: 3.0.12

**Comment by PaulStovell** [comment]
The old script should have been deleted the first time it was executed, so it would no longer be there.

**Comment by PaulStovell** [comment]
Thanks for getting in touch. We've decided to close this item because we believe it is fixed in the latest supported Octopus release. For more information on the reasons why, or if you think this was a mistake, please see this page on [why was my issue closed](http://octopusdeploy.com/roadmap/why-was-this-closed).

**Comment by lonevvolf** [comment]
Please reopen.  We have hit this again today.  To test, just drop a Deploy.ps1 file into your target directory, and you will no longer be able to deploy.
