### ISSUE TITLE
Octopus Server comms port does not bind to IPv6 addresses

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#1890]
See http://help.octopusdeploy.com/discussions/questions/5305

**Comment by michaelnoonan** [comment]
Relates to https://github.com/OctopusDeploy/Issues/issues/1738

**Comment by michaelnoonan** [comment]
Source: http://help.octopusdeploy.com/discussions/questions/5795-recommendation-for-mitigating-no-ipv6-support

**Comment by zentron** [comment]
#### Currently ####
__Tentacle (TCPListener)__ 
Halibut set provided `IPAddress.Any` or `IPAddress.Parse(configuration.ListenIpAddress)`  [HalibutInitializer.cs#87](https://github.com/OctopusDeploy/OctopusDeploy/blob/c527b5ea3c7cbc6846730d0e2a57a6f55d6f4bdc/source/Octopus.Tentacle/Communications/HalibutInitializer.cs#L87)

__Server (TCPClient)__ 
Halibut internally uses `new TcpClient()` [SecureClient.cs#159](https://github.com/OctopusDeploy/Halibut/blob/master/source/Halibut/Transport/SecureClient.cs#L159)


If the user provides `[::1]` as the address to listen on and `[::1]` as the address of the Tentacle then the connection still wont work because the client creation will fail with `An address incompatible with the requested protocol was used`. To allow ipv6 the client must be initialized with `new TcpClient(AddressFamily.InterNetworkV6)`

#### Solution ####
__Tentacle (TCPListener)__
This then makes the client incompatible with ipv4. The Solution for the client is to either:
* Detect the IP address provided and conditionally set the `AddressFamily` enum correctly. _(explicit single protocol)_
* Use `AddressFamily.InterNetworkV6` and set `Client.DualMode = true` to allow the client to operate over either protocol. _(automatic both protocol)_

__Server (TCPClient)__ 
On the tcp server (Tentacle). The user can provide explicitly the ipv6 localhost address however then this requires the client to communicate _only_ over ipv6 as well. The options for this server is to either:
* Leave as-is and require the user to explicitly set ipv6 or ipv4 and then configure the client accordingly. _(explicit single protocol)_
* Configure the server with `IPAddress.IPv6Any` instead of `IPAddress.Any` and then add something like ` listener.Server.DualMode = (endPoint.Address.AddressFamily == AddressFamily.InterNetworkV6);`  _(automatic both protocol)_

**Comment by zentron** [comment]
Release Note: By default bind Tentacles to both IPv6 and IPv4 address to allow communication over both protocols

**Comment by zentron** [comment]
Related issues in #1738 involve unrelated problems and will be fixed in different commits.
