### ISSUE TITLE
Support legacy Azure step types

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#1893]
We brought back Azure steps which are very similar to the 2.6-era steps. The only difference is:

 - Old steps used a SubscriptionID and a global Azure certificate
 - New steps use an account ID, which contains both of those

Instead of forcing people to upgrade, let's add support for those back so that everything just works.

**Comment by mjrichardson** [comment]
I'm thinking of implementing this as:
Import the 2.6 steps as they are, with an `Octopus.Action.Azure.SubscriptionId` variable.  
In `AzureCloudServiceActionHandler`, if `Octopus.Action.Azure.SubscriptionId` is set (and `Octopus.Action.Azure.AccountId` isn't), then populate the certificate variables with the default certificate.  Calamari should then just work.
In the UI, if `Octopus.Action.Azure.SubscriptionId` is  set (and `Octopus.Action.Azure.AccountId` isn't) then set all the fields in bound-expression mode and show a message explaining that as soon as an Account is set, it will be used rather than the imported subscription ID. At that point, the message will never be seen again, and the old subscription variable will never be used.
