### ISSUE TITLE
Calling the v3 upgrade endpoint occasionally fails

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#1909]
When the upgrade check takes place from 3.0 it occasionally fails with the following error.

```
Failed checking for updates
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request) at System.Net.WebClient.DownloadString(Uri address) at Octopus.Server.Schedules.CheckForOctopusUpgrades.CheckForUpdates() in y:\work\refs\heads\master\source\Octopus.Server\Schedules\CheckForOctopusUpgrades.cs:line 104
```

Its been noted that the call from Fiddler succeeds constantly without failure.

**Comment by alfhenrik** [comment]
This issue is very random and intermittent. I have replicated the issue when debugging but unfortunately the exception doesn't have any more details than the above error message.

As it's intermittent and random, the next call to check for upgrades succeeds, so perhaps a solution could be to implement a retry logic in the method that checks for upgrades. So if the call fails, retry immediately and if it still fails (after `n` attempts) log the warning...

**Comment by CumpsD** [comment]
Strange thing is, it never proposed an upgrade, so I'm not sure if any ever got through?

I manually installed a newer version now.

**Comment by alfhenrik** [comment]
@CumpsD so you don't get the little `bullhorn` icon between the `Configuration` menu and the `?` icon?

**Comment by CumpsD** [comment]
I can't say 100% certain, as far as a I remember, I didn't notice anything.

So from a usability point of view, I wasn't obviously made aware there was an upgrade :) Unless all the upgrade checks simply failed and 0 got through.

**Comment by DamianMac** [comment]
Known Azure issue, they should have it fixed soon (hopefully)
