### ISSUE TITLE
Every fifth deployment of the same release deletes nuget package and then re-downloads it on the next deployment

### ISSUE THREAD

**Issue by IanMercer** [OctopusDeploy/Issues#1912]
Repeatedly re-redeploying the same release over and over: every 5 releases (based on retention policy) it deletes the current nuget package and the following release it re-downloads it. The retention policy doesn't look to see if a deployment is using a nuget package before nuking it, it just looks at whether it has an `ExtractedFrom` value. So #1 gets extracted, #2 reuses, #3 reuses, #4 reuses, # 5 reuses, #1 gets wiped along with the package, #6 downloads it again as has a new 'ExtractedFrom', ... etc.

**Comment by PaulStovell** [comment]
Thanks for getting in touch. You've raised a valid issue, but unfortunately we don't think we will have time to fix this in the near future due to other priorities. We've decided to close it for now. For more information, please see the page on [why was my issue closed?](http://octopusdeploy.com/roadmap/why-was-this-closed)
