### ISSUE TITLE
Change script path strategy for offline drop packages

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1951]
See http://help.octopusdeploy.com/discussions/problems/38168

**Comment by PaulStovell** [comment]
I think we should only do this if the change is minimal, not a massive time investment.

**Comment by tothegills** [comment]
Another case this would help: http://help.octopusdeploy.com/discussions/problems/43094

**Comment by zentron** [comment]
The offline drop functionality has since been changed so that the folder can be moved around and the internal paths are all executed with relative paths. For this reason I will mark this ticket as done and closed (not wont fix).

That being the case the user will still need to `cwd` into this directory before executing however I think the current functionality should meet most users needs. Modifying so that the script can be executed with the console working directory set as anywhere may involve more work than it is worth in ensuring that all scripts inside and outside calamari still operate correctly and relative to the right location.
