### ISSUE TITLE
OctoPack 3 cannot be used without NuGet package restore

### ISSUE THREAD

**Issue by pauldambra** [OctopusDeploy/Issues#1953]
Having updated to Octopack 3 we started seeing this in our build output

 > error : You are trying to build with OctoPack, but the NuGet targets file that OctoPack depends on is not available on this computer. This is probably because the OctoPack package has not been committed to source control, or NuGet Package Restore is not enabled. Please enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=317567.

NB the targets file is in the packages folder as we commit packages to VCS.

[We don't use NuGet package restore](http://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful/) so MSBuild would (after that error was listed in the output) run successfully *including packaging with octopack* after which the build would be failed by the error listed above.

This makes Octopack completely unusable for us at v3

**Comment by PaulStovell** [comment]
Hi Paul, it would be best to contact support for this. 

If you look in your .csproj file you'll find where that error message is set. We decide to show this error based on whether the .targets file is found or not. If the files were there, you shouldn't see this error. Our unit tests for OctoPack test for this scenario and are passing, so something else must be going wrong.

**Comment by pauldambra** [comment]
How do I contact support? The files are definitely there and the octopack jobs run. But then that error fails the build...

**Comment by vanessalove** [comment]
https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md has the details you need

**Comment by sgaikwad** [comment]
I am trying to deploy the package but getting below error, please me to resolve this error.

error : You are trying to build with OctoPack, but the NuGet targets file that OctoPack depends on is not available on this computer. This is probably because the OctoPack package has not been committed to source control, or NuGet Package Restore is not enabled. Please enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=317567.
