### ISSUE TITLE
Variable filtering is not working properly

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#1956]
I created two environments (Test and Prod), and a new project, to which I added 3 variables:
```
Variable    Value     Scope
var 1       value 1   Environment=Test
var 2       value 2
var 3       value 3
```
If I filter for "var 1" in the first column, it works (1 row displayed).
If I filter for "Var" in the first column, it doesn't work (no rows displayed).
If i filter for "3" in the first column, it doesn't work (no rows displayed).
if I filter for anything in the second column, it doesn't work (no rows displayed).
If I filter for the environment scope "Test", it doesn't work (3 rows displayed).

Octopus Version: 3.0.20
Sources: http://community.octopusdeploy.com/t/variable-filtering-not-filtering-on-values-nor-scope/341 ; http://help.octopusdeploy.com/discussions/problems/26261

**Comment by robpearson** [comment]
Filters are now case-insenstive and use a string contains search instead of string starts with.

- [x] If I filter for "var 1" in the first column, it works (1 row displayed).
- [x] If I filter for "Var" in the first column, it doesn't work (no rows displayed).
- [x] If i filter for "3" in the first column, it doesn't work (no rows displayed).
- [x] if I filter for anything in the second column, it doesn't work (no rows displayed).
- [x] If I filter for the environment scope "Test", it doesn't work (3 rows displayed).
NOTE: This final item is working as designed because if an environment is not specified, it's assumed to apply to all environments.

**Comment by robpearson** [comment]
Release Note: Variable filters are now case-insensitive and check for the filter anywhere within the variable name/value etc.
