### ISSUE TITLE
Octopus Server service not starting when no internet connection due to updates check

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1962]
https://secure.helpscout.net/conversation/116887436/1249/
second report in tender .. can we handle 'no internet' servers better?
http://help.octopusdeploy.com/discussions/problems/38392

**Comment by krjensen** [comment]
And could you please add the possibility to set at proxy server only for the octopus server. Right now i can choose to take the one from Internet Explorer or none

**Comment by vanessalove** [comment]
removing priority - need to find the real issue here w/ questions for both customers

**Comment by tothegills** [comment]
Had another report of this issue in 3.0.20:
https://secure.helpscout.net/conversation/118832625/1430/

**Comment by PaulStovell** [comment]
We need a bit of information on this since we haven't been able to do it locally. 

Octopus does do an update check around startup, but it *doesn't* block the service from starting. During startup, a thread kicks off, and 30 seconds later on that thread we'll check for updates. Our check for updates call can never block the service from starting. 

I think what might be happening is a certificate revocation check (since Octopus binaries are signed, Windows/.NET will sometimes check for these) or something else. Would it be possible for someone to run Fiddler/Wireshark to see what requests are being made when the service starts?

**Comment by PaulStovell** [comment]
An update: running Wireshark while installing and starting an Octopus server from the MSI, I saw the following requests:

 - Requests to crt.usertrust.com
 - Requests to ocsp.usertrust.com
 - Requests to ocsp.comodoca.com

All of these had the user agent of `Microsoft-CryptoAPI/6.3`, so this is something that Windows/.NET is enforcing because our binaries are signed. This page explains how Windows will check to see if certificates have been revoked:

https://technet.microsoft.com/en-us/library/ee619754(v=ws.10).aspx

The Octopus check for updates requests didn't happen until long after the service reported as "Running". 

CRL checking can be disabled:

http://www.page-house.com/blog/2009/04/how-to-disable-crl-checking.html

**Comment by PaulStovell** [comment]
I compared the binaries between 3.0.19 and 3.0.20, but both sets of binaries and MSI's have the same certificates and used the same timestamp servers. 

The CRL checks in Windows will eventually time out and be ignored, the issue here is that the timeout prevents the service from starting (and this is all before any our code runs) within the service start timeout. 

A workaround would be to run:

```
Octopus.Server.exe service --start
```

By invoking the executable from the command line, the CRL checks should happen and the results cached before the service starts.

**Comment by PaulStovell** [comment]
We're going to add this setting to the various Octopus server config files to try and disable the CRL checking:

https://msdn.microsoft.com/en-us/library/bb629393(v=vs.110).aspx

**Comment by vanessalove** [comment]
Release Note: Octopus Server configuration change to disable unnecessary CRL checking
