### ISSUE TITLE
Cannot access cert for setting up SSL binding in IIS

### ISSUE THREAD

**Issue by johnkors** [OctopusDeploy/Issues#1997]
Octopus 3.0.21

I'm having issues using the SSL binding feature in IIS in a deployment step.

I'm getting an error similar to the other issues re SSL-binded deployments and thumbprints. All of those seems to be resolved by removing whitespaces from the thumbprint, but that did not do the trick in my case. 

Are there any other prerequisites? Guessing the SYSTEM account running the tentacle should have access to that cert as well? Other?

As a curiosity, the error message differs if I use a variable in the thumbprint field or put the thumbprint directly in the Deployment step view. Using a variable, the error message adds a preceding ```?``` (question mark) before the thumbprint in the error message. This is not present when put the thumbprint directly into the field (not using a variable). 
```
Could not find certificate under Cert:\LocalMachine with thumbprint ?3D9EB434FDD7D047639234DBFFD13C90D43E6183. Make sure that the certificate is installed to 
the Local Machine context and that the private key is available.
At C:\Octopus\Applications\AT\MyApp\0.1.0.60\Octopus.Features.IISWebSite_BeforePostDeploy.ps1:125 char:9+       throw "Could not find certificate under Cert:\LocalMachine with thumb

````

I've also verified it has a private key and found the thumbprint by running 
```
Get-ChildItem Cert:\LocalMachine -Recurse | Where-Object { $_.HasPrivateKey -eq $true }
```

**Comment by johnkors** [comment]
Why just closed without comment? Did I report this in the wrong place, or are you missing something?

**Comment by DamianMac** [comment]
Hi @johnkors 
Yep sorry, was trying to do a backlog clearout. We have a contributing guidelines you'd have seen when adding the issue which would have asked you to log a support ticket instead of a github issue. 

The answer to your question though is that when you copy a thumbprint from windows there is some hidden whitespace. http://help.octopusdeploy.com/discussions/problems/16467-ssl-thumbprint 
We trim it but we can't trim whitespace in a variable (because people often want it)

**Comment by johnkors** [comment]
Okay, will add a support ticket. I have no whitespace in either case.
