### ISSUE TITLE
Deployment is blocked if an azure account scoped to another environment is in use.

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2055]
User confirmed this behavior and I was able to reproduce it:

- 2 azure accounts registered: 1 scoped to the environment `prod` (AProd) and 1 to `dev` (ADev).

- 2 steps in the deployment process: 
 1 that uses the account ADev and its scoped to the environment `dev`
 1 that uses the account AProd and its scoped to the environment `prod`

- When deploying to `dev`, an error that AProd (which is not being used in this deployment) is not scoped to that environment shows up after clicking on "Deploy now".

Source: http://help.octopusdeploy.com/discussions/problems/40015
Octopus version: 3.1.3

**Comment by Dalmirog** [comment]
Seems related to #1990

**Comment by michaelnoonan** [comment]
Sounds about right because the validation doesn't exclude Steps that are scoped to an Environment, but it should.

See https://github.com/OctopusDeploy/OctopusDeploy/blob/e066de9753d6ecf713d82a91b767de9ece1efb34/source/Octopus.Server/Orchestration/Deploy/DeploymentFactory.cs#L269

We should be filtering out Steps that will be skipped when deploying to the `DeploymentEnvironment`.

**Comment by zentron** [comment]
This sounds like it could be related to issue\feature with channels where we want to ignore steps during release creation that should be conditionally skipped due to channel filter.

**Comment by zentron** [comment]
hmm.. maybe not quite as related as id hoped.

**Comment by michaelnoonan** [comment]
Release Note: Deployment Steps are now correctly filtered when validating the Azure Accounts involved in deploying a Release to a particular Environment
