### ISSUE TITLE
Server consistently crashes when creating a release using a custom step template with a rather odd variable usage

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2057]
Repro steps are a bit long, so please check the ticket below and update this Issue's subject and body to something more meaningful.

I was able to reproduce this in 2 separate Octopus instances.

Source: https://secure.helpscout.net/conversation/126278635/1963/?folderId=557082
Octopus version: 3.1.3

**Comment by michaelnoonan** [comment]
Related to OctopusDeploy/Issues#1915

**Comment by alfhenrik** [comment]
Root cause is that the variable name in the step template is `NuGetPackageId`, this field is then using an expression of `#{NuGetPackageId}` which Octostache then tries to evaluate by finding the value of the variable `NuGetPackageId`, which in this case causes an infinite recursion and ends in :sob: :boom: (aka StackOverflowException)

**Comment by alfhenrik** [comment]
Possibly another source: http://help.octopusdeploy.com/discussions/problems/42501

**Comment by zentron** [comment]
Fixed By: OctopusDeploy/Octostache@8adf836 & OctopusDeploy/OctopusDeploy@2277775
An exception will now be thrown if, during variable parsing, a reference loop is discovered. While this means an exception will still occur, the message should provide some context and it shouldn't kill the server with a `StackOverflowException`

**Comment by zentron** [comment]
Release Note: `InvalidOperationException` thrown if variable parsing discovers a self referencing loop to prevent service crash.
