### ISSUE TITLE
Powershell Scripts signing

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2093]
Creating ticket per conversation with @PaulStovell to estimate value and effort of this implementation

We've been asked a couple of times if there's a way for us a sign all the scripts we dynamically create with Octopus, as there are some scenarios with heavy GPOs that have this as a requirement to run any Powershell script at all.

**Comment by michaelnoonan** [comment]
Been thinking about this in the background just a little bit.

We don't want to distribute a certificate that we own - that doesn't really make sense. Likewise, just magically creating a self-signed certificate, and making the machine trust it, would work, but has extra complexity that I don't think is worth the effort given it's already a restricted environment. (I've seen some use GPO's/Scripts to make sure the Trusted Certificate Authorities is consistent, thwarting any attempt to use self-signed).

My thinking is that we could piggy back on the work @robpearson is doing in #1549 and let the customer import a code-signing certificate that is already trusted by their organisation. (Either signed by a Trusted 3rd party CA or their own 1st party CA). If the organisation is being this pedantic they likely already have their own code-signing certificate(s) and trusts set up.

In this case I think it would be pretty easy to:

1. `--import-codesigningcertificate` into Tentacle
2. When we build the `bootstrap.ps1`, we would sign it with the provided certificate, and then execute it.

I think we should assume they will sign their own `deploy.ps1` scripts etc, since we can't vouch for their integrity.

What do you think @Dalmirog @PaulStovell @robpearson  ?

**Comment by PaulStovell** [comment]
To me it feels like so much effort for what is really security theatre. Let's assume a bad guy manages to get a PS1 script to your machine and tricks something into executing it. Ha, thwarted via execution policies! So he just sends a .cmd file instead... oh-oh.

**Comment by zentron** [comment]
Decompiling the PowerShell cmdlet shows the unmanaged code that it calls and this has been replicated to work in-code with identical results. There doesn't seem to be any existing libraries that I could find that wrapped these calls already.

Some work/investigation: https://github.com/OctopusDeploy/Calamari/compare/feature-signps

**Comment by vanessalove** [comment]
Decided to move this to UserVoice to see if there is a great demand from the community.
https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/8509138-allow-octopus-to-run-signed-powershell-scripts
