### ISSUE TITLE
Tentacle auto updater will not install to custom path

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2103]
Tentacle auto updated will always install to default path (C:\Program Files\Octopus\Tentacle) instead of the current Tentacle path (may be D:\Tentacle for example)

**Comment by praniga** [comment]
any ETA on this as we are on version 3.1.4 of software but tentacles are on 3.0.17 thanks

**Comment by praniga** [comment]
Hi Damian

Is this fixed or custom path is not supported or will get fixed?

Thanks
Praveen Raniga
Test Environment Specialist | Central Technology Services | Technology & Innovation | ASB
09 414 8273 direct | 90273 extension | praveen.raniga@asb.co.nz<mailto:praveen.raniga@asb.co.nz> | asb.co.nz
[Email signature - bank that backs the All Blacks]

**Comment by alfhenrik** [comment]
@praniga can I confirm if you've got the `32-bit` **Tentacle** installed on a `64-bit` **OS**?
I've been doing some testing locally and the only scenario I've been able to replicate the issue where the install directory has been changed is if the Tentacle that was being upgraded was installed using the 32-bit MSI on a 64-bit OS.

We currently have an issue when auto-upgrading 32-bit Tentacles on 64-bit OS as we will pick the MSI based off the _bitness_ of the OS and if it's the incorrect _bitness_ the Windows Service executable path is not updated to point to the new path to the executable. We're working on fixing this so that the Windows Service executable path is updated if this is the case in this issue #2117.

**Comment by praniga** [comment]
Hi Henrik

Yes, that’s correct we have 32Bit Tentacle on a 64bit server.

Thanks
Praveen Raniga
Test Environment Specialist | Central Technology Services | Technology & Innovation | ASB
09 414 8273 direct | 90273 extension | praveen.raniga@asb.co.nz<mailto:praveen.raniga@asb.co.nz> | asb.co.nz
[Email signature - bank that backs the All Blacks]

**Comment by alfhenrik** [comment]
Thanks!

**Comment by alfhenrik** [comment]
Release note: When updating 32-bit Tentacles on 64-bit OSs it installs the 64-bit Tentacle so we update the Windows Service executable path to point the new installation location.
