### ISSUE TITLE
Failure to copy a file does not fail the deployment

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2106]
If copying a file fails it will be retried multiple times.  If it doesn't eventually succeed it will just move on to the next file.  I think it should fail the deployment if a file can't be copied.

**Comment by tothegills** [comment]
[servertasks-259_3b3vwr965q.txt](https://github.com/OctopusDeploy/Issues/files/23986/servertasks-259_3b3vwr965q.txt)

**Comment by tothegills** [comment]
Release Note: File operation errors (such as copying files) will fail the deployment

**Comment by burningice2866** [comment]
This actually ended up being a Breaking Change in our enviroment after upgrading from 3.0 to 3.2... at first i couldn't figure out was was going on, but after reading the release notes i found this issue.

I agree that this i most likely the correct behavior, but it should have been marked as breaking change, since existing deployment environment risk failing due to (mis)-using the fact that ie. write protected files would be ignored by earlier versions of Octopus Deploy. Thats exactly what happened with us, some devops had chosen to "freeze" a config-file  in environment instead of going for making sure Octopus was deploying a correct version of that file for that specific environment.
