### ISSUE TITLE
Duplicate variable name between Step Template and Project might cause confusions

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2126]
If a variable is configured on a Step template with the same name as a variable on a Project/Variable Set level, the latter will prevail regardless of the value entered by the user on the step fields. This has confused a couple of users already.

We could improve this by adding a warning that says `"You have duplicate variable names between the Step Template [name] and your Project or Variable Sets in use. Be aware that the latter will prevail over the values entered on the step"`

**Comment by robpearson** [comment]
Release Note: Added Verbose Logging when duplicate variables exist between Step Template vars and Project/VariableSet vars.

**Comment by eakoning** [comment]
Wouldn't it be possible to add a variable, just like the ones for [debugging variables](https://octopus.com/docs/how-to/debug-problems-with-octopus-variables#DebugproblemswithOctopusvariables-Writethevariablestothedeploymentlog) in Octopus Deploy to generate a **warning** instead of a verbose log message. Now you will see a green check mark in the dashboard and without actually explicitely opening the verbose log, you'll just never know something may have gone sideways.

**Comment by robpearson** [comment]
@eakoning This was shipped a fair time ago so it's probably a good idea to contact Octopus [support](https://octopus.com/support) if you'd like to follow-up. :)
