### ISSUE TITLE
Channel version rules should allow for empty version range

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2165]
According to the NuGet Versioning Syntax [docs](https://docs.nuget.org/create/versioning)

```
empty = latest version
```

Source: http://help.octopusdeploy.com/discussions/problems/42569

**Comment by michaelnoonan** [comment]
Relates to https://github.com/OctopusDeploy/Issues/issues/2160.

**Comment by zentron** [comment]
After some discussion we have decided that this feature request is not something that will be implemented for several reasons.

In NuGet parlance while `empty = latest version` what it is really implying is a permissive match to any version. By default, NuGet behavior will then pull and use the latest but in theory you could be actually referencing an older version and the rule is still being upheld.  In this sense Octopus Deploy is following this custom since in current behavior, with no rules, creating a new release will try and select the latest package version and is not about enforceability.

In addition any attempt to use this concept to imply an enforced rule will actually be in vain, since the version rule match only applies at release creation time. At some future point you could in theory still deploy a this release, created with an enforced latest package yet having long since deployed many more updated "latest" packages.

The simplicity of the current rule matching also makes the rule violation much more deterministic since it only needs the context of a single package version to pass or fail the test. A "latest-only" rule would make this process much more complex as the validation would need to take place within the context of all packages available at that point in time.

At this point in time this issue will therefore be closed unless an argument can be made for the contrary.
https://octopus.com/company/roadmap/why-was-this-closed
