### ISSUE TITLE
"Value cannot be null" when loging in with User\Password

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2202]
1) Sign in using de MS windows domain account link
2) Sign out of Octopus
3) ! Do NOT close browser.
4) Navigate to deployment link. (paste in same tab, or click to open new tab, doesn't matter)
5) Username+password login.
6) Error: Value cannot be null. Parameter name: instance

![null](https://cloud.githubusercontent.com/assets/6180562/11506039/14f8ddc8-982c-11e5-86c4-fb4d222caba2.JPG)

Source: http://help.octopusdeploy.com/discussions/problems/42887
Octopus version: 3.2.7

**Comment by alfhenrik** [comment]
After investigating this issue it turns out this is a _feature_ of IE...

> When Internet Explorer has established a connection with the server by using Basic or NTLM authentication, it passes the credentials for every new request for the duration of the session.

According to docs, redirecting a user to a URL that returns a `401 Unauthorized` should clear the authentication header but I've been unable to get IE to actually clear it.

To get around this issue, the user should close **all** their current IE browser windows/tabs and start a new fresh session.

There is a workaround (_nasty hack_) for this issue, which is to call `document.execCommand("ClearAuthenticationCache")`, **BUT** this clears **ALL** authenticated session and this would be an undesirable outcome I'd suggest.
