### ISSUE TITLE
Email step that follows Azure step badly formatted

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2234]
Interesting issue. If there is an email step with a lot of values that follows an Azure step, the formatting gets pretty messed up, and it appears to send twice. Customer has tested sending to a regular tentacle and the email is correctly formatted and only sent once, but when deploying to prod, it doubles and has bad formatting from the variables.

If the Azure environment names or other have weird formatting I suggest we sanitize on sending email.

Source has samples, nothing strange in account name or environment name
Source: https://secure.helpscout.net/conversation/147451963/3592/?folderId=557083

**Comment by vanessalove** [comment]
The template, samples, and task log all available in source ticket

**Comment by zentron** [comment]
The messed up emails appear to be an issue on the user's side since getting him to send it to my address shows them as correctly formatted. Getting the user to manually forward the *.eml files to our side showed that the content itself was perfectly fine but it may be getting read/processed on their client with the wrong EOL format.

The sending twice issue was also user error where they had auto release on their first life cycle phase & were performing manual release at the same time. The two emails are actually a result of two separate deployment processes.
