### ISSUE TITLE
Environment tentacle upgrade announcement too noisy

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2237]
I've had a quick chat with the team and at minimum we will:
- add a flag to the release notes if Tentacle has a change, and what the change is, to decide if you want to upgrade or not Then hopefully we will also be able to:
- add something to octopus to 'stop reminding me to upgrade Tentacles'   (it would be very  nice if this was machine or environment based for those you dont want to upgrade past 3.0.x)

And our best large dream plans are:
- extract Tentacle from the build, so it doesn't increment in versions unless it has a change and then the UI on environments page would be less noisy and only show for actual changes.

**Comment by vanessalove** [comment]
one source: http://help.octopusdeploy.com/discussions/questions/6727-frequent-tentacle-updates

But two other similar requests especially for those who have machines that need to stay on .net4.0

**Comment by zentron** [comment]
Thoughts on this one.

* Flag sounds like a good idea. Are we thinking a tag similar to how the `pre-release` tag shows up at the moment but have it say something related to `tentacle-update`? Or are we thinking more simplistic like just mentioning in the tentacle update in the release note for the ticket that includes the change?

* Possible an `ignore` button on the environments  where it has the `One or more machines are running old versions....` message that only shows up when another new tentacle version is out, or only when minor build number is bumped?

**Comment by zentron** [comment]
This task can be broken up into two parts.

## Locking Tentacle Version ##
**Some users are aware that their tentacles are out of date but for whatever reason (like requiring to be locked to .NET 3.5) they don't want to upgrade and don't need to be alerted whenever a new version is available.**

A proposed solution for this is to provide the ability to "lock" specific tentacles to their current version. This would then treat it on the environments page, for all intents and purposes, as already up-to-date, even if there is a newer one available. 

The user would be able to "unlock" this version if they want to allow it to be updated at some later stage.
It is thought that the best place for this is the under utilised "connectivity" tab of the target page.
Useful information from its last health check would be displayed to the user and they would have the ability to lock/unlock a tentacle version. (potentially even launching the update from that page as well)
![image](https://cloud.githubusercontent.com/assets/1830666/12187771/7da691a8-b5fa-11e5-86e2-d577820f4662.png)

## Dismiss Tentacle Update ##
** Often a new Tentacle build will be available for download that has no major changes in functionality (or, due to the build lockstep with the server installer there may be no change at all!). In these cases the user may not want\need to update the tentacle, yet still wants to be kept informed if another newer version comes along. **

On the environments page where we currently show:
![image](https://cloud.githubusercontent.com/assets/1830666/12187837/1bcc5f02-b5fb-11e5-8572-b8f3e71c3ac1.png)
and
![image](https://cloud.githubusercontent.com/assets/1830666/12187847/390df58a-b5fb-11e5-82af-f4f5b1e18cab.png)
Another button will be provided in the top  "Upgrade Required" box called `Dismiss Update`. This will effectively hide the info box and treat the machines as no longer needing update. 

_When the next **minor** build of the tentacle is available, the box will show up again._

They will still be able to update the tentacle if they decide after the fact that they want to upgrade by going to the specific machine's connectivity tab and, as described above, initiate the upgrade from there.

In both cases when locked or dismissed the machine icon will look like the standard machine state (accounting for differences between offline/online state)

**Comment by zentron** [comment]
Both tasks have been addressed in https://github.com/OctopusDeploy/OctopusDeploy/pull/441 and https://github.com/OctopusDeploy/OctopusDeploy/pull/443

**Comment by zentron** [comment]
Release Note: Provide mechanism to lock current Tentacle version in place and dismiss upgrade reminder.
