### ISSUE TITLE
Package step that runs in parallel and uses same package multiple times causes duplicate directory usage

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2275]
If you have a bunch of package steps run in parallel and all of them use the same package, when we unpack the directories can clash.

We should probably support this. 

Source: http://help.octopusdeploy.com/discussions/problems/43526

**Comment by michaelnoonan** [comment]
It appears that in Octopus 3.x we have always been more pessimistic/resilient in determining the extraction path - it just wasn't immediately obvious, and difficult to reproduce.

With multiple parallel steps running on the same Tentacle, including a `Thread.Sleep(5000)` to increase the chance of collision we get deployment logs like these:

**Step 1**
```
Deploying package:    C:\OctopusDev\master\Tentacle\DWebApp01\Files\OctoFX.RateService.3.0.5145.nupkg-4465a5f3-d967-481e-921e-764e489afc04
20:53:18Verbose
Extracting package to: C:\OctopusDev\master\Applications\DWebApp01\Development\OctoFX.RateService\3.0.5145_7
```

**Step 2**
```
Deploying package:    C:\OctopusDev\master\Tentacle\DWebApp01\Files\OctoFX.RateService.3.0.5145.nupkg-4465a5f3-d967-481e-921e-764e489afc04
20:53:16Verbose
Another process is finding an extraction directory, please wait...
20:53:23Verbose
Extracting package to: C:\OctopusDev\master\Applications\DWebApp01\Development\OctoFX.RateService\3.0.5145_8
```

Notice the second step logs the fact it is waiting to enter the `Semaphore` that serializes access to the extraction folder calculation logic.

Taking away the internal `Semaphore` inside Calamari leads to the same directory being used, wreaking havoc with file locks.

At this point I'm going to recommend we don't make any code changes since Octopus 3.x is much more well-behaved than Octopus 2.x with respect to parallel package deployments.
