### ISSUE TITLE
Migrator: end transaction before log conversion

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2338]
I need two more changes made to the migrator to give the remaining customers who still need to migrate a change and decent experience.

now we can convert the logs at a later date, can we complete the data transaction before the log conversion starts

**Comment by zentron** [comment]
As an additional note to this:
 Currently if there are conversion errors during the log parsing, this plays a role in the commit rules (since the configuration could be `CommitDespiteValidationErrors` or just `Commit`) Moving the task log importation outside this process means that while a dodgy task might still log out to the output, it would be too late to stop\roll back the import.

Probably acceptable behaviour, but just worth mentioning.

**Comment by michaelnoonan** [comment]
Release Note: The migration process is now split into two stages, the first to import data, and the second to import task logs, making it easier to migrate very large backups from previous versions of Octopus
