### ISSUE TITLE
Environment restriction from team membership should not override access granted by Administrators membership

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2436]
As reported here: http://help.octopusdeploy.com/discussions/problems/44928

Where is user has a permission granted for all environments, this should take precedence over a restricted permission granted by membership of another team.

**Comment by mstum** [comment]
Hi,

the discussion is private, can someone give a quick overview of the before/after?

Thanks!

**Comment by markryd** [comment]
On the Environments -> Accounts screen, the list of Azure Subscriptions is filtered so that a user only sees subscriptions for an Environment where they have the View Accounts permission.

What was happening was that if a user was a member of two teams, one that had View Accounts on an Environment and one that did not, the user would not be able to see accounts for that Environment. In the reported issue, a System Administrator could not see some accounts because they were also a member of a team that didn't have this permission for one environment

This has been changed so that if a user is a member of a team withe View Accounts permission on an environment they can see that environment's Accounts on this screen no matter what other teams they are a member of.

No other views or actions were changed.
