### ISSUE TITLE
Channels steps defined by name not ID

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2452]
The steps you define for your channel rules are recorded by their name. So when you change the name, suddenly the package step stops using the package rule to select the package because it cannot match the step anymore.

This should be linked via ID and not rely on the customer updating the step name and then going into each channel and removing/reselecting the step.

Source: http://help.octopusdeploy.com/discussions/problems/45202

**Comment by zentron** [comment]
[ ] Update Server to commit Action ID
[ ] Update Front end to understand ActionID
[ ] Ensure `Octopus.Client` still works
[ ] Add DB Upgrade script
[ ] Add code to migrator to allow importing using action name, but mapping to ID

**Comment by droyad** [comment]
Steps to reproduce rename error:

1. Add an action
2. Add a channel and a channel rule for that action
3. Rename the action
Expected: Channel rule maintains reference to the action
Result: The channel rule now has an invalid reference to the action
Fix: Reference actions by ID in channel rules. 

The channel rule action is also used when validating the creation/editing of a release, so that also needed to change the way it compared actions.

Steps to reproduce delete error:
1. Add two steps (actions) A and B
2. Add a channel "X" and a channel rule referencing both actions
3. Add a channel "Y" and a channel rule referencing Action A
4. Delete action A
Expected: The rule on channel "X" now only references action B and the rule on channel "Y" is removed.
Actual: Both channel rules reference a non-existent action
Fix: Delete Channel rule action reference when action is deleted and delete the whole rule if there are no actions (as a rule needs at least one action).
