### ISSUE TITLE
Built-in package feed retention does not scale

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2476]
Apply package retention on the built-in package feed does not scale well, in some cases taking several minutes to run.  The important bottleneck to fix is the `Release_WithDeploymentProcess` view as it annoys DBAs when it runs for a long time.  The time taken for the view to run seems to be correlated with the size of the deployment process (the amount of JSON).

See: https://secure.helpscout.net/conversation/195870893/0/?folderId=571723

**Comment by MJRichardson** [comment]
The bottleneck here seems to be sending the DeploymentProcess JSON column across the network.

Ideally we wouldn't have to, but to run the clean-up for the built-in package repo, we need the IDs and versions of packages used by deployment steps in releases, and this information is buried in the JSON column of the `DeploymentProcess` table.

Long term, perhaps the fix is to spit the Deployment Steps out into their own table?  And make the fields we are interested in columns, rather than JSON properties.  But this is a substantial change.

A short term fix may be to iterate over the `Release_WithDeploymentProcess` view in batches, rather than doing a `Select *`.  The same overall amount of work will have to be done, and the clean-up process will likely take longer, but it should prevent the > 5 minute query time currently seen.  And since the clean-up process is on a background thread anyway...

**Comment by MJRichardson** [comment]
Created an issue to move Deployment Steps into their own table: https://github.com/OctopusDeploy/Issues/issues/2508
