### ISSUE TITLE
"IIS Application - Create" step template incorrectly check for parent site existence

### ISSUE THREAD

**Issue by KasperHoldum** [OctopusDeploy/Issues#2500]
The "Get-Website" cmdlet is used which has an active bug that ignores the -name parameter thus returning all websites. So the following check just checks if any website exist:
```
$site = Get-Website -name $parentSite
if (!$site) {
    throw "The web site '$parentSite' does not exist. Please create the site first."
}
```

It should instead be changed to:
```
try{
   **$site = Get-Website |?{$_.Name -eq $parentSite}**
} 
catch [System.IO.FileNotFoundException]{
   $site = Get-Website |?{$_.Name -eq $parentSite}
} 
finally {
    Write-Host $site.name # or do whatever meaningful thing we want to do...
}
```

Or similar.

**Comment by vanessalove** [comment]
Hi @KasperHoldum 

The library site has its own repository and each PR can be commented on. https://github.com/OctopusDeploy/Library
Otherwise the best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)
