### ISSUE TITLE
Memory leak in browser viewing Octopus UI

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#2576]
If the tab with Octopus UI is left unattended for a couple of hours it consumes all available memory.
If you try to investigate with dev tools in chrome it releases excess memory.

Shannon had this happen - please speak to him about findings.

Source: http://help.octopusdeploy.com/discussions/problems/46489

**Comment by slewis74** [comment]
Had another report of this type of issue, https://secure.helpscout.net/conversation/359928315/15455/?folderId=909887

Think this case relates specifically to the Deployment page, when waiting for a manual intervention and left unattended.

I set the scenario up locally and the page keeps polling the server every 2s, even while waiting for the intervention.  It presumably has to do this, because the task is technically still running and someone else could intervene and it'll move to the next step etc.

Over a couple of minutes memory usage was creeping up, so after a few hours it could certainly cause issues.

**Comment by DmitryLobanov** [comment]
Frankly, we're really tired of that bug. The time when our tabs get unresponsive is already not hours, but minutes. This makes Octopus usage a constant pain. And it's sad to see this bug does not get enough attention from Octopus team.

**Comment by alfhenrik** [comment]
@DmitryLobanov thank you for letting us know, we are currently working hard on rebuilding the entire UI of Octopus (which we hope to release in 4.0).

**Comment by jetcool** [comment]
Like the others mentioned, Octopus UI is leaking memory, it is quite annoying. 
How to reproduce: Open a new tab and leave it there for a few hours. 
Note: We have a lot of projects in Octopus (~600, and about 100 project groups).
![image](https://user-images.githubusercontent.com/2924348/29176147-4ffa5400-7deb-11e7-9104-f10c4027a2a4.png)

**Comment by michaelnoonan** [comment]
Yes, Octopus 4.0 is a completely rebuilt UI using TypeScript and React. We will be testing this against a huge instance with lots of data to see if we can replicate performance and memory issues before shipping.

**Comment by pawelpabich** [comment]
This was tested by one of our large customers and no leaks has been observed.

**Comment by pawelpabich** [comment]
Release Note:  Octopus UI shouldn't leak memory any more
