### ISSUE TITLE
TFS Plugin - Build URL in Octopus release notes leads to 404

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2587]
When we create a release from the TFS plugin, we add the Build URL in the Octopus release notes. This URL leads to a 404.

![buildurl](https://cloud.githubusercontent.com/assets/6180562/16660367/5d716e0c-4444-11e6-9541-490af2663109.png)

Current: https://dalmiro.visualstudio.com/OctopusTest/_BuildvNext#_a=summary&buildId=16

Expected: https://dalmiro.visualstudio.com/OctopusTest/_build?_a=summary&buildId=16

This was tested in VSO, not in a hosted TFS instance. Maybe that has something to do with this issue?

**Comment by SparrowAvanade** [comment]
We are seeing this issue on Octopus 3.3.6 as well.

**Comment by Dalmirog** [comment]
@SparrowAvanade The error actually comes from the TFS plugin, and not from Octopus itself.

Somewhere along these lines https://github.com/OctopusDeploy/OctoTFS/blob/master/source/VSTSExtensions/OctopusBuildAndReleaseTasks/Tasks/CreateOctopusRelease/Octopus-CreateRelease.ps1#L78-L103

**Comment by MarcusFelling** [comment]
Are you using TFS on-prem? I added the following to the build task to fix this:

#Octopus converts _ to - in project name for URL. Check for this and convert if necessary. 
If($projectname -match "_")
{
    $projectnameURL = $projectname 
    $projectnameURL = $projectnameURL -replace "_", "-" 
    write-host $projectnameURL 
} 
else
{ 
    $projectnameURL = $projectName 
} 
$markdownContent = "Octopus release for project $ProjectName was created.`n[See the details here]
($octopusUrl/app#/projects/$projectnameURL/)" 
$markdownContent | Out-File $markdownFile 
Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Octopus Release;]$markdownFile"

**Comment by MarcusFelling** [comment]
Sorry, first time commenting on waffle.io, the formatting messed up my script. To put it simply, the build task converts underscores to dashes in the project name url. The above replaced dashes with underscores to fix this.

**Comment by MarcusFelling** [comment]
Here is the code on Paste Bin: http://pastebin.com/VfeQZniG

**Comment by SparrowAvanade** [comment]
The issue is not that underscores ‘_’ need to be changed to hyphens ‘-‘.

The issue is as follows:

We have a build definition defined in VSTS using the “Create Octopus Release” build step.

One of the things this step does is create and publish markdown release notes into Octopus that contain a link to the VSTS Build that created this release

Example: https://avanade-psg.visualstudio.com/AMP/_BuildvNext#_a=summary&buildId=986
[cid:image003.jpg@01D1DD28.14278660]

This Url is incorrect.  It should be: https://avanade-psg.visualstudio.com/AMP/_build#_a=summary&buildId=986

I have confirmed that this occurs when the build is running on a TFS Build Server and a Hosted instance.

**Comment by Dalmirog** [comment]
When this issue was created the VSTS extension was in version `2.x` which was based entirely on `Powershell` scripts. 

In `3.0` we migrated to `Typescript` and fixed this error (among many others).

Closing this issue as fixed.
