### ISSUE TITLE
Update Step Template variables to use new generic package variable names

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2652]
With the `3.4.0` update a change was made to special variables to deprecate `Octopus.Action.Package.NuGetPackageId` and replace with a more generic `Octopus.Action.Package.PackageId`.
As part of this process it appears that the parameters on step templates were not updated. 
Although in the conversion to project steps they should be correctly updated, the existing steps should be updated as this may otherwise cause their values to confusingly not show up in the UI for step templates.

**Comment by dstrickland-mdl** [comment]
Seems as though something is broken here.  We were using OctopusPackageName.  As of 3.4.0 & 3.4.1, there is a very strange bug which has completely stopped us in our tracks here.

The value of OctopusPackageName is being rendered in the powershell scripts randomly.  Sometimes it has the actual name and sometimes it is the text of the varlble [ #{Octopus.Action.Package.NuGetPackageId} ]  instead of the actual Value.

**Comment by zentron** [comment]
@dstrickland-mdl when you say sometimes its the value sometimes its the text do you mean if you deploy the same release with the same configuration multiple times you get different results? Is the step from a library template? What does the project look like? 
The old variable should still be getting set with the same value but it sounds like there is an approach that has been missed. 
If you manually supply a project variable `Octopus.Action.Package.NuGetPackageId` to reference `#{Octopus.Action.Package.PackageId}` does it then consistently work?

**Comment by zentron** [comment]
@dstrickland-mdl we have found what may have been the cause of your issue and it should be patched in the next release. Details are available on the related ticket at https://github.com/OctopusDeploy/Issues/issues/2679
