### ISSUE TITLE
Running Azure Web Deployment Script Template against a Cloud Target fails to find package

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2655]
Server: 3.4.0

1. Create a Azure Web App Deployment step template.
2. Reference step in project an set role to deploy to cloud region target 
3. Deploy

Result: Deployment fails with below error
![image](https://cloud.githubusercontent.com/assets/1830666/17951952/67aa6a78-6aa9-11e6-9412-7b490c16f245.png)

Source: http://help.octopusdeploy.com/discussions/problems/47172

## Workaround
Create a brand new step or step template and copy the details across.

**Comment by michaelnoonan** [comment]
We discovered the source of this problem:

- Brand new steps in 3.4.x get a property `RunOnServer = true` which has the side-effect of downloading the package on the Octopus Server
- Steps which are upgraded from before 3.4.x don't have that property, and the packages were being ignored due to a bug in Package Acquisition.

We propose to fix the logic on the Octopus Server in Package Acquisition planning, and improve the logging. Also the UI says slightly different messages based on `RunOnServer = true` so we should consider making this consistent.

**Comment by michaelnoonan** [comment]
Another source (private): http://help.octopusdeploy.com/discussions/problems/47408-switched-to-cloud-regions-now-getting-no-package-for-the-action-xxx-on-the-server-was-acquired

**Comment by tothegills** [comment]
Release note: Upgraded Azure steps should not work again
