### ISSUE TITLE
Enable untenanted projects to be deployed to tenanted deployment targets

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2722]
(Same logic applies to Accounts)

We made a decision during the beta phase of Octopus 3.4 to make a clear distinction between tenanted deployment targets and untenanted deployment targets. The main reasoning was that we shouldn't accidentally leak dedicated-tenant variables and deployments onto shared servers.

This decision prevents a scenario where you want to deploy tenanted applications onto a server, and use another project to deploy a common component like a telemetry agent.

The workarounds available are:
1. Add another tentacle to the server (one tenanted, the other untenanted) but this adversely affects licensing
2. Create a dummy tenant and make the common project use that dummy tenant.

We should enable this situation in a nicer way. Current options we're considering are:
1. Use the project > settings > multi-tenant deployments option as a way to modify the deployment target calculation when starting a deployment.
2. Add another setting to the deployment targets so they can define how they participate in tenanted/untenanted deployments.

Source: http://help.octopusdeploy.com/discussions/questions/9090-tenanted-un-tenanted-and-deployment-target-licence-double-use

Source: http://help.octopusdeploy.com/discussions/questions/9061-feature-use-account-for-tenant-and-non-tenant-deployments

Source: http://help.octopusdeploy.com/discussions/questions/9031-tennant-and-non-tennant-deploys-to-the-same-server

Source: https://secure.helpscout.net/conversation/344338204/0/

### Update 30/05/2017:  The implemention for this issue is in progress

Our working plan is to address this by replacing the Tenants section on the Machine settings with something like the following:

![machine-tenants-exclude](https://cloud.githubusercontent.com/assets/113759/26539627/de96d060-4490-11e7-878c-361ff999dd6f.png)

Selecting the 2nd or 3rd option will cause the Tenant selector you see today to be displayed.

![machine-tenants-include](https://cloud.githubusercontent.com/assets/113759/26539637/e93f4dd0-4490-11e7-9904-d6694246e040.png)

Machines currently assigned to tenants will default to option 2: _Include only in tenanted deployments_.

Selecting option 3: _Include in both tenanted and un-tenanted deployments_ will do just what you would expect.

**Comment by zentron** [comment]
Also need to keep in mind\test what this means for permissions

**Comment by TIllingworth** [comment]
This is currently having a huge impact on licence use, I know there is a workaround however the time required to configure our current deployment process would be very large. Are a large number of people experiencing this issue?

**Comment by tothegills** [comment]
> Add another setting to the deployment targets so they can define how they participate in tenanted/untenanted deployments.

Could use machine policy

**Comment by TIllingworth** [comment]
An alternative might be to only have a single licence usage when you have multiple connections to the same machine, though this may not work with the design currently in place and allowing a deployment target to be configured as tenanted and untenanted specifically may be a better option.

**Comment by ohTHATaaronbrown** [comment]
Add another customer to your list who want the ability to mix tenanted and non-tenanted work on deployment targets, please.

Our use case is this: 
* we have a whole bunch of operations-related deployment projects that are tenant-agnostic, but operate on machines that have tenanted applications installed as well as on common, non-tenanted servers (like common database servers, etc).
* we also have deployment projects that we want to make tenant-aware.

The proposed dummy tenant workaround is cumbersome in large environments.

We need to be able to deploy our back-end operations projects to the same deployment targets as we deploy our tenanted applications to.  Ideally without having to make the operations deployments "tenanted".

**Comment by ohTHATaaronbrown** [comment]
I also have a desire to have some steps in a deployment run only once per machine, while other steps run once per tenant per machine.  I don't see this as possible in the current tenant implementation.  Am I missing something?

**Comment by graemechristie** [comment]
+1. Again we have too many Tentacles and Projects for the Dummy Tenant Hack or Running multiple tentacles per server to be feasible.

**Comment by TIllingworth** [comment]
Also, not to be picky but technically doesn't this break the way licences work since you'd end up using multiple licences for the same deployment target. Is that good enough to categorise this as a bug?

**Comment by tobylo** [comment]
I won't repeat what people before me has written, but here is another customer that is affected negatively by this descision. Sadly, neither of the workarounds are feasible solutions in our case.

**Comment by henkmeulekamp** [comment]
Added user-voice request; https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/16616209-allow-non-tenant-and-multi-tenant-deployments-to-t

**Comment by juliank** [comment]
I would also like to chime in on this issue. In our case, we would like to gradually move some of our projects over to using tenanted deployments. However, some of the projects are "composite", with several projects deploying to the same deployment target, and not all of the projects should us a tenanted model. Using the proposed dummy tenant solution appears to be a bit cumbersome.

**Comment by michaelnoonan** [comment]
Thanks so much for taking the time to weigh in on this issue. I can't give you an estimate of when this will be completed, but I did want to let you know this issue is high on our radar. Enabling everyone to fully adopt multi-tenant deployments in Octopus is important to us.

Hope that helps!
Mike

**Comment by espenwa** [comment]
We are also eagerly awaiting being able to deploy a mix of tenant and non-tenant-based projects on the same targets. The version-tag on this issue says 3.4 - have you any information about the currently targeted release?
(Tenants/Channels are very nice features, and we plan to use them in-house for keeping multiple versions in production simultaneously in an enterprise environment).

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enable untenanted projects to be deployed to tenanted deployment targets](https://trello.com/c/tpc4wCYz/37-enable-untenanted-projects-to-be-deployed-to-tenanted-deployment-targets)

**Comment by MortenChristiansen** [comment]
> "Card not found.
> 
> This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams."

**Comment by lonevvolf** [comment]
Yes, it would be nice to know the status here - it still references 3.4, which is a bit in the past;  :)

**Comment by vanessalove** [comment]
@MortenChristiansen @lonevvolf Not all the links that we provide are for public consumption such as private support tickets as source documents and also links to our internal trello. They are to link to our systems and allow us to provide the context we need for our processes.

The was added to a roadmap in a trello so the aim is to be completed in Q1 for this year.

While it says release/3.4 in a tag that is also a tracking tag of ours and nothing to do with intended milestones. It was for a feature released in that version.

**Comment by mackayj** [comment]
@vanessalove Any update on the timeline? We currently have to edit the environment every time we want to deploy to our mixed tenanted / non-tenanted servers

**Comment by michaelnoonan** [comment]
Hi @mackayj - we don't have a fixed date to ship this logic change. Please be assured it is definitely on our roadmap and we will post updates in here once it gets to the top of the stack. Hope that helps!

**Comment by bjammin** [comment]
It's been 3.5 months since the last update in this thread, and nearly 9 months since this was first raised.  In that time there have been 9 major version releases that could have included this.

Is it really still on the roadmap?

**Comment by MJRichardson** [comment]
Hi folks,

### Update:  The implemention for this issue is in progress

Our working plan is to address this by replacing the Tenants section on the Machine settings with something like the following:

![machine-tenants-exclude](https://cloud.githubusercontent.com/assets/113759/26539627/de96d060-4490-11e7-878c-361ff999dd6f.png)

Selecting the 2nd or 3rd option will cause the Tenant selector you see today to be displayed.

![machine-tenants-include](https://cloud.githubusercontent.com/assets/113759/26539637/e93f4dd0-4490-11e7-9904-d6694246e040.png)

Machines currently assigned to tenants will default to option 2: _Include only in tenanted deployments_.

Selecting option 3: _Include in both tenanted and un-tenanted deployments_ will do just what you would expect.

### Permissions

We are also intending to make a change to the permission model to correspond with the above. We are going to change the way the **permissions for teams without tenant scope** are handled.

Currently:

- **Team without tenant scope:** The permissions for a team not scoped to any tenant(s) apply ONLY to un-tenanted machines. This team's permissions do not apply to tenanted machines.

- **Tenant-scoped team:** The permissions for a team team scoped to tenant(s) apply ONLY to the machines scoped to those same tenant(s). This team's permissions do not apply to un-tenanted machines.

After this change:

- **Team without tenant scope:** The permissions for a team not scoped to any tenant(s) will apply to both tenanted and un-tenanted machines. _This aligns with the behaviour of teams not scoped to any environments/projects - it's like a wildcard_.

- **Tenant-scoped team:** The permissions for a team team scoped to tenant(s) apply ONLY to the machines scoped to those same tenant(s). This team's permissions do not apply to un-tenanted machines. _This is the same behaviour as today_.

This change will align tenant scoped permissions with how environment/project scoped permissions are interpreted. We also believe this new behaviour corresponds with the way most people grant permissions.

The end result is:
- Grant `MachineView` to a team with the scope `Environments: Production`: All members of this team can view machines in the Production environment. _This is common when you have certain people managing all machines in an environment_.

- Grant `MachineView` to a team with the scope `Environments: Production` and `Tenants: A`: All members of this team can view machines in the Production environment allocated to tenants A. _This is common for 3rd-party self service access_.

- Grant `MachineView` to a team with the scope `Environments: Production` and `Tenants: A, B, C`: All members of this team can view machines in the Production environment allocated to tenants A B or C. _This is common when you have certain people managing machines on behalf of certain tenants_.

**Comment by bjammin** [comment]
Thanks Michael, this looks like a good solution and I appreciate the update.

**Comment by MJRichardson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow tenanted machines to participate in un-tenanted deployments](https://trello.com/c/lsokmOKw/4-allow-tenanted-machines-to-participate-in-un-tenanted-deployments)

**Comment by mackayj** [comment]
@MJRichardson 

> Card not found.
> 
> This card may be on a private board. You may be able to view it by logging in.
> 

Been looking forward to this update for a while now, can you give us a rough ETA?

**Comment by KasperHoldum** [comment]
We're also waiting for this feature to be able to roll out tenanted deployments mixed with untenanted deployments. Any ETA?

**Comment by MJRichardson** [comment]
@mackayj @KasperHoldum 
Thanks for your patience folks.  This will ship with Octopus 3.15, which if everything goes according to plan will be released next week.
