### ISSUE TITLE
[Bug, 3.4.0] Release notes won't render when contents inside brackets are special characters 

### ISSUE THREAD

**Issue by johnkors** [OctopusDeploy/Issues#2747]
Using Octopus 3.4.0.

Im trying to create release notes containing git log (containing authors), and some of these authors have norwegian special characters Æ, Ø or Å in them. When we include these kind of authors in brackets, no release note content is rendered on the release page. It's so sad to see some of my co-workers not getting any credits for the work they put in :/ ;)

Editing the release notes of a release to this:
```
<Bjørn harald> Did stuff
<Anders> Updated readme
```
   Result: :broken_heart:  Nothing is rendered after saving it.

```
<John> Did stuff
<Anders> Updated readme
```
  Result: :white_check_mark:  Only the names are omitted and contents after each name is rendered.

![releasenotes](https://cloud.githubusercontent.com/assets/206726/18437886/459de1ee-78ff-11e6-81af-a6409489dc07.gif)

**Comment by michaelnoonan** [comment]
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

From first glance it looks like the reason is because `<stuff>` or `<Mike>` would be interpreted by the Markdown parser as an HTML tag. Could you try a different format like `*Mike* did something amazing`?

![](http://recordit.co/DVNmmVBMXI.gif)

**Comment by johnkors** [comment]
Yeah, sure - it can always be worked around by using other characters, but that's a bit besides the issue of this bug.

I was not aware of the specifics of the markdown parser you're using, and not sure that I would need to as a user either. Anyways, open a issue in your tracker if you feel it's something you need to track. Just wanted to report that behaviour varies with the characters used, which is not very intuitive.
