### ISSUE TITLE
Event trigger deadlock

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2748]
See http://help.octopusdeploy.com/discussions/problems/47464

**Comment by thebigmoosey** [comment]
Triggers are used in two tables, Event and Deployment (to populate the associated related document tables). Suggest we remove triggers from Octopus completely and replace with code in c# instead. Event should be easy because it's all contained in the `EventStore` class. Deployment will need an equivalent Store class made to contain all this new logic. It should be easy to find all instance of the trigger's usage, search the code for 'TABLOCKX'.

**Comment by thebigmoosey** [comment]
Release note: Replacing SQL triggers with code-based triggers (to help us track future deadlock issues)
