### ISSUE TITLE
Duplicates appear in audit log

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2775]
For example, when deleting a machine:
![image](https://cloud.githubusercontent.com/assets/171197/18733472/9aed0952-80ae-11e6-8de4-47be32ff5ae1.png)

**Comment by thebigmoosey** [comment]
These are actually separate events (the standard Document Delete and Machine Delete) they just have the same  description, so it appears they are logging twice. Suggest coming up with a different name for the Machine-related events so they don't cause confusion. We still need to show them in the event log in case people specifically want to select those machine-related events.

**Comment by zentron** [comment]
Another thought is that (without having read through the code) the second event shouldn't even be logged since by definition it could only occur iff the first one has been logged

**Comment by thebigmoosey** [comment]
This issue can be closed. We updated the naming around these events so they don't appear as duplicates anymore (fixed many months ago as part of a separate ticket, possibly when we were implementing subscriptions).

@zentron We use the second event for auto-deploy event sourcing. Not logging it will stop certain auto-deploy scenarios from functioning.

**Comment by zentron** [comment]
Still seems wrong that the user-initiated "event" logs 2 records. but if its closed its closed :)

**Comment by thebigmoosey** [comment]
Yea agree, this ended up being a byproduct of some auto-deploy decisions made back in 3.4 and then some 3.5 decisions re. subscriptions (to help us more easily target `MachineAdded`, `MachineDeleted` etc events in code).

To help clarify, in 3.4 we previously hid these "duplicate" events on the audit screen, but once we added subscriptions in 3.5 (where users could subscribe specifically to `MachineAdded` events etc), that solution no longer made sense (because I might want to filter my audit screen and only see `MachineAdded` events). So instead we updated the name of the events so people could recognise that they are not actually duplicate events. ie. One of the events is the document-related event and the other is the auto-deploy domain event.​ Long explanation, but yea, that's the history :)

**Comment by tothegills** [comment]
Could events have a document type so could stick with the existing `Created`, `Modified`, `Deleted` categories and still be queryable for things like auto deploy and subscriptions?  Would also make it easier to add triggers for others types of documents in the future without creating a new set of "system" events that essentially duplicate what we already have.
