### ISSUE TITLE
Allow auto-deploy to have an order of deployment

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2798]
Currently there is no way to determine which auto-deploy project will deploy first when a machine comes online. There are cases where one project needs to be deployed first due to having dependencies for other projects and the deployment order is crucial.

Spoke to Mark S about this and suggestion for a order field when you define the trigger where you can give it a number seems to be an easy way to make this happen.

Source: http://help.octopusdeploy.com/discussions/questions/9309

**Comment by michaelnoonan** [comment]
What kind of guarantees about sequencing are required?

It would be easy to enqueue the deployments in order, but more difficult to complete one deployment before starting the next...

Placeholder for a conversation.

**Comment by gurufordy** [comment]
Hi Michael,

For me I've got a load of applications that share an environment and some depend on each other and so order is important but not paramount here.. However on top of that I now have a DSC project that I want to trigger before anything else as it's setting up some of the fundamentals on the box before the apps get a chance to use them.

So I guess I need a guarantee that I can at least run my DSC deployment first sorry.

**Comment by michaelnoonan** [comment]
Hi @gurufordy. Thanks for letting us know about your scenario. One idea would be to add your PowerShell DSC as part of a Custom Health Check script in your Machine Policy for these machines, and only report them as Healthy once the DSC reports no drift. This means you can set your Auto Deploy Trigger to fire only when the Machines become healthy, instead of simply becoming available.

For application dependencies, I personally try to push those requirements down to the application layer, so each application is able to check the health of downstream dependencies and report their own health to upstream services, like load balancers etc. I like to use a simple library like https://github.com/uglybugger/NotDeadYet. This has the added effect of making your applications potentially more resilient to transient failures, not just deployment ordering.

One idea we are toying with is to have some kind of dependency between projects, sort of like TeamCity, so if you trigger a deployment, Octopus could make sure all the deployments are up to date on earlier projects before running a later project.

Or the opposite, perhaps one project could trigger another. (You can do this yourself right now by using https://library.octopusdeploy.com/step-template/actiontemplate-chain-deployment which allows you to chain deployments together.

It's early days and we need to do a lot of thinking about the knock-on effects of building these concepts into the box.

Hope that helps!
Mike

**Comment by michaelnoonan** [comment]
Hi Everyone,

I've been putting some time into this issue over the last week. We aren't planning to add inter-project dependencies to Octopus in the short-term, this is something we need to spend time on to get right.

In the meantime we think the best way to configure this kind of scenario is to create an **orchestration** project with the Automatic Deployment Trigger in it, which would use the [Chain Deployment](https://library.octopusdeploy.com/step-template/actiontemplate-chain-deployment) step to execute all of the deployments for the actual projects in order.

I've written a documentation page all about [Automatic Deployment Triggers](http://docs.octopusdeploy.com/display/OD/Automatic+Deployment+Triggers) with a lot of answers to common questions.

I'm sorry to bring bad news in the short-term. We do have a UserVoice suggestion that is gaining votes, and you could add your vote in there also: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/9811932-allow-project-dependencies-so-deploying-one-proj

Hope that helps!
Mike

https://octopus.com/company/roadmap/why-was-this-closed

**Comment by gurufordy** [comment]
Thanks Michael, will vote on the UserVoice and see how we can use the step template you linked to in the short term :+1:
