### ISSUE TITLE
Old task logs with manual intervention steps do not render correctly

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2830]
The steps after the manual intervention step are not mark as successful.

Repro steps:
- Install Octopus 3.1
- Create a deployment process with a script step, manual intervention step, another script step
- Create a release and deploy
- Upgrade the server to latest

Look at the task log:
![image](https://cloud.githubusercontent.com/assets/171197/19336045/7b9426a0-914b-11e6-93ce-4ab7b51ca1bb.png)

**Comment by tothegills** [comment]
Log differences:

[ServerTasks-3.1.log.txt](https://github.com/OctopusDeploy/Issues/files/528362/ServerTasks-3.1.log.txt)
[ServerTasks-3.4.log.txt](https://github.com/OctopusDeploy/Issues/files/528364/ServerTasks-3.4.log.txt)

**Comment by NickJosevski** [comment]
Sigh 
3.1.0 
 ![image](https://cloud.githubusercontent.com/assets/119096/23782779/abd2c31e-05a2-11e7-85c1-17a78ac3a270.png)

3.4.0
![image](https://cloud.githubusercontent.com/assets/119096/23783043/49742d78-05a4-11e7-92aa-afb2b1858ac8.png)

**Comment by NickJosevski** [comment]
## Cause

The 3.1.0 code has put a root level "FIN" block to mark the end of the `intervention step`, where was after 3.5.0 it marks it at the level (see right hand side of log compare).

Left 3.1.0, Right: 3.11.9
![image](https://cloud.githubusercontent.com/assets/119096/24337519/57cd29d4-12e1-11e7-8576-b0a0f33276a7.png)
 
Since 3.4, in `ServerLogStorage.ReadLogsFromFile` the top level "FIN" blocks are used to create a new ActivityLogTreeNode, to support multiple deployments in the same task.

## Fix 

The only fix worked out so far is *not-ideal* it would require detecting this non-intended "FIN" block and correcting the structure of the resulting `ActivityLogTreeNode`s. It cannot be detected until the task log is fully processed. If the task contains an erroneous top level "FIN" block and no other "PLN" (planned) blocks after it, then it is likely the error case.

Therefore the check would need to run first to see if the task being loaded is from 3.1.0 or earlier version, then do the check for the no "PLN" entries after existing after a root level "FIN".

There's some [code on this branch](https://github.com/OctopusDeploy/OctopusDeploy/commit/3cedd1f3ee7dc3367d04b4e055ded5fcf3fed3bd), if needed in the future.

## Outcome
Leave this for now, if it becomes a significant issue revisit for an lower impact solution.
