### ISSUE TITLE
Deployment continues after retrying 10 times in guided failure mode

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2885]
**Setup**

- Enable "Guided failure" on the environment
- Have a step that always fails in your deployment process (I tested this with a PS step with `write-error "such error"`) and another one that always succeeds.
- Deploy it, take ownership of the interruption and retry 10 times.
- After the 10th time, the failing step will be skipped and the deployment will continue with the next step instead of failing for good.

**Source**: https://secure.helpscout.net/conversation/272634224/10894 (see questions by dalmiro and comments by mark on this private link)

**Octopus**: `3.4.15`

**Comment by vanessalove** [comment]
Note that the discussion around this is that stopping after 10 retries is reasonable, but instead of continuing automatically it should fail the deployment. Maybe with a 'this is the last chance' style warning before clicking.

**Comment by droyad** [comment]
After the final retry, the screen now looks like this:

![image](https://cloud.githubusercontent.com/assets/1687639/22807222/9befc934-ef71-11e6-84b4-fd2f0bd324a4.png)

Normally looks like this:

![image](https://cloud.githubusercontent.com/assets/1687639/22807258/d39c4cea-ef71-11e6-986a-d2e9711db836.png)

Note the lack of the `Retry` button and the extra test below the header.

This allows the person to choose to ignore or fail instead of just failing. They can then also add a note. In the end we raise the interruption 11 times, but only allow 10 retries.
