### ISSUE TITLE
OctoDiff being supplied partial signature file during deployment

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#2906]
As reported here: http://help.octopusdeploy.com/discussions/problems/48599

Partial signature files are temporary files used during signature creation.  They should not be supplied as parameters to OctoDiff.exe.

```
Using package C:\Octopus\Packages\efc\efc.9.13.0.127.nupkg with hash e4419bf682f4656159e583f28f019c211f03db3a for creating delta
16:41:31   Verbose  |           Building signature file: C:\Octopus\OctopusServer\PackageCache\efc.9.13.0.127.nupkg.octosig
16:41:31   Verbose  |           - Using nearest package: C:\Octopus\Packages\efc\efc.9.13.0.127.nupkg
16:41:31   Warning  |           The previous command returned a non-zero exit code of: 4
16:41:31   Warning  |           The command that failed was: "C:\Program Files\Octopus Deploy\Octopus\Octodiff.exe" signature "C:\Octopus\Packages\efc\efc.9.13.0.127.nupkg" "C:\Octopus\OctopusServer\PackageCache\efc.9.13.0.127.nupkg.octosig.partial" --progress
```

**Comment by droyad** [comment]
The parameter to OctoDiff has intentionally included `.partial` since [this](https://github.com/OctopusDeploy/OctopusDeploy/commit/f550bf845ec275d7a56ff7877d104c90bf3ddf19) commit 2 years ago.

Possibly the partial file already existed, causing this problem.

However no reports since. So closing this issue.
