### ISSUE TITLE
Custom proxy servers don't work for HTTPS-based NuGet feeds

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2926]
To replicate:

1. In Octopus, add this NuGet feed: https://www.myget.org/F/octopus-dependencies/api/v3/index.json
2. Test it - you should see packages
3. Set up Fiddler4, listening on port 8888. 
4. In Octopus Manager, tell Octopus to use that proxy (localhost:8888)
5. Run the test again - this time it will fail:

```
System.NotSupportedException: The ServicePointManager does not support proxies with the https scheme.
   at System.Net.ServicePointManager.FindServicePointHelper(Uri address, Boolean isProxyServicePoint)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)
   at System.Net.HttpWebRequest.FindServicePoint(Boolean forceFind)
   at System.Net.HttpWebRequest.set_InternalProxy(IWebProxy value)
   at System.Net.HttpWebRequest.set_Proxy(IWebProxy value)
   at System.Net.Http.HttpClientHandler.SetDefaultOptions(HttpWebRequest webRequest)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

**Comment by PaulStovell** [comment]
http://help.octopusdeploy.com/discussions/problems/48990-urgent-use-a-custom-proxy-server-dont-work-with-https-feeds

If users enter the proxy manually in the .config file, they can force it to use HTTP. It's just Octopus Manager that trims the scheme, which then defaults to whatever scheme the target URL is using. 

i.e. this works:

```
  <set key="Octopus.Proxy.ProxyHost">http://localhost</set>
```

This doesn't:

![2016-11-18 02_15_28-proxy configuration wizard](https://cloud.githubusercontent.com/assets/47085/20397297/f3061bbc-ad34-11e6-8cbc-039ab97a241d.png)

**Comment by markryd** [comment]
I believe this is un-related to us removing the scheme in the config. Under the covers we force the http scheme anyway since .NET will throw if you try to new up a `WebProxy` with https. This seems to be a problem with how we are holding the Nuget libraries. We set `WebRequest.DefaultWebProxy` but they still go and read out the proxy settings for the current user. The workaround is to go and set the IE Proxy for the user Octopus is running as. I tested this with SYSTEM and it worked.

The fix is to look at how to hand the Nuget libs a proxy correctly, since they ignore `DefaultWebProxy`.

**Comment by michaelnoonan** [comment]
It seems like we are doing the right/common thing by stripping the scheme. From my experience we should only ever be providing the hostname for the proxy server.

This is an example from the Windows 8 proxy configuration dialog:

![](http://g.recordit.co/p1qxWIFaZ7.gif)

**Comment by michaelnoonan** [comment]
At this point it's looking very much like a bug inside NuGet itself where the `ProxyCache` is picking up a proxy where the address of the proxy is actually the source of the package repository!?

![image](https://cloud.githubusercontent.com/assets/1627582/20415260/e4c388fc-ad82-11e6-91af-42b50514ac52.png)

I'm going to keep on hunting.

**Comment by michaelnoonan** [comment]
OK, I think I'm at the bottom of this one. The root cause is because the `ProxyCache` asks two questions but using two different "system proxies":

1. `bool IsSystemProxySet(Uri)` [code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L21) which uses `WebRequest.DefaultWebProxy` - this is the one we configure in Octopus
2. `WebProxy GetSystemProxy(Uri)` [code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L21) which uses `WebRequest.GetSystemWebProxy()` which is cached [privately in a static readonly field](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L21) - we cannot do anything about this one.

The result is that NuGet thinks we need to use a proxy for the Package Source, which is true, but it tries to get the URI to the proxy server using a different route and gets the wrong answer.

From the history of the code it looks like they have deliberately taken this approach to work around several older bugs in the NuGet ecosystem. I think we will need to update our fork of NuGet to provide the hooks we need to configure the `ProxyCache` correctly for our needs.

**Comment by michaelnoonan** [comment]
This may be related to the same code changes: http://help.octopusdeploy.com/discussions/problems/49049-downloading-package-from-external-feed-fails-when-changing-from-http-to-https

**Comment by michaelnoonan** [comment]
Release Note: Fixed a bug preventing external NuGet feeds from working via a proxy server
