### ISSUE TITLE
Hard to remove an environment from a tenant if the lifecycle changes

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2989]
1. Create a project with lifecycle that contains Environment A
1. Add a tenant with that project and Environment A
1. Change the project lifecycle to one without  Environment A
1. Edit the tentant's environments

There will be a blank space in the text box which takes several goes to get rid of. If you don't get rid of it, the tenant can't be saved.

**Comment by droyad** [comment]
![image](https://cloud.githubusercontent.com/assets/1687639/20992149/10495f82-bd2e-11e6-9ff0-665407c9a305.png)

**Comment by droyad** [comment]
Still a problem in 4.0, there is no delete button (`Other`):

![image](https://user-images.githubusercontent.com/1687639/34597260-64b0ac0e-f231-11e7-9769-ce3e08c4f38c.png)

**Comment by NickJosevski** [comment]
It can't just be allow a delete on the missing resource, because we also show the same if they user cannot access the resource because they lack permission.

So this needs to be fixed from the other direction, we need the relationship links between resources, and we need to perform the cascade deletion.

In other parts of the app these "dangling" references can crash UI, so following links for deletes is better all round.

**Comment by NickJosevski** [comment]
Reported here also: https://help.octopus.com/t/your-post-in-unable-to-associate-environment-to-tentant/20190

Closing off a duplicate issue: https://github.com/OctopusDeploy/Issues/issues/4645

**Comment by droyad** [comment]
Reproduced on `2019.4`

**Comment by danielfischeroctopus** [comment]
Related issue.
#5831

**Comment by zentron** [comment]
Closed as dupe
