### ISSUE TITLE
Make updates to community step templates more discoverable

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3040]
Currently if you want to see if a community step template has an update you have to go into the step template to see the little bullhorn that notifies you that there is an update to the step template in the community library.

![image](https://cloud.githubusercontent.com/assets/1035315/21536527/ba0bc166-cdcf-11e6-8830-7d850c06345a.png)

![image](https://cloud.githubusercontent.com/assets/1035315/21536534/d16e61b0-cdcf-11e6-9281-2e43731ebe89.png)

It would be nice if we could make this more discoverable, in a similar way we've done with Tenants and missing variables

![image](https://cloud.githubusercontent.com/assets/1035315/21536504/86fdf226-cdcf-11e6-9da7-6b0e53577ca1.png)

![image](https://cloud.githubusercontent.com/assets/1035315/21536518/a03a4942-cdcf-11e6-9382-fc4ee7b4cd1f.png)

**Comment by zentron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make updates to community step templates more discoverable](https://trello.com/c/MNKTR1x0/23-make-updates-to-community-step-templates-more-discoverable)

**Comment by pawelpabich** [comment]
This is by design. The goal is to not overload users with decisions that they are required to make. A new version of a step template in the community library doesn't require immediate attention. A warning that they can see all the time but don't need to action can cause unhealthy anxiety. 

Existing examples:
- We allow users to be notified only about minor/major versions of Octopus
- Add step page shows that there is an update available to a step template only when the user hovers over it
