### ISSUE TITLE
Azure Container Registry fails with JSON exception when testing the feed

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Issues#3041]
The following exception is returned when trying to search for images in the Azure Container Registry: `'Unexpected character encountered while parsing value: <. Path '', line 1, position 1'`

I have replicated the issue with an Azure Container Registry that I setup as well.

Spoke to @zentron and he was sure he tested this when he initially did the work on this and it worked, so most likely something that has changed in the Azure Container Registry.

Source: http://help.octopusdeploy.com/discussions/problems/50140

**Comment by zentron** [comment]
Appears to currently be fine. I will update docs with steps once docs site is back online. In the meantime:

Given the following repository
![image](https://cloud.githubusercontent.com/assets/1830666/22234914/8af51cf6-e247-11e6-9f59-ea449f84b97e.png)
Then the correct url to provide to Octopus deploy is **https://** octoregistry-on.azurecr.io **/v2**
Note that without **https** the request will redirect to the Azure container services marketing pages, hence the 

> Unexpected character encountered while parsing value: <.

error as outlined in the linked source.

Also note that the **/v2** extension is required since this is used by Octopus Deploy to determine which version of the API is available.

The final point to make is that at this point in time, the Azure Container Registry integration with Octopus Deploy _requires_ using the admin username & password as provided through the Azure portal and direct integration with your Azure service principals is _not_ yet supported.
![image](https://cloud.githubusercontent.com/assets/1830666/22235004/52e3087c-e248-11e6-85ca-0966b50ebdac.png)

**Comment by droyad** [comment]
Has not happened again
