### ISSUE TITLE
Uploading a zip package with a dash as name / version delimiter returns error

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3042]
E.g. `product-1.0.1.zip` fails with the error message `The resource was not found on this server`, as the package will be parsed as packageId `product-1` and version `0.1`.

**Comment by droyad** [comment]
The parsing is correct, we just need to fix the retrieval of it (see #3076 for more info)

**Comment by droyad** [comment]
Report: http://help.octopusdeploy.com/discussions/problems/53874

**Comment by RachelAmbler** [comment]
@droyad I'm on here as well so can keep an eye on the situation (53874 was my ticket if others were wondering).

**Comment by droyad** [comment]
When we create package related URLs, we combine the package `id` with the `version` using a `-`. eg id `MyPackage-1` and version `1.0.0` becomes `MyPackage-1-1.0.0`. When parsing the url, the code can't figure out if the version is `1.0.0` or `1-1.0.0` as they are both valid SemVer2 versions.

The fix is to use `.` to separate the id and version as this is consistent with nuget package naming or split it into two parameters.

**Comment by droyad** [comment]
This has been fixed sometime between `3.13.2` and `3.17.2`.
