### ISSUE TITLE
VSTS feeds do not authenticate

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#3081]
See an example here: https://demo.octopusdeploy.com/app#/library/feeds/feeds-vsts-test-feed/test

Can not add external VSTS NuGet feeds to Octopus. Failing with:
```
Unable to load the service index for source https://damovisa.pkgs.visualstudio.com/_packaging/TestFeed/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
```

See http://help.octopusdeploy.com/discussions/problems/50662

Doesn't appear to be related to #2959, restarting the server does not help.

**Comment by tothegills** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VSTS feeds do not authenticate #3081](https://trello.com/c/0yDeNUya/160-vsts-feeds-do-not-authenticate-3081)

**Comment by tothegills** [comment]
Workaround: Use a v2 feed

**Comment by tothegills** [comment]
Tried v2 and v3 feeds in TFS 2017 and neither worked.  See here: https://secure.helpscout.net/conversation/307809118?folderId=557082

**Comment by CamronBute** [comment]
I am also having this problem.

**Comment by droyad** [comment]
@CamronBute I'm currently looking into this. Are you using a Personal Access Token? If so, is the username blank? If so, put anything in the username field. 

Due to another issue, you will need to restart the server after changing the credentials for a feed.

**Comment by droyad** [comment]
I believe the VSTS issue was due to an expired PAT or a transient problem with VSTS. I tested and was able to authenticate successfully. The only caveat was that a non-blank username is required.

As for TFS, I was not able to authenticate at all with TFS2017 using a PAT, even with `NuGet.exe`. Authentication with the username/password worked however.

Closing this for now in light of those findings. Please contact support if VSTS/PAT authentication or TFS/password authentication does not work for you, and we will investigate further.

**Comment by droyad** [comment]
I believe the VSTS issue was due to an expired PAT or a transient problem with VSTS. I tested and was able to authenticate successfully. The only caveat was that a non-blank username is required.

As for TFS, I was not able to authenticate at all with TFS2017 using a PAT, even with `NuGet.exe`. Authentication with the username/password worked however. So I'm putting that down to a problem with TFS2017.

Closing this for now in light of those findings. Please contact support if VSTS/PAT authentication or TFS/password authentication does not work for you, and we will investigate further.
