### ISSUE TITLE
Default values for sensitive fields on step templates displayed in clear text 

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3090]
When you create a step template with a sensitive parameter with a default value, the value is displayed in clear text as well as transmitted in cleartext via the api and export.

![image](https://cloud.githubusercontent.com/assets/373389/22187180/cdb09432-e155-11e6-96f7-5b67770bc3d3.png)

![image](https://cloud.githubusercontent.com/assets/373389/22187442/6f1a4058-e15a-11e6-8a66-9ff1d51f74b6.png)

Source: http://help.octopusdeploy.com/discussions/questions/10522

---

## options:

* dont allow a default value if the control type is sensitive
* add a warning to the UI saying "dont enter a plaintext value here (but variables are okay)" (but worded better)
* treat it as an encrypted value

## things to consider:

* how do we export step templates that have sensitive values?
* how do we protect the sensitive value in general, permissions around Step Templates are not really strict

**Comment by michaelnoonan** [comment]
I've encountered similar issues with the default value because of the UX. At the moment it is always treated as a plain-text field, and it is displayed prior to the selection of data type.

Consider the example of changing an existing `Plain text` field to a `Drop down list` field. You have to understand that the default value should be changed to become the `Value` part of the list of selectable values, which is defined afterwards. We could do a better job with this UX by putting the default value field after the data type selection so the default value field could be "typed". This way the UI would help you choose the default value from a `<select />`.

Similarly by moving the default value after the data type we could handle the case where it is a sensitive value.

One other thing to keep in mind is when you want a Sensitive value, but want the default to be an expression like `#{MyEnvironmentSpecificDefaultValue}` - in this case I want to see the expression in clear text because the expression itself is not sensitive, but the value(s) of the `MyEnvironmentSpecificDefaultValue` is sensitive.

**Comment by zentron** [comment]
The last comment is why i'd say that if we showed as sensitive on the page, it would need to just be the standard "bindable" sensitive field form type, so the user can click opt to "bind to variable" like other fields to enter in clear text. We can then determine of its variable or sensitive based on the data type of the variable so that it can be correctly shown, or obscured on the details page

**Comment by pawelpabich** [comment]
What should happen during step template export when the default value is encrypted? 
Or in the general case when a step template is retrieved (`api/actionteplate/id`)?

We could remove it but that might confuse users.

**Comment by alfhenrik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sensitive Variables with default value renders as clear text](https://trello.com/c/Lc5Qjf1J/152-sensitive-variables-with-default-value-renders-as-clear-text)

**Comment by zentron** [comment]
Release Note: Sensitive variables in templates do not return their values through the API

**Comment by zentron** [comment]
When the template is used in an actual step, the template default is copied onto the step itself. Note that this value will not be replaced even if the template is updated.
