### ISSUE TITLE
Domain events holding open a transaction

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#3097]
The DomainEvents service is holding open a transaction for the life of the application. This is possibly the result of `tempdb` growth.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Read committed Snapshot](https://trello.com/c/ecUIrCNs/188-read-committed-snapshot)

**Comment by michaelnoonan** [comment]
Release Note: Fixed a bug where a SQL Database transaction was held open for the life of the Octopus Server which was a potential cause for `tempdb` growth

**Comment by michelejohlbs** [comment]
I just emailed support tonight about the same issue we are experiencing. We are on version 3.17.14 and transactions are still kept open in Azure SQL causing TempDB growth.

The SQL I could track that was held open in the transaction was:
(@packageid nvarchar(17))SELECT * FROM dbo.[NuGetPackage] WHERE ([PackageId] = @packageid) ORDER BY [Id]

**Comment by michaelnoonan** [comment]
Hi @michelejohlbs - This looks different to the original issue, so let's dig a bit deeper in a support ticket. On its way as we speak!

**Comment by michaelnoonan** [comment]
This particular issue was caused by the Built In Package Repository Re-indexing process. It was running normally, but over a large number of packages. We may be able to optimise the database transaction usage, but a good workaround is to disable the re-index process since 99% of customers don't need it, but also, 99% of customers don't even notice it!

https://octopus.com/docs/packaging-applications/package-repositories/built-in-repository-reindexing

**Comment by michelejohlbs** [comment]
Thank you for the support on resolving this Michael. 
To confirm, the disabling of the re-index on the package repository did stop the TempDB growth.
