### ISSUE TITLE
Make tenant filtering more obvious

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3117]
We recently had a customer accidentally deploy to more tenants than they expected. We like to follow a principal of least surprise, so it would be nice if we could make the number of tenants matched in a filter more obvious from the outset.

![image](https://cloud.githubusercontent.com/assets/1627582/22451590/8b833576-e7bb-11e6-900b-1feb8a83473b.png)

- [ ] Make the number of matching tenants draw attention (more obvious/needy)
- [ ] Add some basic explanatory text about the combinatory logic applied (see https://github.com/OctopusDeploy/Issues/issues/3117#issuecomment-280401591 below)
- [ ] Add a link to docs to learn more about tenant filters

Source (private link): https://secure.helpscout.net/conversation/307947528?folderId=557082

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make tenants matching filter more obvious](https://trello.com/c/BmhTBOFn/88-make-tenants-matching-filter-more-obvious)

**Comment by fourpastmidnight** [comment]
I was investigating the use of tenants for my organization and was working through your multi-tenant deployment guide. I came across this discrepancy as well. Fortunately, there are no customer-facing impacts since I was only testing, but I found more tenants being matched than I anticipated.

I think what threw me off was that when I specified the Tenants to be matched, and then specified a tenant tag from one of the tenant tag sets, I expected the filter to be an AND criteria, but it turned out to be an OR criteria (i.e. they're unioned).

So the setup is:

* Tenants
    * Tenant 1
    * Tenant 2

* Tenant Tag Sets:
    * Clients
        * Client 1
        * Client 2

In the above, _Tenant 1_ was assigned the tag _Client 1_.

I then selected _Tenant 1_ and _Tenant 2_ and then the tenant tag _Client 1_. In lieu of anything telling me otherwise, I expected that:

> From the selected tenants, only select those tenants who have a tenant tag matching one or more of the selected tenant set tags below".

I suppose I expected this behavior because of other places within Octopus Deploy where "scoping" things restricts the already defined set, instead of adding to it.

Instead, what appears to be happening in this instance is that these "filters" are additive (in fact, then, they aren't really filters at all, but "selectors"):

> If a tenant is _Tenant 1_ or _Tenant 2_ **OR** a tenant has a tenant tag of _Client 1_, then the tenant is a valid deployment target

If the behavior of tenant filtering/selection is kept as it is currently implemented, it would be helpful to add text to the screen, such as:

> **Tenants**
> ------------------------------------------------------------
> **Tenants**:  <select tenants\>  
> 
> Also select tenants who have the following tenant tags:  
>
> **Hosting**: <Select tags from Hosting tenant tag set\>  
> **License Type**: <Select tags from License Type tenant tag set\>  
> ...
> etc.

I'm not entirely sure if the current behavior is the best behavior--I myself am leaning towards that specifying tenant tag set tags should further restrict the list of selected tenants instead of _adding_ to the list of tenants already selected; but I'm far from certain on all the different use cases that one or the other option adds or removes from various deployment scenarios.

Perhaps even, it's worth adding the type of filtering/selection to be performed by specifying tag set tags: should specifying tag set tags select additional tenants, or should specifying tag set tags restrict the set of tenants already selected? So maybe something like:

> **Tenants**
> ------------------------------------------------------------
> **Tenants**: <Select tenants\>
>
> **Selection/Filtering Options**  
> * (x) Restrict the selected tenants above to those tenants who have one or more of the tags selected below
> * (  ) Additionally select tenants who have one or more of the tags specified below
>
> **Hosting**: <Select tags from Hosting tenant tag set\>
> **License Type**: <Select tags from License Type tenant tag set\>
> ...
> etc.

Or perhaps providing a UI to provide some sort of "Tenant mapping Rule" where you can apply one or more rules--to keep the interface a bit cleaner. Rules would be OR'd together, while things within a rule would be ANDed.

**Comment by michaelnoonan** [comment]
Hi @fourpastmidnight - thanks for the constructive feedback!

We did spend a lot of time testing out different scenarios using these filters with different combinational logic, and we landed on the current form based on our own experiments and customer feedback at the time. I've updated the Issue description with your suggestions which work within our current implementation.

On the other points your descriptive and constructive feedback has certainly given me food for thought!

# Selection/Filtering Options

Regarding the options for filtering: I would encourage you to add a suggestion to our UserVoice site with this exact content: https://octopusdeploy.uservoice.com. This way we could measure support for exactly what you are suggesting, and also makes it easier for you to drum up support from your community.

# In the meantime

The best recommendation I have is to leverage the [existing combinatorial rules](https://octopus.com/docs/key-concepts/tenants/tenant-tags#TenantTags-Tag-basedfilters) to achieve your end-goal:

> When filtering tenants, Octopus will combine tags within the same tag set using the OR operator, and combine tag sets using the AND operator.

- Only specify a tenant "by name" (explicitly) if you absolutely want that tenant included in the result
- A filter with tags in the same tag set will be more inclusive
- A filter with tags across different tag sets will become more restrictive

I've updated our documentation in an attempt to help in the meantime! :)

**Comment by fourpastmidnight** [comment]
Thanks for replying. I would've made the suggestion on uservoice, but I'm out if hours already; and you only give people 7 of them!! I need to read the above again to make sure I understood it, but thanks again for replying. Any clearly to documentation and India such as this is always helpful.

**Comment by fourpastmidnight** [comment]
After re-reading the "In the meantime" section, I understand now, how these Tenant Tag Sets are working to "select" the applicable tenants. Thanks for the clarification!

**Comment by michaelnoonan** [comment]
The deploying multiple releases part has been addressed by https://github.com/OctopusDeploy/Issues/issues/3917

**Comment by michaelnoonan** [comment]
I'm shipping a change in Octopus 4.0.7 which takes some strides towards consistency in this area, if not making it easier to understand across the board. We still have work to do on the general UX for picking tenants and helping understand the logic behind the tag queries.

**Comment by michaelnoonan** [comment]
It's been a long time since having this meandering conversation, and we have changed our UX significantly since that time. There may be some ideas which are still valid, though I would like to see these raised as different issues if some of our customers are still concerned about them.
