### ISSUE TITLE
Deployment overview and logs list steps out of order

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#3235]
When viewing the deployment log and deployment overview, the steps appear out of order. However the steps actually do **run in the correct order**. This is an issue with creating the log file groupings from the deployment plan.

## Issue has been resolved
It was introduced in `3.10.0`, a fix will ship in `3.11.5`. See below for more details.

## Reported Cases:

The associated tickets (some are private discussions):
 1. http://help.octopusdeploy.com/discussions/problems/51739
 1. http://help.octopusdeploy.com/discussions/problems/51685-task-summary-order-appearing-different-to-task-log
 1. http://help.octopusdeploy.com/discussions/problems/51804-task-summary-ordering-with-disabled-steps
 1. http://help.octopusdeploy.com/discussions/problems/51858
 1. http://help.octopusdeploy.com/discussions/problems/51846-task-log-layout-not-displaying-expected-output-during-deployment
 1. [ email1 ](https://secure.helpscout.net/conversation/326620914/?folderId=557082)

## More info
There is a bug related to skipping steps that some people were hitting at the same time, that is patched in 3.11.4 ( see: #3233 ) but people are on 3.11.4 now and still experiencing the issue.

Example of it displaying out of order, but running as expected: 

![image](https://cloud.githubusercontent.com/assets/119096/23532640/221f388c-fff8-11e6-9736-237b3c571d28.png)

**Comment by droyad** [comment]
We currently think it has something to do with step names and interaction with another feature (variables, channels, etc). Renaming a step seems to put it back in the right position.

**Comment by droyad** [comment]
The Octopus log files are organised in nested 'blocks' so that the logs can grouped under their relevant process. The log file in question is stored in `<octopushome>\ServerTasks` and the deployment overview, UI log and raw log are generated from that.

`3.10.0` introduced multi-line sensitive variable masking. This is primarily to mask the accidental output of certificates and private keys.

This feature works by holding log messages if the end of the message is a partial match to the start of a sensitive variable. The hold is until the next line is logged, or the block ends. The sensitive value masking then evaluates the two lines against the sensitive variables to see whether masking is applied. It then releases those lines to the log.

Line breaks are ignored as some methods of logging (eg PowerShell) wrap at certain points. So if you step name was `Foo`, the following sensitive variable would cause the log line to be held: `Foo Bar`, `oo Bar`, `FooBar`.

Most of the time this does not cause an issue as the next log line, or the end of the log block occurs quickly.

At the start of the deployment process, we setup the blocks of the steps that are going to run (the "step" block). This is why they appear right away when a deployment starts. This is done by logging a special log message at a level of `PLAN`. It is this log entry that is getting held and causing the above behaviour.

As each step runs, it creates blocks for each action inside it's step block. Nothing is actually logged at the step block level until the finish message and end block. Hence the `PLAN` entry is held until then.

For example, in a really simple scenario, the log file should look like this:
```
10:00:00 INFO Deployment1 Deployment 1 starting
10:00:00 PLAN Deployment1\Step1 Step 1: Foo
10:00:00 PLAN Deployment1\Step1\Action1 Step 1 Action started
10:01:20 INFO Deployment1\Step1\Action1 Output from the task
10:05:00 END  Deployment1\Step1\Action1 Action ended
10:05:00 INFO Deployment1\Step1 Step Finished
10:05:00 END  Deployment1\Step1
10:05:00 INFO Deployment1 Finished deployment
```

However if you had a sensitive variable with a value of `Foo Bar`, the second line would be held and result in
```
10:00:00 INFO Deployment1 Deployment 1 starting
10:00:00 PLAN Deployment1\Step1\Action1 Step 1 Action started
10:01:20 INFO Deployment1\Step1\Action1 Output from the task
10:05:00 END  Deployment1\Step1\Action1 Action ended
10:05:00 PLAN Deployment1\Step1 Step 1: Foo
10:05:00 INFO Deployment1\Step1 Step Finished
10:05:00 END  Deployment1\Step1
10:05:00 INFO Deployment1 Finished deployment
```

Our solution is to release `PLAN` and similar log entries immediately as they would not contain multi-line 
sensitive variables.
