### ISSUE TITLE
Variable run conditions now broken

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3277]
We discovered a bug with variable run conditions in step templates. The changes from #3150 seem to have caused this problem...

The variable substitution syntax examples do not appear to evaluate correctly anymore. These used to work and were tested manually before we deployed this feature. So sometime between when this was released and now, something has changed in Octostache. The test we have in place was not thorough enough to catch this.

Eg. This fails, when it should succeed.
```
#{if Octopus.Environment.Name == "Production"}
```

We have a test that proves this is broken on this branch: https://github.com/OctopusDeploy/OctopusDeploy/tree/bug-variableRunConditions

See the test file: source/Octopus.E2ETests.API/Scripts/VariableRunConditionsTestScript.cs

This is marked as priority, because we marketed this feature on our blog, showing variable run conditions like the above example, so if people have set these up in their deployment plans, they will suddenly stop working.

**Comment by markryd** [comment]
`#{if Octopus.Environment.Name == "Production"}` isn't a valid Octostache expression and never has been. The blog post doesn't mention an expression like that https://octopus.com/blog/deployment-process-uservoice-update.

`#{if Octopus.Environment.Name == "Production"}` should evaluate to itself (ie `#{if Octopus.Environment.Name == "Production"}`) which will be true, since it isn't 0, false or empty.

**Comment by droyad** [comment]
To be clean, the syntax should be `#{if Octopus.Environment.Name == "Production"}true{/if}`

**Comment by slewis74** [comment]
Does the Conditional section on https://octopus.com/docs/reference/variable-substitution-syntax need updating then?

**Comment by markryd** [comment]
Docs have been clarified.
