### ISSUE TITLE
More flexible options for action conditions based on the tenant for the deployment

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3337]
The main pain-point this resolves is a decision we made around whether an action will run for a particular deployment based on the `Deployment.TenantId` which can either be a Tenant, or `null` (for an untenanted deployment). In this case the customer wanted to run a step for untenanted deployments, and any tenanted deployments where the tenant matched a certain filter.

As of Octopus 3.4, if you add a tenant filter to an action we automatically exclude that step for any untenanted deployments.

A picture is worth a few extra words:

![image](https://cloud.githubusercontent.com/assets/1627582/24279913/80889c50-1098-11e7-8b2d-2faa53a9ccd1.png)

Source: http://help.octopusdeploy.com/discussions/questions/11037

**Comment by pawelpabich** [comment]
Variable Based Run Condition feels like the right tool for the job here. In this way we can keep the UI simple. What do you think @michaelnoonan ?

**Comment by TomPeters** [comment]
There are many combinations of things that people want to base the run conditions off: environments, tenants, machines, roles and channels all come to mind. Instead of implementing this feature (which may end up being very complex in order to cover all possible types of scopes), we think it will be better to rely on the existing framework we have for varying your deployment across different scopes: Variables.

Specifically we think that Variable based run conditions can solve this problem in a simpler way. Some enhancements to Variable based run conditions may be required to cover all use cases (eg see https://github.com/OctopusDeploy/Issues/issues/3206).
