### ISSUE TITLE
Auto-deploy from failed deployments

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#3358]
Auto-deploy needs to be able to recover from scenarios where one machine stops a previously-successful deployment from running.

## Steps to reproduce
If you have auto-deploy setup and one machine fails the deployment (not because the machine went offline, but maybe a configuration drift on that machine was an issue for the deployment), there's currently no way for auto-deploy to continue (short of subscribing to a `DeploymentFailed` event with subscriptions and writing your own custom webhook to help you recover).

## Potential solution
We're proposing we modify auto-deploy's logic to be able to query deployments that have "previously" successfully deployed (but are currently not in a successful state), and also having a cap on the number of times we attempt an auto-deploy in these situations. Project triggers will include a "Retry cap" field that users can set, so that they can configure how many times auto-deploy will retry before completely stopping.

To facilitate this, we want to add a "HasDeployedOnce" property to the deployment object, which we'll use as a one-time flag to indicate to auto-deploy that "this deployment has succeeded once before and can be retried, even if the current state of the deployment is failed" ... along with a "NumberOfTimesRequeued" property on the deployment object, which with a "RetryCap" property on the project trigger will help us know how many times auto-deploy can keep re-trying.

Source: http://help.octopusdeploy.com/discussions/problems/53010
Another: http://help.octopusdeploy.com/discussions/problems/54674

**Comment by sebandres** [comment]
Is there any progress on this thread? 
We are having the same issue and is very annoying when new machines that trigger the deployment get ignored due to some transient error on a server from the same release on a different transient server.

**Comment by sebandres** [comment]
@KennethBates Would you know if this is being acted on? We are seeing the same behavior where a new node fails to install for whatever reason and because of this all subsequent new nodes never trigger a deployment (deployment blocked) even though the initial deployment for version X was successful.

I noticed you responded to a support ticket on this same topic back in March referencing this gh issue.

Thanks!

**Comment by sebandres** [comment]
@NickJosevski Any chance on bumping this up the queue? We've even tried setting the [Auto Deploy Override](https://octopus.com/docs/api-and-integration/octo.exe-command-line/creating-auto-deploy-overrides) but it seems overrides only works if the last release is successful (which defeats the concept of an override!)

**Comment by NickJosevski** [comment]
Hi @sebandres. Sorry we don't have a solid time frame for when it'll be improved.

I brought it to the attention of the team who are working in that area, they'll see what they can do about getting to it sooner rather than later.

**Comment by sebandres** [comment]
Cool, thanks @NickJosevski !

**Comment by tothegills** [comment]
I think there are a couple problems we need to address:

- A deployment to many machines where one machine fails will stop the deployment, leaving the other machines with an incomplete deployment
- Auto deployments will not trigger when the previous deployment failed

Transient connectivity issues or a machine going offline during a deployment can be mitigated by the "Skip machines if they become unavailable" setting in the deployment process but we don't have a good answer for continuing the deployment when a real failure happens, resulting from something like a dependency missing.  We could extend our existing functionality to capture all failures and remove failed machines from the deployment with a warning. Would that be a good solution?
![image](https://user-images.githubusercontent.com/171197/30142699-9764d6c2-93c5-11e7-95bd-8e4aad7f9b12.png)

The deployment would then be successful and continue to fire for subsequent auto-deploys.

Is there a scenario where that would not be a good solution?  For example a group of machines come online, trigger an auto-deploy and one fails.  Is there a case for failing that deployment but continuing to auto-deploy to future machines?

**Comment by jfisher84** [comment]
Some good thinking going on here @tothegills! The elastic nature of the cloud and scaling out really does present some interesting challenges around machine / network availability.

I like the idea of having the option to continue deploying if a machine is offline. But it would have to come with a few caveats. 1 machine out of a group of machines (for a role) could ok to ignore if:
* There are other machines in that group / role that can serve up the application.
* The machine that is offline is marked as being 'out-of-date' if it does come back online - **i.e.** we know that a deploy has occurred since it was unavailable, and we can trigger an action to remove it from a load balancer, octopus deploy group, or choose to deploy the latest code for it's group / role if it re-appears.
* If there is a general network outage - we would not want these choices to allow for an entire group of applications servers to be deleted / removed or stopped in serving traffic.  Which is why I think the rule of having at least x number or percentage of a role / group having successful deployments a base requirement.

**Comment by tothegills** [comment]
Thanks for the feedback @jfisher84.  What would you want Octopus to do if the caveats were not satisfied?

**Comment by sebandres** [comment]
@tothegills @jfisher84 

We tend to have a more discreet idea of a green/red outcome from a deploy.

For us the story goes like this:

1. Version 1.0 is ready we try to deploy to available targets and they all succeed, then 1.0 is the new 'good' version.
2. Version 1.1 is ready we try to deploy to available targets, some of the targets fail so we consider the deployment to be a failure, apply rollback actions, version 1.0 is still the 'good' version.
3. If a new target comes online at this point (new target or offline that became online) it should always get the 'good' version, in this case 1.0.
4. Version 1.1.1 is ready we try to deploy to available targets and they all succeed, then 1.1.1 is the new 'good' version.
5. If a new target comes online at this point (new target or offline that became online) it should always get the 'good' version, in this case 1.1.1.
6. And so on...

Let's also keep in mind that if you schedule a release it will also block any 'auto-triggers' until the release happens. For us the ideal behavior is that the new target gets the 'good' version until the scheduled release happens AND is successful to any targets it intended to release to and by doing so updates the new 'good' version.

**Comment by tothegills** [comment]
@sebandres Is the first deployment (the scheduled one) the only deployment that matters when considering a release the "good" one?  If an auto-deploy of that version failed would you still want that version to be deployed in subsequent auto-deploys?

I will definitely fix scheduled deployments blocking auto triggers.

**Comment by sebandres** [comment]
The first time a new version releases is the one determining the 'good' one to us given that we run health checks on top of that. Auto-triggered releases that fail shouldn't impact what we consider a good version given that it is in fact just a 're-release' of an already established/healthy version.

**Comment by tothegills** [comment]
Hi everyone,

For your feedback:
Instead of selecting the latest deployment and checking if it is successful, we will find the most recent successful deployment in the environment and use it for auto deploying.

- If a deployment of 1.0 is successful and a subsequent deployment of 1.0 fails (either via auto deploy or a manual deployment) we will continue to deploy 1.0 to machines that trigger auto deploy.
- If a deployment of 1.0 is successful and subsequent deployments of 1.1 and 1.2 fail, we will continue to deploy 1.0 to machines that trigger auto deploy.
- If a deployment of 1.0 is successful and there is a pending deployment of 1.1, we will continue to deploy 1.0 to machines that trigger auto deploy.

I think this should also mean that the dashboard will be updated after an auto deploy triggers to reflect the version that has been auto deployed.  For example: 1.0 is successful but 1.1 fails.  The dashboard will show 1.1 as the "current" and 1.0 as the "previous" deployments for the environment.  After an auto-deploy of 1.0 takes place, 1.0 will once again show as the "current" deployment for the environment.

Would this satisfy your requirements?

I have a question about rolling back.  If the deployment of 1.0 is successful but the deployment of 1.1 fails, how do you roll back the machines that were involved in the 1.1 deployment?

**Comment by sebandres** [comment]
Sounds spot on @tothegills.

I'm not sure about the dashboard bit, and it might be wording getting in the middle here.

If 1.1 fails we update current to 1.1 but after an auto-deploy we update again with 1.0. What is the purpose of updating 'current' version for a failed deploy? If current is meant to indicate what was the last version attempted to deploy regardless of outcome it feels correct, if current is the last 'good' version then updating it after a failed deploy does not seem to align.

I would be intrigued in the first case as to how we would handle concurrency on the updating the current version as auto-trigger is an async action and might pop up in the middle of the new version's deployment.

Treating failed deployments would depend on each pipeline correct? Some people might decide to destroy any targets that failed deployment, or trigger a deploy of the 'good' version on them. And probably in many other different ways. Or were you asking about something else?

Regards,

Seb.

**Comment by wilson85** [comment]
@tothegills that sounds good.  But, if there is an auto deploy override, could it use the override regardless of what state the deployment was?

**Comment by jfisher84** [comment]
* Yes - Auto-Deploys should always work if the initial release deploy was a success
* Yes - If the first release deployment fails, Auto-Deploy should refer to previous successful deploy.

Rollback condition -  Little bit murky around this with elastic environments. I'd say yes to having a feature to rollback:
* Rollback should not occur on a failed Auto-Deploy. Only a new release failed deployment where a successful release has occurred on the target previously

However; We've got some thinking to do around how we manage cloud environments. Servers join a load balancer when we deem it healthy. Which has a lot to do with Octopus Deployments. Need to be careful around how we determine health and the possible outcomes of failure around Autoscaling events.

**Comment by tothegills** [comment]
Regarding overrides (@wilson85):  Our original intent with overrides was to enable things like phoenix environments.  Your infrastructure could be provisioning, you make a new release of a project and set an override so that when your infrastructure arrives it will receive the new release instead of the "current" deployment to that environment. After the first deployment of the new release the override is removed because that deployment is now "current" and will be auto deployed.

These days you can deploy to an empty environment, which accomplishes the same thing. We could consider re-purposing overrides so that the release specified in the override is always the release that gets auto-deployed, no matter if the deployment fails.  Should the override be removed when a different release has a successful deployment to the environment or persist until it is manually deleted?  Is there actually a use case for this kind of override behaviour if we change auto-deploy to always deploy the most recent successful deployment?

Regarding rollbacks (@sebandres, @jfisher84): Is there something we can do to help with rollbacks? If you are destroying targets, redeploying the good release or removing a server from a loadbalancer you might benefit from triggering a deployment when another deployment fails.  The triggered deployment may need to run across the same machines as the failed deployment. I'm trying to gauge if something like this would be helpful or if you already have systems in place for rollbacks.


One thing I'm not really clear on:  When a scale up event happens and you have a group of machines that arrive all at once triggering an auto-deploy.  If one of those machines fails for whatever reason it will stop the deployment, causing the other machines to also fail (they could have a partial deployment or no deployment at all). Do we need a mechanism where one bad machine will not spoil the others?

**Comment by sebandres** [comment]
> Regarding overrides (@wilson85): Our original intent with overrides was to enable things like phoenix environments. Your infrastructure could be provisioning, you make a new release of a project and set an override so that when your infrastructure arrives it will receive the new release instead of the "current" deployment to that environment. After the first deployment of the new release the override is removed because that deployment is now "current" and will be auto deployed.

I'm going too much into solution mode here but it feels we can have multiple behaviors people would benefit from when using auto-trigger overrides and a new deploy happens (Do Nothing, Remove Override, update override with new 'current' version, etc) perhaps the best approach is to surface these different behaviors and let the user choose how they want to use it on a 'Project Setting' or something like this?

> Regarding rollbacks (@sebandres, @jfisher84): Is there something we can do to help with rollbacks? If you are destroying targets, redeploying the good release or removing a server from a loadbalancer you might benefit from triggering a deployment when another deployment fails. The triggered deployment may need to run across the same machines as the failed deployment. I'm trying to gauge if something like this would be helpful or if you already have systems in place for rollbacks.

My view on it by feels like we might be over engineering the solution here if looking at the initial pain we are trying to solve. Smaller surface of change might get you more feedback into how the new changes are used and then see if there is a need to keep extending/mutating the behavior is the approach we like to use.

> One thing I'm not really clear on: When a scale up event happens and you have a group of machines that arrive all at once triggering an auto-deploy. If one of those machines fails for whatever reason it will stop the deployment, causing the other machines to also fail (they could have a partial deployment or no deployment at all). Do we need a mechanism where one bad machine will not spoil the others?

Similar to my first point, feels like you won't be able to come up with a single answer that will cater for all users so why not just surface that choice and let the user decide?

**Comment by jfisher84** [comment]
@tothegills - Yea hard to say if there's one 'right way' of rolling back. As it can depend on the type of failure, and what type of deployment it is. Something we'll get better at judging with more experience I think. For now it might be good to have a couple options and level of granularity i.e. based on deployment type, environment or roles. Not 100% sure.

**Comment by tothegills** [comment]
Release note: Auto deploy now always re-deploys the most recent successful deployment

**Comment by sebandres** [comment]
Nice!
