### ISSUE TITLE
Disabling the ARC package step causes errors

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3383]
# Steps to reproduce

1. Create a new project
2. Add a package step
3. Configure ARC to use that package step
4. Disable the package step
5. Try to change one of the Project Settings, like its name or the multi-tenant deployment mode
6. You will see an error like this: `The package step provided could not be found in the project's deployment process`

This same behaviour could also happen if the ARC step could be deleted from the deployment process.

# Workaround

​In the meantime you can work around this bug by either:

​1. Disabling ARC if you are not using it, or if the step has been deleted (this should have been prevented by our validation)
​2. Re-enabling the disabled step - if that's actually what you want
​3. Changing ARC to trigger off another package step which is actually enabled
​

**Comment by johnsimons** [comment]
This seems to be fixed in v4.

In v4 when attempting to disable or delete the step that is configure as ARC, you end-up with an error on the screen:
![image](https://user-images.githubusercontent.com/122651/34973642-91118308-fad4-11e7-96b8-719332f552df.png)
![image](https://user-images.githubusercontent.com/122651/34973682-bd63da78-fad4-11e7-8aca-67c5e4aa538f.png)
