### ISSUE TITLE
Properly escape values in IIS deployments

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#3411]
A customer accidentally added a `"` to their IIS Website Name field and the deployment broke.
We should escape these characters to stop deployments from failing.

Source: http://help.octopusdeploy.com/discussions/problems/53521

**Comment by NickJosevski** [comment]
IIS User Interface doesn't allow these characters, I think we should just stop you using them instead of trying to escape them, in the same way how we show an error when the site name is empty

![image](https://cloud.githubusercontent.com/assets/119096/25130938/58294b9e-2487-11e7-8d31-eae1a2da0db6.png)


![image](https://cloud.githubusercontent.com/assets/119096/25131028/a472f446-2487-11e7-9cb8-294b994249ff.png)

**Comment by NickJosevski** [comment]
Release Notes: Improved and more validation around IIS deployment step variables
