### ISSUE TITLE
Octopus.Server.exe configure --maxConcurrentTasks is misleading in 3.x

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3556]
This setting is stored in the per-node config file, and sets what ends up being interpreted as a "cluster-wide task cap" to answer the question: Are there too many tasks running across the entire cluster. The problem is this is set per-node: so each node in the cluster could have a different interpretation of this question.

# Proposal

This proposal comes in two parts:

1. Get rid of the concept of a cluster-wide throttle, and just let it become the “sum of `Node.TaskCap` across the cluster”. eg; If each node in a 4-node cluster has a Task Cap of 5, the resulting cluster-task-cap would be 4 x 5 = 20.
1. Make the `Octopus.Server.exe configure --maxConcurrentTasks`change to set that specific node's task cap. Perhaps we should deprecate this command and replace it with a more appropriately named argument like `--taskCap`?

# Source

This proposal was source from the discussion in this support ticket:
http://help.octopusdeploy.com/discussions/problems/55053

**Comment by michaelnoonan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Octopus.Server.exe configure --maxConcurrentTasks is misleading in 3.x](https://trello.com/c/Y5v4hxpv/497-octopusserverexe-configure-maxconcurrenttasks-is-misleading-in-3x)

**Comment by MichaelJCompton** [comment]
happening as part of https://github.com/OctopusDeploy/Issues/issues/4168

**Comment by MichaelJCompton** [comment]
Update: We are proposing to remove the cluster-wide throttle and replace with just per node caps (as per 1 above).  For point 2 above, the `macConcurrentTasks` option to configure will be removed - the per node task caps can be set through the UI and API.

**Comment by matt-richardson** [comment]
Please consider leaving the `MaxConcurrentTasks` but make it spit out a deprecated message. The api is part of our public api - the [DSC project](https://github.com/OctopusDeploy/OctopusDSC) has lots of if/else conditions as the command line has changed lots 😢. `MaxConcurrentTasks` is not implemented by DSC, so we are not broken, but its very conceivable to think that someone has scripted something to use it.

Also, from a DSC point of view, it's vastly easier for us to use the command line to set options like this, rather than the API. That said, this is only a present limitation as we need to rewrite to use the api more. However, a rewrite is low on the priority list, so there's no sign of that happening anytime soon.

**Comment by MichaelJCompton** [comment]
Release Note: High Availability "MaxConcurrentTasks" is now the sum of the node's task caps.

**Comment by MichaelJCompton** [comment]
As of 2018.2.6, `MaxConcurrentTasks` is deprecated, but not removed - setting it has no effect.
