### ISSUE TITLE
Machine missed during auto deployment

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#3717]
The stored procedure `[dbo].[EventSourceDeployments]` that is used to find machines that were blocked during an already running deployment uses the dates of the last `DeploymentStarted`  and `DeploymentSucceeded` so there is a possibility that a machine could be missed.

The auto-deploy code was refactored to use an `AutoID` property as working with dates in an HA environment would be troublesome, we should investigate if we can make this stored procedure work with `AutoID`s as well.

Source: https://secure.helpscout.net/conversation/400528456/17320/

**Comment by thebigmoosey** [comment]
Brain dumping this here, because this was _possibly_ due to the trigger being setup with the "Machine created" event, instead of using the event group "Machine becomes available for deployment" (which only provides valid machine events once they've gone through a health check).

We should probably have some warnings in the triggers UI around people manually selecting this "Machine created" event to explain the implications. ie. A machine that has been created/added to the DB has not yet gone through a health check, so it may cause confusion when you're using triggers.

>>>

So if we map out the logic of auto-deploy's scheduler:

- AutoDeploy schedule runs @ 0:00:00 (finds nothing to do)
- Machine1 comes online
- User manually runs the first deployment
- DeploymentStarted event occurs
- DeploymentSucceeded event occurs (has deployed to Machine1)
- AutoDeploy schedule runs @ 0:00:30
- AutoDeploy queries machinesSinceLastPass, finds nothing to do
- AutoDeploy queries missingDeploymentMachines, asks SP:EventSourceDeployments for all events between its last pass time (0:00:00) and its current pass time (0:00:30) that are of type `DeploymentSucceeded`, finds Machine1, but realises its already deployed to this machine, so nothing to do
- Machine2 comes online
- Machine3 comes online
- AutoDeploy schedule runs @ 0:01:00
- AutoDeploy queries machinesSinceLastPass, and finds Machine2 and Machine3
- AutoDeploy queries missingDeploymentMachines, asks SP:EventSourceDeployments for all events between its last pass time (0:00:30) and its current pass time (0:01:00) that are of type `DeploymentSucceeded`, finds nothing to do
- Machine4 comes online seconds/milliseconds later
- AutoDeploy issues a command to create and start the deployment with Machine2 and Machine3
- DeploymentStarted event occurs (and lets say this is a long-running deployment)
- AutoDeploy schedule runs @ 0:01:30
- AutoDeploy queries machinesSinceLastPass, and finds Machine4
- AutoDeploy queries missingDeploymentMachines, asks SP:EventSourceDeployments for all events between its last pass time (0:01:00) and its current pass time (0:01:30) that are of type `DeploymentSucceeded`, finds nothing to do
- AutoDeploy issues a command to create and start the deployment with Machine4, but the deployment is currently executing, so this machine is blocked
- AutoDeploy then creates a AutoDeployTriggerBlocked event, so we can consider it for processing on the next pass
- [At this point, the AutoDeploy scheduler can keep ticking over, and we'll keep adding a new AutoDeployTriggerBlocked event for as long as that deployment is executing]
- DeploymentSucceeded event finally occurs (has deployed to Machine2 and Machine3)
- AutoDeploy schedule runs @ 0:02:00
- AutoDeploy queries machinesSinceLastPass, and finds nothing (no new machines have come online or become health since the last pass)
- AutoDeploy queries missingDeploymentMachines, asks SP:EventSourceDeployments for all events between its last pass time (0:01:30) and its current pass time (0:02:00) that are of type `DeploymentSucceeded`, finds our deployment that succeeded. That SP returns the AutoId of when that DeploymentStarted and when it DeploymentSucceeded and looks for machine-related events, finds Machine4 (because we have a Blocked event related to that machine)
- AutoDeploy issues a command to create and start the deployment with Machine4

So our date logic should work in this case because we're asking for all events between when it [last passed] and [now], leaving no gaps in the timeline because that is a date stored against the server's `Configuration` table. Even if you turned off your server and turned it back on again, auto-deploy's scheduler will know when it last passed and will find all DeploymentSucceeded events between that time.

**Comment by tothegills** [comment]
Release note: Improved auto-deploy machine evaluation to prevent machines being missed due to timing issues
