### ISSUE TITLE
Duplicate Variable warning incorrectly describes variable priority

### ISSUE THREAD

**Issue by alexrolleyoctopus** [OctopusDeploy/Issues#3814]
The wording in the duplicate variable warning currently states the following:
```
You have a duplicate variable 'testingVariable' between the Step Template used in the 'Script.Step' step and your Project or Variable Sets in use. Be aware that the latter will prevail over the values entered on the step.
To log this warning as verbose instead, add the 'OctopusSuppressDuplicateVariableWarning' variable to your project with a value of 'true'.
```

The following line is incorrect: `Be aware that the latter will prevail over the values entered on the step.`. When tested (and in our [documentation](https://octopus.com/docs/deploying-applications/variables/scoping-variables#Scopingvariables-Scopespecificity)) it is the value of the variable that is in the Project that will prevail, _not_ the value that is in the Variable Set.

**Comment by EvilTony** [comment]
Running into this problem on my deployments as well. We have one step that runs as rolling but it says it is conflicting with max parallelism.

**Comment by EvilTony** [comment]
Clarification, the warning showed up and it was confusing because the step was overriding the parent but the warning said otherwise. We just flipped this on to remove the confusion to our users: OctopusSuppressDuplicateVariableWarning

**Comment by droyad** [comment]
The message is actually correct. The value of the variable from the project variables will actually prevail. This is due to `User` variables having higher priority (only `Private` variables trump them).

The linked documentation is only relevant to `User` variables.

In other words, the values entered at the step, any step, are exposed as variables scoped to `Action` only. The user variables are scoped to whatever the user entered as the scope, plus `User`. See how it is calculated [here](https://octopus.com/blog/variable-specificity-and-complexity) (also linked from the above doco)

**Comment by droyad** [comment]
Release Note: Clarified the duplicate variable message to emphasise a user variable is overwriting a step field
