### ISSUE TITLE
Filtering audit to Tenant document type shows machine events

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3904]
Tested in OD 3.17.12 and 4.0

When filtering the audit log to `Document Type: Tenant`, the results shown include machine events associated with a tenant. There's also a `Document Type: Machine` filter option which should be what you need to select to see such events. The Tenant filter should only show events regarding the tenant itself.

Screenshot when tested in v4.0:

![tenant_filter_machine_event](https://user-images.githubusercontent.com/20388190/32421049-c8e1b154-c2df-11e7-9216-a49a43ad0b83.png)

Source: https://help.octopusdeploy.com/discussions/problems/62258

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filtering audit to Tenant document type shows machine events](https://trello.com/c/WgGGOknO/851-filtering-audit-to-tenant-document-type-shows-machine-events)

**Comment by Flamage82** [comment]
I can't see a way of achieving this in a simple manner.  We need to record the tenant as a related document in the machine updated event so that filtering by that tenant in the Audit log returns the machine events.  There isn't a property on the event which would allow us to determine which type of document was actually modified and which types we just want to be able to filter on.

In the interests of being thorough, we could theoretically search through the Message or JSON fields to identify that a machine record was modified.  However, this is incredibly brittle, and won't work as a generic solution for other document types.
