### ISSUE TITLE
Guided Failure UI Improvement.

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#3907]
The comment that started this discussion:

> ... two or three users ...[say]... they didn't think they had permission to respond to Guided Failure Mode due to not seeing the 'assign to me' button; might be nice to make that a bit more obvious in 4.0

## UI v3 and v4
![image](https://user-images.githubusercontent.com/119096/32469217-5bfe6c94-c39d-11e7-9fdc-b309b179693a.png)

## Concerns
 - [User] still needs to know to assign the task to themselves
 - It seems like it's not the obviousness of the "ASSIGN TO ME" button in the UI, but more the idea that that's the thing that should be *clicked first*.
 - [The User is] expecting a setup where [they'd] click `Proceed/Fail/Retry/Ignore/Abort`, and it would be _implicitly assigned_ to whoever clicked the button.

**Comment by jess-ross** [comment]
To help address these concerns we could apply the following styles and layout:

1. we have the most important bit of information at the end of the sentence and repeated text at the start. It’s best to have the action/reason at the start of the sentence. My suggestion is to just have ‘Failure guidance required’ and not worry about the task name as it already appears multiple times on the page so it should be clear that this alert relates to this task. 

2. Can make the assigned person name bold rather than italic, as this will stand out more and draw the attention to the fact the user needs to assign it to someone else other than ‘No one’. A capital at the start of No one and You would be nice :)

3. Making the 'Assign to me' button a primary action button will definitely help draw attention to it.

4. ‘Log’ and Show details’ can be ternary buttons

5. Changing the layout will help it read better too.

<img width="1174" alt="screen shot 2017-11-08 at 10 19 32 am" src="https://user-images.githubusercontent.com/17240784/32525762-bdc8ee8e-c471-11e7-992a-ace4e8ae6e99.png">

6. When the 'Assign to me' is clicked, the Notes multiline field is looking really light on the orange background. So it could have a white background. The question can be bolded to and the buttons aligned right for consistency.

<img width="847" alt="screen shot 2017-11-08 at 10 50 55 am" src="https://user-images.githubusercontent.com/17240784/32526008-e6863a88-c472-11e7-8a5e-ba5361e0b97b.png">

**Comment by NickJosevski** [comment]
1/5. The title is generated in 1 location server side, and used everywhere, so it's clear on the Task screen as an example, or in other summary areas, so that's a big change / more risk.

![image](https://user-images.githubusercontent.com/119096/32820595-f873409e-ca1a-11e7-8939-e345ec8729b1.png)

![image](https://user-images.githubusercontent.com/119096/32820608-0747234c-ca1b-11e7-92fb-d667cc94132a.png)

so I think it should stay as a title area that way when it's long and small screen it looks like this:

![image](https://user-images.githubusercontent.com/119096/32821246-1c885638-ca1e-11e7-970f-86d90f988a59.png)

3. ☑️ 
4. ☑️ 
6. ☑️

**Comment by jess-ross** [comment]
Changes look good :)

**Comment by NickJosevski** [comment]
Release Note: Improvements to guided failure and manual intervention experience
