### ISSUE TITLE
Variable editor scrolling experience could be better

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#3946]
As you scroll in the variable editor, new rows don't appear straight away, but appear after a short delay. This is because we need to re-render them as you scroll.

Usually with virtual scrolling, you handle this by rendering new rows off-screen with visibility: hidden, and simple toggle the visibility class when they come on screen.

This doesn't work well in the variable editor because of the Scope column which has chips. They need to be measured to work out how many you can show, and this can only happen after the row is visible.

It would be nice if we could find a way of doing the measurement while they row is still hidden so that we can instantly show rows as they scroll into view.

Some sources:
https://secure.helpscout.net/conversation/472234374?folderId=909879

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable editor scrolling experience could be better](https://trello.com/c/7pRXqcLZ/528-variable-editor-scrolling-experience-could-be-better)

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable editor scrolling experience could be better](https://trello.com/c/Ft0zx0bj/843-variable-editor-scrolling-experience-could-be-better)

**Comment by CalebTodd** [comment]
Definitely a 👍  on this one. I do a lot of work with variables and this makes me want to downgrade. I used to just find my variable in the page and now I have to use the extra filter which is significantly slower.

**Comment by tommy-rot** [comment]
This is probably the most annoying issue I experience atm.  Please bump the priority on this one!

**Comment by TomPeters** [comment]
We've made progress towards fixing this issue in our recent 4.1.9 release of Octopus Deploy. If this has been an annoyance for you, I would encourage you to upgrade.

While scrolling performance is much better in all browsers, I have not yet resolved this issue because we are not yet satisfied with the performance in IE11 and Edge.

**Comment by pawelpabich** [comment]
Submitted a bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15519971/

**Comment by TomPeters** [comment]
We think that the scrolling performance has improved in all browsers since this issue was originally raised. We have not heard any reports about this being an issue for some times so we will close this issue.

If you are still experiencing scrolling performance problems, please reach out to [Octopus support](https://octopus.com/support).
