### ISSUE TITLE
Deploy button shows `Deploy to [env]` even the tenant is not connected to that environment

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#3995]
## Issue
Lifecycle DEV->TEST->PROD, a tenant connected to a tenanted only project and environments DEV and TEST but not PROD, after deploying to DEV and TEST, the `Deploy to PROD` button shows

## Steps to replicate
- Create a tenanted only project
- Connect a tenant to DEV and TEST environments
- Deploy a release to DEV and TEST

In the task or release page, you will now see `Deploy to PROD` button as screenshot below which it shouldn't, thought that the deployment page will not let user to deploy, but it is not appropriate to show
![image](https://user-images.githubusercontent.com/3387099/33356998-7f5f74f6-d50b-11e7-840b-54d4834c9fde.png)

**Comment by TomPeters** [comment]
The `Deploy to...` button shown on the Task page only pre-populates the environment for the deployment. In the example above, it is valid to show `Deploy to Production` because the production part of the lifecycle is now available (for any applicable tenant) because we have deployed to Test. 

This button does not pass through the Tenant associated with the current deployment task to the next page (the create deployment page).
