### ISSUE TITLE
UserView permission should grant ability to fetch user

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#4355]
Calling `GET /api/users/{id}` currently requires `UserEdit` permission, and if the user being retrieved is an administrator it also requires `AdministerSystem`.

This is causing problems when an intervention is assigned to an administrator and a non-administrator attempts to view the intervention.  

It also violates the principle of least surprise.

We will make  `GET /api/users/{id}` require only the `UserView` permission.

Reported by: https://octopususergroup.slack.com/archives/C6UEBB7R9/p1520311577000021 (link to Octopus Community Slack)

**Comment by jimh-datacom** [comment]
Any update on this? It's causing issue for our chain deployment setup.

**Comment by NickJosevski** [comment]
This by design. We reviewed and further hardened access around users in 2018.4.9, a related issue is: https://github.com/OctopusDeploy/Issues/issues/4486

Reason:
The result from `GET /api/users/{id}` has been classified as sensitive enough to warrant the need for the `UserEdit`. The user data returned contains information about purpose of API keys (not the keys), and external authentication providers.

It may not be intuitive when applying *View permissions to GET actions, but there are exceptions such as this.

**Comment by NickJosevski** [comment]
@jimh-datacom if you would like to discuss your specific objective drop us a line on support: https://octopus.com/support

You will be able to get a listing of all users via the `/api/users/all` without needing UserEdit permission.
