### ISSUE TITLE
Investigate a sort by date option for package selection

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#4425]
For customers using feature branch and more complex versioning, the option to sort by date may be more useful that sort by version. We should investigate this, run up some feature branch versions and decide whether this is a good idea.

This may be complicated between the built-in package repository and external package feeds, so that is something we'll need to consider.

Source: https://help.octopus.com/t/order-packages-by-date/19315

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate a sort by date option for package selection](https://trello.com/c/mAMm5e6N/56-investigate-a-sort-by-date-option-for-package-selection)

**Comment by zentron** [comment]
Closing ticket as it  there are some underlying complexities that would come from this feature due to the different APIs of the various feeds.

With the correct versioning strategy the latest build _should typically_ be resolvable via the version number. Channels allow you to configure your versioning strategy for a release based on pre-release tags or version components. This allows you ensure that although the latest build might not be the highest version for that app ever pushed, it still shows up as the latest version when the applicable rule is applied.

Feel free to comment on this ticket if you feel this conclusion is insufficient for your needs
