### ISSUE TITLE
`/all` endpoints can break the SQL parameter limit

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4442]
When ids are provided to the `/all` endpoint, for example `/machines/all?ids=....`, the resulting query can exceed the SQL parameter limit causing:

>SQL Error 8003 - The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

When ids are specified we should load in batches using `BatchWithBlockSize`.

See https://help.octopus.com/t/sql-query-error-when-viewing-a-variable-set-or-script-module/19470

**Comment by tothegills** [comment]
This comes up again and again, I think we should implement the fix in Nevermore.

**Comment by mikeclayton** [comment]
Instead of batching long "WHERE IN" lists into multiple queries you could use "Table-Valued Parameters" in SQL Server from 2008 upwards - you can avoid the 2100 parameter limit that way. You basically pass a DataTable containing your lookup values as a named parameter in your command and then use it in your query as you would any other server-side database table. 

See https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters for more info.

I've tried this locally on SQL Express and performed a "WHERE IN" query with 5000 rows:

    // build a DataTable containing all the WHERE IN ids
    var objectIds = new DataTable();
    objectIds.Columns.Add("ObjectId", typeof(int));
    for( var id = 0; id <= 5000; id++ )
    {
        objectIds.Rows.Add(new object[] { id });
    }

    // create a query with a named parameter "@ids"
     var selectQuery = "SELECT Id FROM [MyTable] WITH (NOLOCK) WHERE [Id] IN (SELECT [ObjectId] FROM @ids)";

    var selectCommand = new SqlCommand();

    // add the "table-valued parameter" to the command
    var selectParameter = selectCommand.Parameters.AddWithValue("@ids", objectIds);
    selectParameter.SqlDbType = SqlDbType.Structured;
    selectParameter.TypeName = "dbo.ObjectIdTable";

I don't know how this affects performance vs batching, and you need to add a User Defined Type to the database (in the example above I had to do this first "CREATE TYPE dbo.ObjectIdTable AS TABLE (ObjectId int)") but I figured I'd mention it just in case it's useful.

**Comment by droyad** [comment]
It now errors out with a Request Too Long so we don't ever hit the API. However a quick test shows that we do sensible client side batching with IDs. We also haven't gotten any further reports recently.
