### ISSUE TITLE
Unable to delete Environments created by Octopus 3.2 or earlier

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Issues#4487]
## Summary
Cannot delete an Environment. When that Environment was created in a version of Octopus 3.2 or earlier.

Affected versions 
### Error

> Error resolving type specified in JSON 'Octopus.Server.Orchestration.Deploy.DeploymentState, Octopus.Server'. Path 'StateObject.$type', line 1, position 2420. Could not find type 'Octopus.Server.Orchestration.Deploy.DeploymentState' in assembly 'Octopus.Server, Version=2018.2.8.0, Culture=neutral, PublicKeyToken=null'.

## Details
An Environment created prior to version 3.2 had a specific structure, when that's being deserialized now, as part of delete cascade checks it throws that error, and cannot be deleted.

Customers reports:
https://secure.helpscout.net/conversation/555991431?folderId=1228416 (internal link)

## Workarounds
No real work around, as it's not possible to hide environments, so this no longer needed Environment will still remain to be visible.

**Comment by alfhenrik** [comment]
Also happens when running retention policies (internal link): https://secure.helpscout.net/conversation/562112392/25989/?folderId=571729

**Comment by alfhenrik** [comment]
### Summary
After investigations it turns out that this is not related to environments, but rather deployments that have been made. We moved one of the types, `DeploymentState`, used on the deployment resource and made a migration script to fix up any deployments in the database that contained this type in its `JSON` blob.

The affected customers both upgraded to `3.2.14` which we had to pull due to a backwards compatibility issue, so my best guess is that they then reverted back to the version they had upgraded from and kept on using Octopus as per normal until a new version had been released. 

The problem here though is that the migration script we had written to remove the type declaration in the deployment `JSON` blob would not be executed again as it had already been run and this then left deployments in a bad state that caused the exception mentioned above when trying to delete an environment or when the retention policy ran and tried to delete releases/deployments etc.

### Workaround
Run the following SQL script on your Octopus database:
```
UPDATE [dbo].[Deployment] 
SET JSON = REPLACE(JSON, '"$type":"Octopus.Server.Orchestration.Deploy.DeploymentState, Octopus.Server",','')
WHERE JSON  LIKE '%"$type":"Octopus.Server.Orchestration.Deploy.DeploymentState, Octopus.Server",%'
```
