### ISSUE TITLE
Adding a step with a large script pegs the CPU for a long time

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4519]
The initial clone results in 100% CPU usage with the `POST` to `/deploymentprocess` taking 15 seconds. Performance degrades as more steps are cloned. Does not happen for "Run script" step, have not tested with other community templates.

To reproduce:
- Create a project
- Add a "Chain Deployment" step
- Clone the "Chain Deployment" step
- Continuing cloning for more fun
 
Reported by: https://help.octopus.com/t/when-i-clone-a-chain-deployment-load-on-server-goes-to-90

**Comment by tothegills** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cloning the Chain Deployment step pegs CPU for a long time](https://trello.com/c/VLvCTBEs/73-cloning-the-chain-deployment-step-pegs-cpu-for-a-long-time)

**Comment by droyad** [comment]
The script in this step is 47k in size, very large. The slowness is due to the diff done for the event (audit) record. About 20-40 seconds on my machine.

Code: https://github.com/OctopusDeploy/OctopusShared/blob/6d35cdf709bd4754d57d3e9abaa2280e6e4b8162/source/Octopus.Shared/Internals/DiffMatchPatch/GoogleDiffMatchPatch.cs#L912

![image](https://user-images.githubusercontent.com/1687639/57506826-59034b00-7340-11e9-85ca-a43b354578e3.png)

**Comment by droyad** [comment]
While annoying it's not a showstopper this only occurs on add of this step (other steps add quickly even when this step is present). Editing and re-ordering runs quickly. Fixing it would be time consuming, therefor closing it.
