### ISSUE TITLE
Choose control-type when configuring prompted variables

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#4531]
Currently all prompted-variable are text inputs.  Only the label and description and whether a value is mandatory can be configured:

![image](https://user-images.githubusercontent.com/113759/39508781-054234a2-4e27-11e8-9511-c310b74c4e3c.png)

We should support similar options as when configuring tenant variable-templates:

![image](https://user-images.githubusercontent.com/113759/39508852-48995924-4e27-11e8-8da9-295290d67d0a.png)

Specifically, we would allow configuring:
- Control-Type: Drop-Down, Checkbox, etc
- Default Value

UserVoice suggestions:
- https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/5948062-checkbox-and-dropdown-in-prompted-variables
- https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6016396-variable-prompt-templates

**Comment by MJRichardson** [comment]
Release Note: Support for checkbox and drop-down control-types for prompted variables

**Comment by umair-syed-webjet** [comment]
more specifically, I am trying to use a dropdown/list of fixed values for the user to select from instead of plain text. Everytime I select any format for the value and save it, it reverts back to plain text.
![image](https://user-images.githubusercontent.com/12508030/48171150-ae897b80-e34e-11e8-97b9-38e1cd3c0878.png)
