### ISSUE TITLE
Missing Permissions "VariableEdit" when editing Common Tenant Variables

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4544]
## Octopus Version:

Tested and Replicated in Octopus version 2018.4.9

Issue not replicable in Octopus version 2018.4.6

## Issue:

When navigating to `Tenant > Variables` an error message indicating `Missing Permission VariableEdit` appears despite the logged-in User having the appropriate permission.

The issue is not replicable unless either `Project` or `Environment` scoping is applied to the associated Users Team.

This issue appears to be caused by a change in 2018.4.7 related to Tenant permissions (see related issue)

### 2018.4.6

![update tenant variable 2018 4 6](https://user-images.githubusercontent.com/33012349/39735341-8154b92a-52be-11e8-94bd-c1ccde9883f0.gif)

### 2018.4.9

![update tenant variable 2018 4 9](https://user-images.githubusercontent.com/33012349/39736812-462d7d9e-52c5-11e8-9d84-e49ba48b6790.gif)

## User Permission Export:

[Permissions Export.txt](https://github.com/OctopusDeploy/Issues/files/1982174/Permissions.Export.txt)

## Workaround:

To workaround this issue there are two solutions;

1) Remove Project/Environment Scoping from the associated Team 

or

2) Rollback to Octopus version 2018.4.6 ensuring a Database  backup is taken prior.

## Source:

https://help.octopus.com/t/problem-with-permissions-since-2018-4-9/19907/4

## Related Issue:

https://github.com/OctopusDeploy/Issues/issues/4474

**Comment by mayuanyang** [comment]
The TL,DR is this is by design.
A tenant can have 2 types of variables, `Project Variables` and `Common Variables`. When a scoped user try to modify a `project variable` for a particular environment, the permission system will now make sure it is allowed within the user scopes (from 2018.4.7).

However for a `Common Variable`, it does not have the concept of for a specific environment or project as it means to be shared by all environments and projects. In this case by letting user to modify these variables will potentially open the hole of a variable value get used for the unscoped project and environment which could cause a serious security issue.

### Future reference
We could consider using the `VariableEditUnscope` permission that to grant wild card to projects, environments and project groups when editing `Common Variables`. More analysis is required before implementing this.

**Comment by adamwhitekallidus** [comment]
Our problem is that there doesn't appear to be a way to grant someone the ability to edit common variables and scoped project variables. As soon as we put a restriction on VariableEdit the ability to edit common variables is lost.

Surely it makes sense that users can edit common variables AND be restricted on what project variables they can edit?
