### ISSUE TITLE
Password managers auto fill sensitive variables

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#4614]
When filling in the value for sensitive variables password managers can automatically populate the sensitive field (usually with the user's Octopus password).

Reported by DealerSocket.

See https://lastpass.com/support.php?cmd=showfaq&id=10512

 Related: #4450 ?

**Comment by droyad** [comment]
Possible workaround for the end user: https://stackoverflow.com/questions/20954944/stop-lastpass-filling-out-a-form/28216951#28216951

May have been fixed in `2018.5.6` [internal link](https://octopusdeploy.slack.com/archives/C4WNL3PQ9/p1527807772000367)

**Comment by zentron** [comment]
They and mozilla have explicitly said they will ignore the `autofill=off` parameter "due to security" which to me is a poor excuse to break the user experience like this when autofill doesn't make any sense (let the developer decide).
https://bugs.chromium.org/p/chromium/issues/detail?id=352347
https://bugzilla.mozilla.org/show_bug.cgi?id=956906

As for workarounds, chrome appears to be _really_ inconsistent with this. Our elements already say `autocomplete=off` and that obviously doesn't work. One work around suggestion is that it needs to be on the `<form>` element. I cant quite decipher what chrome is doing here. 

If i put a form element around the sensitive element 
![image](https://user-images.githubusercontent.com/1830666/58229126-30ce1000-7d74-11e9-8ff6-d16728c82666.png)
it not only appears to work for the password field we have wrapped, but for other fields _outside the form_ we want autocomplete off for (like in this example the username)
![image](https://user-images.githubusercontent.com/1830666/58229607-83f49280-7d75-11e9-8d83-c0fc7aeafdc0.png)

Looks sweet right? lets just put a form in the root and be done.. not so fast. as soon as i put the form a tiny way up in the DOM (in this case in the generic AccountEdit control that hosts the specific type controls), then
![image](https://user-images.githubusercontent.com/1830666/58229721-cddd7880-7d75-11e9-9797-3a787c9ac4bb.png)

 it's ignored again

![image](https://user-images.githubusercontent.com/1830666/58229709-c4eca700-7d75-11e9-9d52-9d65b71c5821.png)

**Comment by zentron** [comment]
I'm closing this ticket as a _cant_ fix as we are at the mercy of the browsers who seem to have their own agenda and would be a fools errand to try and fight given it sounds like they have thwarted other work arounds
