### ISSUE TITLE
No variables substitute in email step when using Format DateTime

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4735]
Octopus 2018.6.15

Steps to reproduce
1) Create an email step
2) in the body, include system variables (i.e. `#{Octopus.Project.Name}`) along with the MyDate variable with formatting (shown in blog post: https://octopus.com/blog/octostache-json-formatting#formatting)
It'll look something like this:

```
A successful deployment of #{Octopus.Project.Name} in the #{Octopus.Environment.Name} environment on #{ | NowDate | Format DateTime \"HH dd-MM-yyyy\"} has occurred.
```

Result: The email writes out just that without any of the variables substituting, including the system variables.

Workaround: If you remove the escape from the quotes (`#{ | NowDate | Format DateTime "HH dd-MM-yyyy"}`), all variables in the body are substituted as expected.

Source: https://help.octopus.com/t/octopus-project-name-and-other-variables-not-being-replaced-in-email-body/20792

**Comment by droyad** [comment]
This would be due to the evaluation aborting due to an error and then just returning the original string. We should look into whether we can easily just skip over that one. If not, close as wont-fix

**Comment by zentron** [comment]
Although Octostache is currently built to fail to replace _any_ variables if the expression contains invalid variable patterns, a fix has been added to provide a warning if this takes place since it is understandable that a block of text like the body is much more likely to encounter this problem.
Not that if a variable cannot be found, the other variables in the body will still be replaced

**Comment by zentron** [comment]
Release Note: Provide warning if email body fails to evaluate variables
