### ISSUE TITLE
Blocked Progression allows you deploy to next environment if current environment is optional

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#4942]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When blocking a release it is possible to deploy to the next environment if the current environment is marked as optional. 

## What I expected to happen

Once I block progression on a release it isn't allowed to progress.

## Steps to reproduce

1. Mark an environment as optional
![image](https://user-images.githubusercontent.com/38642825/46422005-04885500-c6f9-11e8-950c-a898d2315b37.png)
2. Block progression on a release
3. Because the environment it failed in is optional I can proceed onto the next one.
![image](https://user-images.githubusercontent.com/38642825/46422068-241f7d80-c6f9-11e8-9352-f0fafeca4a84.png)

## Affected versions

**Octopus Server:** 2018.8.7

## Workarounds

None.  Aside from marking all environments as required.

## Links

Customer report this via a private slack chat.

**Comment by zentron** [comment]
If i recall correctly this is particular scenario by design (or at least accepted based on other rules and behaviours of optional phases). If the first phase is optional that implies that the second (non optional) phase can be also considered as active and hence immediately deployable. 

If the deployment is blocked "at the first step" then the [blocked deployment rule](https://octopus.com/docs/deployment-process/releases/blocking-deployments):
```
- The first phase can always be deployed to even if the release is blocked before any deployment has taken place.
```
applies and so both can be deployed to since they are both "active" first phases. 

Optional and Blocked phases both have some complex edge case conditions which only get more complicated when combined, particularly when _also_ being the first phase :).
If this is an undesirable behavior perhaps we need to clarify some of these rules

**Comment by OctopusBob** [comment]
This is by design.  The person who reported the issue is fine with that.
