### ISSUE TITLE
Tenant common variable evaluation for untenanted deployment

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#4967]
# The problem
Tenant specific variables do not get evaluated in untenanted deployment which might lead to confusion. E.g. a project has a tenant common variable with the value of  `#{Octopus.Deployment.Tenant.Name}`, it get resolved to the right tenant name for tenanted deployment, but got ` #{Octopus.Deployment.Tenant.Name}` as the value for untenanted deployment

## What I expected to happen
In most of the cases, untenanted deployment should not rely on any tenant specific variable, or we should make it clear in our docs to describe the behaviour

## Links
https://secure.helpscout.net/conversation/681576617

**Comment by boonew2** [comment]
For some more context around this the tenant variables existing for untenanted deploys was apparent because of the variable iterator in Octopus. 

I have some variables that follow a convention like: 
`Tag[<key-name>].Value` = `something`
and then have another variable that assembles all tags into a json array with something like:
```
[#{each tagPair in Tag}{"Key":"#{tagPair}","Value":"#{tagPair.Value | JsonEscape}"}#{unless Octopus.Template.Each.Last},#{/unless}#{/each}]
```
I added some common variable templates following the convention like: `Tag[deploy-tenant].Value` with a default value of `#{Octopus.Deployment.Tenant.Name}` and was surprised when the iterator picked up that `Tag` on an untenanted deployment.

**Comment by zentron** [comment]
This is by design. Variables which are only relevant in tenanted deployments (e.g. `#{Octopus.Deployment.Tenant.Name}`) will only be provided with a value when the deployment includes a tenant. For un-tenanted deployments this variable will remain unevaluated. This also means that if user-provided project variables are depending on this variable, they will need to be scoped to the appropriate tenant-tags if they dont want those second level variables to be present.

**Comment by boonew2** [comment]
@zentron just to make sure the general issue was understood (because the summary on this issue when it was opened didn't really capture the spirit of it)..

It wasn't that `#{Octopus.Deployment.Tenant.Name}` wasn't evaluated (cause of course it couldn't be without a tenanted deploy) it was that a tenant only variable was picked up by an iterator at the project level

**Comment by zentron** [comment]
It's still not entirely clear to me when the expected\actual behaviour is however based on my current understanding and testing it seems to function as expected. While Project Variables templates (which i believe you are talking about?) are typically provided values by a tenant, they also allow the ability to set a default value which would typically be used of there was no tenant involved in a deployment. It is quite common to have a process which can be run tenanted or untenanted and in the latter case the template defaults serve to provide those untenanted values.

To further clarify what is happening in your scenario, could you please send some screenshots\examples of your variable configuration to support@octopus.com and we would be happy to address them, perhaps by creating another more detailed ticket.
