### ISSUE TITLE
Docker acquisition script moved from Server to Calamari

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#5425]
Prior to this change, the acquisition step for docker (`docker pull`) was a special script that would be passed to the target during acquisition. This worked differently to all other acquisition processes which would call the [`calamari download-package` command](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Commands/DownloadPackageCommand.cs).

As part of our work to provide a Tentacle that can run on Linux, these operations need to be standardised to make the creation of the bootstrapping script simpler (bash vs powershell) and as a result the docker pull logic will be moved into Calamari (https://github.com/OctopusDeploy/Calamari/commit/7091945ace5dba20fc0b71cc04004ee9f7bf87d4) so that the server can invoke the same acquisition logic as with other package types. 

**Note: this change should have no observable differences to the end user and result in a functionally equivalent process**

**Comment by zentron** [comment]
Updated in: https://github.com/OctopusDeploy/OctopusDeploy/commit/34ce3ac54b1b03f28338fc36ab3ff2418ae94ae6

**Comment by gchuchuganov** [comment]
It used to work, since the April 1st version it can not get to "docker pull"

13:55:44   Verbose  |         Octopus Deploy: Calamari version 4.15.1-ci0003

13:55:44   Verbose  |         Feed type provided `Docker` using DockerImagePackageDownloader
13:55:44   Error    |         bash: Calamari/Temp/8ed613ec-25e9-4475-a146-c288d820fe2f/Bootstrap.46d-4d86-b5fc-6b9e9f31ce9b.Octopus.DockerPull.sh: No such file or directory
13:55:44   Error    |         Failed to download package Project/image v19 from feed: 'https://registry'
13:55:44   Error    |         Unable to pull Docker image

**Comment by matt-richardson** [comment]
Hi @gchuchuganov - your best bet is to get in touch with us via one of our support channels - https://octopus.com/support, and send through all the details you can. That way we can dig into it properly.

**Comment by gchuchuganov** [comment]
Confirming this was fixed in https://github.com/OctopusDeploy/Calamari/pull/382
Meanwhile after three daily emails support told me "could not reproduce the issue".

**Comment by zentron** [comment]
Hi @gchuchuganov , I can confirm that we could not reproduce this issue. We had trouble getting enough information from affected users so took a hunch as to the cause of the problem being something with the OS not allowing the files to be written to the OS temp directory. Glad to hear its working for you now.

**Comment by gchuchuganov** [comment]
Thanks for fixing it, mate!
