### ISSUE TITLE
UI audit screen highlighting changes

### ISSUE THREAD

**Issue by thebigmoosey** [OctopusDeploy/Issues#5486]
# The enhancement

We want to make deltas in the audit screen be more discoverable. When you have a small, single-character change to something like a project variable set, it can be very difficult to spot the delta currently. If we add padding and borders, we can make this more discoverable very easily.

## Mockup

The Problem:
<img width="995" alt="2019-04-17 12_09_53-Microsoft Edge" src="https://user-images.githubusercontent.com/819605/56255884-dfde5280-6109-11e9-8521-fa54bc4ff978.png">

The Proposed Solution:
![2019-04-26 15_46_55-Audit - Octopus Deploy](https://user-images.githubusercontent.com/819605/56785960-91803080-683a-11e9-92ee-74a7613be0be.png)

## Links
Internally raised by TAMs and TAM customers.

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit screen deltas - make these more discoverable](https://trello.com/c/3QElAxdW/593-audit-screen-deltas-make-these-more-discoverable)

**Comment by fsettele** [comment]
Hi Mark,

some thoughts about your proposal to make it finally right:
- To make the audit compare better readable it would be great, that kind of the default view shows only the line(s) where the change was +-5 lines to get the context. With a click on "Show complete File" the current behavior will be restored
- To make it easier to detect differences I would go to adapt the "git compare" format. In this case this smaller changed will be dedected faster as well
- And finally, ensure to have a standard sorting of the audit item. I sometimes saw, that the were no actual differences, but e.g. the Variable was shown at the bottom instead of the top and so I had two differences displayed, but there was none.

Wondering what you think?

Cheers,
Franz

**Comment by thebigmoosey** [comment]
Hi Franz (cc @fsettele),

Thanks for your thoughts here. There's been similar feedback internally about collapsing this view further, and having the ability to click "next, next, next" through each of the changes, so we'll look into that next week and see what we can come up with.

For this issue, the focus is purely on UI-updates and not making any changes to the API with regards to how the diffs are currently generated/stored on the backend (so the changes we make for this issue will work consistently with any previously-stored events).

However, we can can definitely consider a more advanced diff-engine in the future, where the output would be more similar to GitHub diffs, as you mentioned.

Regarding the variable issues you've noticed, we haven't been able to reproduce, but if you see this consistently, we'd recommend reporting that to support and our support staff can investigate further.

Cheers
Mark

**Comment by thebigmoosey** [comment]
Release Note: UI improving delta highlighting on the audit screen
