### ISSUE TITLE
Out of date Tentacle and Calamari warnings are no longer useful 

### ISSUE THREAD

**Issue by jburger** [OctopusDeploy/Issues#5643]
Currently, users of Octopus Server using Machine Policy to automatically upgrade tentacles during deployments can see warnings regarding out of date Tentacle and Calamari instances. [Relevant documentation here](https://octopus.com/docs/infrastructure/machine-policies#MachinePolicies-ConfigurehowCalamariandTentacleareupdated)

As evidenced by customer queries, we are finding that these warnings do not hold much value anymore, now that the default behaviour is 'on demand' upgrades. For e.g.

```
As a user I want to be able to upgrade my Octopus server without negatively impacting deployment schedules nor do I want to cause undue consternation among the operations support folks.
```

The 'Healthy with warnings' icons shown in the deployment targets view (and other locations) are also causing some confusion. 

## Proposed solution
We think that removing these warnings entirely will encourage use of the default behaviour, which carries better performance characteristics overall, and not make unnecessary alarm bells sound off for customers.

## Before
![before](https://user-images.githubusercontent.com/579657/60071244-9e48d400-9758-11e9-8c61-2582a91a7f99.png)

'Healthy with warnings' icons are displayed for such deployment targets.

## After
![after](https://user-images.githubusercontent.com/579657/60071260-a43eb500-9758-11e9-9fb0-52beba41531a.png)

Such targets would not be labelled as 'Healthy with warnings'

## Workarounds

At this stage, ignore the warnings, or move to the 'Always up to date' model. The trade-off for the latter is that in large ecosystems, tentacle upgrades can take a significant amount of time due to a CPU bound limit on how many upgrades can be done at once.

## Links

[public support ticket](https://help.octopus.com/t/increase-number-of-concurrent-tentacle-updates/23368/6)
[internal discussion thread](https://octopusdeploy.slack.com/archives/C033W4273/p1561418888036100)
[related issue](https://github.com/OctopusDeploy/Issues/issues/4374)

# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

**Comment by tgillitzer** [comment]
The "orange box" alert isn't the only issue here.   The other issue is that the tentacles are classified as "Healthy with Warnings", which causes our operations staff to fret over them when they are perfectly functional.   This issue as written doesn't address that.

**Comment by zentron** [comment]
Added to a potential roadmap item for reconsidering tentacle upgrades

**Comment by zentron** [comment]
The plan will be to change the way we message Tentacle changes by leveraging semver.

## Background
The current granularity for messaging a Tentacle requiring an upgrade is based on the following possible states
```C#
public enum UpgradeStatus
{
   NoUpgrades,
   UpgradeSuggested,
   UpgradeRequired
}
```

An `UpgradeRequired` means the user is _force_ to do the upgrade before using the target while an `UpgradeSuggested` shows up as a warning and in some cases (such as some machine policies) may still result in an upgrade being triggered automatically. 

## Solution
1. To reduce the cases where an upgrade is unnecessarily performed, a forth state `UpgradeAvailable` will be provided which will allow for an upgrade to take place, through the button appearing, but no warnings or forcing functions will appear.

2. Rather than the strange logic currently used for determining states we will instead use Semver to indicate upgrade requirements such that relative to a given self-reported Tentacle version, when compared with the Tentacle version the Octopus Server has available:
  * Major bump = Upgrade Required
  * Minor Bump = Upgrade Suggested
  * Patch Bump = Upgrade Available

3. Since most current logic will typically be concerned with checking for the existing states, there should be minor changes needed in both the front and back-end to support this change.

## Further Info
See [internal doc](https://docs.google.com/document/d/1o50QMlpsmoletlhEvju7ZH_k02OJ3TNUk_TO1oiU7NI) for further details

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.899 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.899 |
| 2023.1+ | _all releases_ |
