### ISSUE TITLE
Wildfly deployments not working in 2019.6.3

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#5697]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

It seems a few changes in Calamari broke deployments to Wildfly

## What I expected to happen

It should just work

## Affected versions

**Octopus Server:** 2019.6.3

## Workarounds

nope

## Links

https://secure.helpscout.net/conversation/900023104/47047/

**Comment by johnsimons** [comment]
Release Note: Wildfly deployments working again

**Comment by mcasperson** [comment]
The issue results in the wrong argument being passed to the package deployment command. In the screenshot below, you can see the `name` is set to `localhost`, which is the WildFly server address and not the name of the artifact. This in turn means WildFly doesn't know what to do with the file (because it expects a name like `application.war`).

![image](https://user-images.githubusercontent.com/160104/61101676-06fcb400-a4ae-11e9-8fde-5900f155e358.png)
