### ISSUE TITLE
Licence activation failure for older builds 

### ISSUE THREAD

**Issue by adamoctoclose** [OctopusDeploy/Issues#5904]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [ ] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you generate a licence in Octofront and use that in old Octopus builds, it fails to activate the licence. I believe that older builds of Octopus do not recognise the "Kind" element, so, we may need a may of generating licences for old Octopus builds. It is tested in the latest version of Octopus and it is working all ok. I'm not sure what point this did stop working!

## What I expected to happen

Licence should activate and not show any errors.

## Steps to reproduce

1. Go to Configuration 
2. Click on Licencing 
3. Paste new in new licence from Octofront
4. See error "Your licence has expired."

### Screen capture

![Screenshot](https://user-images.githubusercontent.com/54795433/66757615-68a93180-ee94-11e9-9133-3a7c95de2969.png)
)

### Log exerpt

```
Insert your log exerpt here.
```

## Affected versions

**Octopus Server: 3.17.5** 
**Octopus Server: 2018.5.6** 

## Workarounds

Options 1 would be to upgrade to latest Octopus version and activate licence.

If you can't upgrade then contact Octopus support who will be able to help resolve the issue.

**Comment by tajamal** [comment]
I am using having issue with a new license and it's not working with octopus version v2018.14

![image](https://user-images.githubusercontent.com/1224863/67002999-55d56d80-f0dd-11e9-84d6-390a14f218f0.png)
Are there other workaround then upgrading, as generating a license for older versions ?

**Comment by Justin-Walsh** [comment]
Two new reports of this today: (Internal links)
https://secure.helpscout.net/conversation/993849800/52424?folderId=2845821
https://secure.helpscout.net/conversation/994859057/52503?folderId=557077

**Comment by matt-richardson** [comment]
Looking into this, xml being used is:
```
<License Signature="xxxxxxxxxxx">
  <LicensedTo>XYZ Limited</LicensedTo>
  <LicenseKey>12345-12345-12345-12345</LicenseKey>
  <Version>2.0</Version>
  <ValidFrom>2017-05-30</ValidFrom>
  <Kind>Subscription</Kind>
  <ValidTo>2020-10-29</ValidTo>
  <ProjectLimit>Unlimited</ProjectLimit>
  <MachineLimit>25</MachineLimit>
  <UserLimit>Unlimited</UserLimit>
</License>
```

which is being evaluated in older versions of Octopus as "maintenance expired".

The code is getting `maintenanceExpiresIn = -520 days`
Because `key.LicensedForReleasesUntil = 30/05/2018 12:00:00 AM +10:00`
Because [`LicensedForReleasesUntil => MaintenanceExpires ?? (ValidFrom?.AddYears(1));`](https://github.com/OctopusDeploy/OctopusDeploy/blob/b83bedc9d6b6d748db7f372fabeeb5cd47988310/source/Octopus.Core/Features/Licensing/LicenseKey.cs#L40)
and there is no MaintenanceExpires on that license
which is showing up in the ui as ["Your license has expired"](https://github.com/OctopusDeploy/OctopusDeploy/blob/b83bedc9d6b6d748db7f372fabeeb5cd47988310/newportal/app/areas/configuration/components/License/License.tsx#L200-L203)

**Comment by thekatstevens** [comment]
Quick update folks! We've done some investigating and identified that this issue presents when using an old Octopus license that has recently been upgraded to a "modern" license (since Sept 2019), and when using a version of Octopus Server which doesn't fully understand this new license shape.  

**What is the issue?**

In September 2019 we changed our licensing, and the way Octopus Server reasons about it. Versions of Octopus Server prior to this change don't have the new licensing code, and use a fallback strategy that says "if the license doesn't specify a maintenance period, assume it's one year from the `ValidFrom` date in the license". In these upgrade cases, the licenses were originally purchased more than a year ago, so Octopus thinks the license is out of maintenance.

**How does it affect me?**

Octopus Server will _think_ that the maintenance has expired, even though it hasn't, and it will show a `Your license has expired` error message as shown above by @tajamal. However, all the limits are still correctly interpreted and enforced, and you are not blocking from creating releases or deploying - but the message is confusing.

**How can I fix it?**

If you have the capability, upgrading to Octopus 2019.8.6 or higher will ensure that you have the new licensing code, and the license will be correctly interpreted.

If you are unable to upgrade, please bear in mind that the error doesn't cause any negative side-effects and won't block any of your activities. However if would like the error to go away, please email us at **support@octopus.com** and we will re-generate your license in a slightly different way to ensure that the maintenance period is correctly interpreted.

**Comment by alexrolleyoctopus** [comment]
New report of issue: 
https://secure.helpscout.net/conversation/1013082885/53547?folderId=1465198

**Comment by thekatstevens** [comment]
Good news, we now have a workaround for this problem! As mentioned above, the proper "fix" for this is to upgrade to Octopus Server v2019.8.6+ so that the license key will be correctly interpreted. 

**What if I can't upgrade right now?**
Keep in mind the error message you are seeing doesn't actually block any activities at all - you can still deploy and add targets up to your licensing limit, and upgrade to any newer version of Octopus Server (despite what the message says). This "error" is simply a warning.

If you want the error to go away, please [email our support team](mailto:support@octopus.com) and they will be able to generate a special "legacy" version of the license key and send it to you, which will cause the error to disappear.
