### ISSUE TITLE
VariableEditUnscoped does not allow creation of channel scoped variables

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#5926]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When a user is assigned to a Team that is granted access to a limited number of environments, that user is unable to create a variable scoped to just a Channel. Even if the team has the VariableEditUnscoped role.
When this is attempted the user receives the message 
`You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: VariableEdit`

## What I expected to happen

User should be able to successfully save variables scoped to just a Channel.

## Steps to reproduce
Create Octopus user and new Team with Role 'Project lead' scoping on Projectgroup and two Enviroments

1. Amend Project Lead user role and add VariableEditUnscoped permission
2. Create a new team and restrict to a single environment (ensuring you have more than one environment created in total)
3. Assign a new user to this new team
4. Create a new project variable and scope to a specific Channel
5. Save variable

## Affected versions

**Octopus Server:** 2019.10.1

## Workarounds

Add environment scoping to the new variable allows it to be saved

## Links

[Internal Link](https://secure.helpscout.net/conversation/985691869/51841?folderId=3252735)
User Permission Export:
[Permissions_export_2019_10_22__06_41_38_UTC.zip](https://github.com/OctopusDeploy/Issues/files/3754074/Permissions_export_2019_10_22__06_41_38_UTC.zip)

**Comment by NickJosevski** [comment]
The permission `VariableEditUnscoped` and `VariableViewUnscoped` function on the Environment dimension.

The way Variable scoping works when it's related to a channel is we determine ALL the environments that are "derived" from the lifecycle associated with the channel. We then combine them with the "direct" environment scopings (if any) that exist on the variable.

Therefore the scoping to channel is correctly blocking this user who lacks access on at least one of the Environments in the channel, because for an edit action you must have the edit permission for ALL.

It's a known problem that the message users get is not clear that it's _scoping related_.
