### ISSUE TITLE
Octo.exe and TeamCity improvements

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#638]
- [x] Fix bug in Octo.exe that prevented `deploy-release` from working
- [x] Add `--version latest` support to Octo.exe's `deploy-release` command
- [x] Add a `promote-release --from Test --to Production` command
- [x] TeamCity build runner for the above

**Comment by frankn** [comment]
of late, i have noticed that the promote-release command sometimes picks an older version instead of the latest. Our build works as follows, 
1. Teamcity invokes a deployment to our "CI" environment in octopus via octo.exe,  after a successful deployment, 
2. TeamCity runs acceptance tests 
3. TeamCity promotes the release from CI environment to QA environment. However, the promote does not always pick the latest version. 

I would like to specify the version to promote as i think that octo.exe is promoting the release before the release has propagated to the dashboard. 

Currently, this is how the version number is determined in PromoteReleaseCommand, 

    var dashboardItem = dashboard.Items.Where(e => e.EnvironmentId == environment.Id && e.ProjectId == project.Id)
                .OrderByDescending(i => SemanticVersion.Parse(i.ReleaseVersion))
                .FirstOrDefault();
