### ISSUE TITLE
Jira Connect App configuration is failing to get authentication token

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Issues#6516]
# The bug

You encounter this error when testing the connection between Octopus and Jira:
```
Failed to get authentication token from Jira Connect App.
```
Following [our documentation](https://octopus.com/docs/releases/issue-tracking/jira#connecting-jira-cloud-and-octopus) on Connecting Jira Cloud and Octopus Deploy, when we reach step 5:

> Configure the Octopus plugin in Jira.
> Navigate to the Configuration ➜ Settings ➜ Jira Integration page in Octopus, copy the Octopus InstallationID, and add it to Jira App configuration.

On saving, we are shown an empty screen. On further inspection, the network calls are showing a 400 response:
![2020-08-17 15_06_55-Octopus Configuration - Jira](https://user-images.githubusercontent.com/819605/90359113-5642ea00-e09b-11ea-839c-c72f774dfdfc.png)

As an end-user, if we don't notice this network error and try to test our connection in Octopus, we are greeted with the following error:
![2020-08-17 15_07_47-Settings _ Jira Integration - Octopus Deploy](https://user-images.githubusercontent.com/819605/90359153-6eb30480-e09b-11ea-8caf-60aa932503e4.png)

```
Failed to get authentication token from Jira Connect App.
```

The customer report linked below is even showing that they had previously connected an app successfully and were receiving this same error.

We suspect something has changed on Jira's side that has caused our integration to stop working (considering we have not deployed any updates to this integration recently).

## Affected versions

**Octopus Server:** All versions - due to this relying on the third-party integration with Jira.

## Workarounds

There are no known workarounds at this time.

## Links

Customer ticket: https://secure.helpscout.net/conversation/1247764820/68689?folderId=3252735
Repro'd instance (talk to MarkS): https://markse.atlassian.net - I used a new personal instance to ensure I would see what customers were seeing (avoiding any super-permissions that may exist on our company atlassian account).

**Comment by slewis74** [comment]
We were able to reproduce this locally and discovered that the issue was being caused due to the CSRF handling code in ASP.NET Core throwing an error. The root cause of that error was that in the setup for the Connect App we had enabled the CSRF and set `SameSite=None` for the cookies it uses, but missed that you also have to explicitly set the Secure flag.
When that flag wasn't set the newer browsers would drop the cookie and cause the authentication handshake to fail and all you'd get is the blank screen (Network tab in the developer tools in the browser actually showed the cookied error under a tiny icon that was easy to miss).
We've put a patch into `1.3.0` of the Connect App and it is now live. In progress installations of the plugin may still fail the credential check after the save has been successful. We found that uninstalling the Jira plugin and starting its install again resolved that.
