### ISSUE TITLE
FeedId is not cleared from step templates

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6733]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When in a non-default space and you use Save A Copy on a Community Step Template that has a referenced package it will error with "The following Feed Ids cannot be found: feeds-builtin"

## What I expected to happen

It to work in non-default spaces.

## Steps to reproduce

1. Go to a non-default space.
2. Go to Library
3. Go to Step Templates
4. If one doesnt exist, add "AWS - Deploy Lambda Function" or another step template that has a referenced package.
5. Click the template to View / Edit it
6. Click Save As Copy (you do not need to change anything)
7. In the dialog that pops up just click Save (again, no need to change anything)
8. See error

### Screen capture

![image](https://user-images.githubusercontent.com/63259411/104470250-84175680-5587-11eb-85c9-6fab844fb09a.png)

### Log excerpt

```
There was a problem with your request.
The following Feed Ids cannot be found: feeds-builtin
```

## Affected versions

**Octopus Server:** 2020.5

## Workarounds

Remove the referenced package within the step template and add it back.

## Links

Source ticket: https://help.octopus.com/t/step-template-save-as-copy-not-working/26108/14

**Comment by droyad** [comment]
The UI doesn't clear out the FeedId field when switching from Specific Package to Let the project select

**Comment by droyad** [comment]
The step template UI allows the user to select between the template specifying the package or the consuming step specifying it:

![image](https://user-images.githubusercontent.com/1687639/104551358-772b5d80-5682-11eb-896a-29416026b755.png)

When the `Let the project select the package` field is selected, the `FeedId` field in the data is not set to `null`, it still contains the selected FeedId. It has always not done this. This is not normally a problem as the `FeedId` is valid for that space, so validation passes. 

example:
```json
{
  ...
  "Packages": [
    {
       ...
      "PackageId": null,
      "FeedId": "feeds-builtin",
      "Properties": {
        "Extract": "False",
        "SelectionMode": "deferred",
        "PackageParameterName": "AWS.Lambda.Package"
      },
    }
  ],
 ...
}
```

The problem occurs when that template is export and then imported into another space (e.g. via the community library). Since `2020.5.0` the FeedId is validated to make sure it's a valid Id, causing the error to display. The UI though does not highlight where the error is. The solution is to change that radio button and then select a valid feed from the drop down and then switch the radio back.

Actions:
- Clean up the Community Library steps and remove `FeedId` where the method is `deferred`
- The UI should clear the feed on save
- The backend should validate that a `FeedId` is not set when `deferred` is set (or clear it)
