### ISSUE TITLE
When Using a Step Template and Certificate Parameters, if the Certificate Variable is Scoped to a Target Role the Certificate Will Output Blank

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6818]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using a Step Template and Certificate Parameters, if the Certificate variable is scoped to a Target Role, the Certificate will output blank. There is some odd behavior in that if you have a Certificate variable with multiple values, and one of the values is unscoped, the scoped value will correctly be used.

## What I expected to happen

I would expect the Certificate Parameter in a Step Template to work when it has a target role scope.

## Steps to reproduce

1. Create a Certificate and add it to a Project scoped to a target role
2. Create a step template that has a Certificate parameter and simply output the CertificatePem of the Certificate parameter
3. Add the step template to the project with the Certificate from step 1, and use that certificate variable
4. Deploy and look at the output, it will be blank.

### Screen capture

Here are my variables:
![image](https://user-images.githubusercontent.com/63259411/113914492-9a5e3880-97ab-11eb-9868-7ae053b874fc.png)

Here is the output from the step templates:
![image](https://user-images.githubusercontent.com/63259411/113914723-d7c2c600-97ab-11eb-8c85-4fc2534502da.png)

## Affected versions

Tested Versions it is broken in:
Latest at time of writing (2021.1.6460)
2020.6.4688
2020.5.6

Customer reports that this worked in `2018.2.3`

## Workarounds

1) Reference the Project variable itself within the step template instead of the step template parameter
or
2) Create a 2nd unscoped value within that certificate variable to allow the scoped variable to be referenced correctly.

## Links

Source Ticket (INTERNAL): https://octopus.zendesk.com/agent/tickets/66388
Cloud repro (INTERNAL): 
https://octopus-operations.octopus.app/app#/Spaces-83/projects/certificate-scoping-issue/deployments
https://octopus-operations.octopus.app/app#/Spaces-83/tasks/ServerTasks-66576/raw

**Comment by droyad** [comment]
The code [here](https://github.com/OctopusDeploy/OctopusDeploy/blob/891fd5dd573d933add82fb45dfb7345dcd46c14b/source/Octopus.Server/Orchestration/ServerTasks/Deploy/Manifest/ExecutionManifestFactory.cs#L549) expands (or copies?) the values from the project variables to names of the step template variables. Due to the scope being applied it doesn't do so for variables scoped to roles or targets. 

It should expand/copy all step template variables that _may_ be used in that action, making sure to keep the scope on the new variables the same (i.e. still scoped to role).

To reproduce:
- Add two certificates to Octopus (use the SelfSigned option) `CertScoped` and `CertUnscoped`
- Create a script step template with 2 certificate variables `ST_U` and `ST_S`
- Set the script to:
```
Write-Highlight "Unscoped #{ST_U.Name}"
Write-Highlight "Scoped #{ST_S.Name}"
```
- Create a project
- Create two certificate variables in that project `Scoped` and `Unscoped`, scope the first one to a role
- Use the step template and link the parameters up to the appropriate variable
- Set breakpoints and run.

**Comment by droyad** [comment]
We have started further investigation into this issue

**Comment by N-lson** [comment]
We have identified a potential fix. We are currently testing it and should have an answer soon.

**Comment by N-lson** [comment]
Release Note: Fixed an issue where scoped variables used as step template certificate/account parameters were not being evaluated correctly
