### ISSUE TITLE
Arbitrary release version strings can be supplied if the version leads with 10 or fewer leading digits.

### ISSUE THREAD

**Issue by paulegradie** [OctopusDeploy/Issues#6942]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have labelled the value stream (area/core, area/steps, ...)
- [x] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug
We noticed recently that we can successfully provide invalid release Ids that can fool the version parser.

One can successfully fool the version parser by supplying a random string that leads with 10 or fewer digits, e.g. `1262591882cccc3eb1bb19b476991ebf`

## Steps to reproduce
1. Create a new release
2. Provide a version id such as `1262591882cccc3eb1bb19b476991ebf`
3. This should produce an error, but it will succeed.

### Screen capture

Creating:
![image](https://user-images.githubusercontent.com/30226456/124855205-f83d2f00-dfeb-11eb-83db-be16e2614069.png)

Created:
![image](https://user-images.githubusercontent.com/30226456/124855539-6d106900-dfec-11eb-8243-342a9eccdc3a.png)

## Affected versions

**Octopus Server:** 2021.2

**Comment by mcasperson** [comment]
This is by design. The versioning was expanded to allow support for docker tags to account for scenarios where a project release was based off the tag of a docker image in a deployment process. `1262591882cccc3eb1bb19b476991ebf` is a valid docker tag, and to give it some semantic context it will be treated as a version with a major component of `1262591882` and a prerelease of `cccc3eb1bb19b476991ebf`.
