### ISSUE TITLE
When using external feeds, package versions multi-part prerelease labels will result in "The package was not found in the feed".

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeploy/Issues#6949]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have labelled the value stream (area/core, area/steps, ...)
- [X] I have tagged the issue appropriately (kind/bug, kind/enhancement, feature/ ...)

# The bug

When using external feeds, package versions with leading zeroes (e.g. 21.06.36) will result in "The package was not found in the feed". Feed tests do show the package and version correctly.

## What I expected to happen

It to find the package in the release if it sees the package in the feed test.

## Steps to reproduce

1. Create a package in an external feed (Artifactory Nuget used in my test) with leading zeroes in the version (e.g. 21.06.36)
2. Create a release using that package
3. See error

### Screen capture

![image](https://user-images.githubusercontent.com/63259411/125495751-b04eb38d-d9d6-403f-8ec4-ba12a961ff3d.png)

## Affected versions

**Octopus Server:** v2020.6.5197+ and 2021.1.7316+

## Workarounds

Remove the leading zeroes from your package or use the internal feed.

## Links

Source ticket (INTERNAL) : https://octopus.zendesk.com/agent/tickets/71219
Slack Convo (INTERNAL) : https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1624637471262200

**Comment by mcasperson** [comment]
Something to double check with this issue is package versions with a prerelease value ending in `i` or `c` rather than the provided example of a minor version component starting with a `0`. For example, it may be the prerelease string of `210630-48f5c0c` that is the cause of this issue, and not packages with versions like `21.06.36`.

If so, this may be related to https://github.com/OctopusDeploy/Issues/issues/6926.

**Comment by mcasperson** [comment]
Never mind my last comment, as the two issues are unrelated.

The root cause is the query made to get the packages. In the screenshot below I have a nuget repo with a package called `gittwo` and various versions with leading zeros:

![image](https://user-images.githubusercontent.com/160104/125540380-aa87213b-8b41-47ed-964c-e1eccceb391b.png)

This query, with no leading zeros, returns no results:

```
http://localhost:8082/artifactory/api/nuget/test/Packages(Id='gittwo',Version='1.6.0-release.test')
```

This query, with leading zeros, returns results:

```
http://localhost:8082/artifactory/api/nuget/test/Packages(Id='gittwo',Version='1.06.0-release.test')
```

`V2FeedParser` has the following code:

```
List<V2FeedPackageInfo> packages = await this.QueryV2Feed(string.Format((IFormatProvider) CultureInfo.InvariantCulture, "/Packages(Id='{0}',Version='{1}')", (object) UriUtility.UrlEncodeOdataParameter(package.Id), (object) UriUtility.UrlEncodeOdataParameter(package.Version.ToNormalizedString())), package.Id, -1, true, log, token);
```

`package.Version.ToNormalizedString()` will strip leading zeros:

![image](https://user-images.githubusercontent.com/160104/125540533-44e01d3a-9195-4839-9c96-ec660603c3d0.png)

**Comment by N-lson** [comment]
I tested with version `21.06.36` and wasn't able to reproduce this issue.

I did some digging in `ExternalHttpNugetPackageFeed` and `V2FeedParser` and I don't think the issue is with the leading zero, but instead with the prerelease label.

From testing with the original version `21.06.36-release.210630-48f5c0` this is what I found:

What initially happens as Matthew described above is that an initial query is made to a URL like the following:
```
http://localhost:8082/artifactory/api/nuget/test/Packages(Id='MyPackage',Version='21.6.36')
```
which will return no results.
However, the next line in `V2FeedParser` checks if any packages were found from the first query, and if not, it attempts to find the package by the Id. So then a second query is made to:
```
http://localhost:8082/artifactory/api/nuget/test/FindPackagesById()?id='MyPackage'&semVerLevel=2.0.0
```
Now the package **is found** from this query (along with all of it's versions). The problem however is this query is part of an `Enumerable.Where()` where the condition is:
```
(p => (SemanticVersion) p.Version == (SemanticVersion) package.Version))
```
Where p is the package which has just been found from the query, and package is the original package details. The `ReleaseLabels` part of the version is now a mismatch between the two. The original package only has one release label `release.210630-48f5c0c` however the queried package release label has now been split into two parts: `release` and `210630-48f5c0c`. So this package is never returned as a result.

We're currently investigating this issue.

**Comment by N-lson** [comment]
Release Note: Fixed an issue where retrieving external feed packages with multi-part prerelease labels in the version would result in "The package was not found in the feed"

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5291 |
| 2021.1 | 2021.1.7599 |
| 2021.2 | 2021.2.6580 |
| 2021.3 | 2021.3.519 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2020.6 | 2020.6.5291 |
| 2021.1 | 2021.1.7599 |
| 2021.2 | 2021.2.6580 |
| 2021.3 | 2021.3.519 |
| 2022.1+ | _all releases_ |
