### ISSUE TITLE
CaC Git File Storage Directory field adds a `/` on every key entry

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#7028]
### Team

- [X] I've assigned a team label to this issue

### Severity

One report with a workaround

### Version

2021.2.7428

### Latest Version

I could reproduce the problem in the latest version

### What happened?

When attempting to add any data into the Git File Storage Directory field in the Config As Code EAP feature, every key entry in this field adds an additional `/` after `.octopus`.

### Reproduction

1) Type in anything into the Git File Storage Directory feature
2) See extra slashes `/` added in on every letter entered

### More Information

![CaCGitFileStorageDirectory](https://user-images.githubusercontent.com/20388190/132610639-48a3b3cc-111a-47f1-bffc-59f9f8660ff0.gif)

### Workaround

Manually write out the desired input externally, and copy/paste it into the field. Note even backspace adds an extra slash.

**Comment by cstrzadala** [comment]
@KennethBates the [PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/10005) contains the fix for this issue. 

The @OctopusDeploy/team-config-as-code  team are now in the process of releasing the EAP from the `2021.3` release which currently follows `master`. The version on Deploy `2021.3.2117` confirms that the issue no longer exists for me. If you want to double check against this version (or the latest `2021.3.2124`) and if all looks good, feel free to close this issue.

**Comment by benjimac93** [comment]
@cstrzadala just to confirm this fix won't make itself into the 2021.2 branch right ?
