### ISSUE TITLE
Button on Redeploy page is disabled if there is a single tenant

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#7030]
### Team

- [X] I've assigned a team label to this issue

### Severity

Annoyance

### Version

2021.1.7316

### What happened?

Description of Issue
If you have a project with a single-tenant Octopus will auto-fill that tenant when the deployment screen loads.
If you use the re-deploy option from within Project > Releases > <release> the deployment screen will auto-fill the tenant but the deploy button will remain greyed out.
If the Release being select is not the latest release, it seems that the deploy button will become active.

### Reproduction

* Create a project and link a single tenant
* Create and deploy a release to that tenant
* Navigate to Project > Releases > Release and hit the Redeploy button
![inline-76277417](https://user-images.githubusercontent.com/1687639/132660863-4886dd1a-0477-4d40-9ace-a4d872e1582f.png)

​
* Tenant will be filled in but the deploy button greyed out
![inline993122957](https://user-images.githubusercontent.com/1687639/132660876-26f017d5-94cd-4199-b2dc-4e829b5ba6ae.png)

* Create a new release and deploy that to the tenant
* Attempt to redeploy the previous release - the deploy should appear active now​
![inline-902160394](https://user-images.githubusercontent.com/1687639/132660894-70698ff9-4c82-4735-879f-42721f26bc41.png)
​

### More Information

Copied from ZenDesk [ticket](https://octopus.zendesk.com/agent/tickets/72299)

**Comment by susanpann** [comment]
This behaviour is intentional - when re-deploying to an environment where only a single tenant is used, it automatically re-selects the tenant for re-deployment. It also defaults to skip tenants where the current version is the same as the one being re-deployed - this is to avoid accidental redeployments. 

To enable the deploy button, uncheck the box that says "skip tenants where <VERSION> is the current version deployed to <ENVIRONMENT>" (you may have to click on Advanced Selection Options depending on the version of octopus you have installed).
