### ISSUE TITLE
Inherit from parent option is not at top of dropdown list when selecting lifecycle in a channel

### ISSUE THREAD

**Issue by brentkinney** [OctopusDeploy/Issues#7148]
### Team

- [X] I've assigned a team label to this issue

### Version

2021.3.7082

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When selecting a lifecycle in a channel, I would expect the 'inherit from parent' option to be at the top and not listed alphabetically as it is not an actual lifecycle.
![image](https://user-images.githubusercontent.com/48770271/140380217-9ae2d3a8-a2e7-4349-9e0f-84e5ed1be81b.png)

### Reproduction

Open the lifecycle dropdown for a channel and the 'Inherit from parent' option does not appear at the top.

### More Information

This issue is not present in a 2019 build of Octopus and the list appears as expected.
![image](https://user-images.githubusercontent.com/48770271/140380336-04b401ed-fafe-408a-92b7-961650973d90.png)

**Comment by droyad** [comment]
While I was working on this, I got confused that the overview page showed a channel when the channel was set to inherited. Turns out the overview page shows the resultant channel from the inheritance. I've improved this by showing that it's inherited on the overview page. I also changed the list item to say "Inherit from project" instead of "Inherit from parent"

![image](https://user-images.githubusercontent.com/1687639/142820413-fc0b9dc9-b480-4e66-b389-73eeea920dc6.png)

**Comment by droyad** [comment]
Release Note: Sorted lifecycles correctly in the channel edit page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8915 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8915 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.8915 |
| 2022.1+ | _all releases_ |
