### ISSUE TITLE
API pagination happens before search terms are applied

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#7273]
### Team

- [X] I've assigned a team label to this issue

### Severity

Severity can vary depending on aspect affected, working example is that a user could not locate certificates in the library or in variables.

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

API requests that contain both `?take` & `?partialName` perform the order of operations incorrectly.

The `?take` is performed before the `?partialName` search, resulting in the search only being performed within the first X number of responses.

Example:

When searching for certificates, API call changes focused on improving performance causes the results to be paginated with a `?take=15`.
The search method used in the request is `?partialName=`, which is performed _after_ the pagination, meaning the API will request the first 15 certificates and then search them for names matching the search criteria.

When clicking "Load More" in the Library/Certificates search, an extra 15 or so is added to the take value, meaning if the Certificate the user is looking for is certificate number 200, they would have to press that button 11 times to load the certificate.

### Reproduction

[Internal Only] 
If you head over to https://octopus-operations.octopus.app/app#/Spaces-262/library/certificates you can see there are 16 certificates in total.
Search for "bug" and you will find nothing unless you click the "load more" button to load the 16th certificate.
Which, can be found here: https://octopus-operations.octopus.app/api/Spaces-262/certificates/Certificates-412

### Workaround

The workaround to find things like certificates is to click the "load more" button until the item you're searching for appears.
Otherwise, referencing things directly or making changes/additions via API rather than UI may be the best approach.

**Comment by droyad** [comment]
I had a quick look at this, and it does the wrong thing because `partialName` is ignored by the API, it uses `search` [instead](https://github.com/OctopusDeploy/OctopusDeploy/blob/920818b984c9c8f00622c3f1cc1c31e3e01995bd/source/Octopus.Server/Web/Handlers/GetCertificatesRequestHandler.cs#L43).

The UI does show the load more, so the certs can be accessed eventually:
![image](https://user-images.githubusercontent.com/1687639/146693360-9f014891-72c8-4607-958d-51597d0249ef.png)

This API was migrated in https://github.com/OctopusDeploy/OctopusDeploy/pull/10025

The [previous version](https://github.com/OctopusDeploy/OctopusDeploy/pull/10025/files#diff-8538c73583855f72ad5e8b104a94e051e2563d02ced944af30d782e27065a38eL38) supported both `partialName` and `search`

**Comment by N-lson** [comment]
Release Note: Correctly filter Certificates on the UI when there are more than 15

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10327 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10327 |
| 2022.1+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.10327 |
| 2022.1+ | _all releases_ |
