### ISSUE TITLE
"Files in Additional Packages" in "Upgrade a Helm Chart" step always uses "ExecutionTarget" package mode

### ISSUE THREAD

**Issue by chrischu** [OctopusDeploy/Issues#7326]
When configuration "Files in Additional Packages" in an "Upgrade a Helm Chart" step, there is no way to change the behavior to acquire the package on the server and upload it to the tentacle, instead the package is always directly downloaded on the target.

When first trying to add the package the dialog looks like this:
![image](https://user-images.githubusercontent.com/447251/150343644-5e4f8397-86d9-4fc4-9385-9d7344560d55.png)

When I then click ok and try to edit the package again I'm greeted with this:
![image](https://user-images.githubusercontent.com/447251/150343740-dfbdf2a7-3db2-4ac5-a8ff-5c9c413c2e66.png)

No matter what I do, I cannot change the setting to download on the Octopus Server for whatever reason.

Is there any way to accomplish this? Is there any viable workaround?

I'm using Octopus v2021.3 (Build 8275).

**Comment by chrischu** [comment]
Oh I managed to fix the problem by manually (via the API) adjusting the build process and changing the "AcquisitionLocation" to "Server", so I it seems like this is a bug in the UI.

**Comment by chrischu** [comment]
Hello? Is there any update on this?

**Comment by drauch** [comment]
We're also having this problem, any updates?

**Comment by danefalvo** [comment]
Hi @chrischu,

Generally issues are raised by the Support Team at Octopus in this repository. Due to the engineer workflows, what you have submitted will likely not have been picked up.

In future, please contact support@octopus.com with details of the problem you are facing and the support team will raise a bug if necessary, but will 100% help you out. If it's not a support related issue, you can find all the relevant contacts [here](https://octopus.com/support)

As you have put a bit of detail into this post and it's a fairly straight forward issue, I will see if the engineers will be able to pick this up. I can't promise anything, but whether they do or don't I will make sure to let you know.

@drauch you will get excellent support whether you have a paid or free account, by reaching out to the team via support@octopus.com.

**Comment by danefalvo** [comment]
Hi Chris,
Although not the usual workflow, the engineers have let me know that they will triage this issue on this occasion. 
We will provide updates on this Github issue.

**Comment by chrischu** [comment]
Hi @danefalvo,
Thanks, that's great news!

**Comment by chrischu** [comment]
Thanks @danefalvo!
