### ISSUE TITLE
ProjectEdit required to create release

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7329]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking some CaC customers

### Version

After 2021.3.10526

### Latest Version

Not applicable

### What happened?

This seems to be isolated to Config-as-Code projects. Creating a release no longer works using the Build Server bult-in-role after upgrade from 2021.3.10526 to 2021.3.11085.

```
Run OctopusDeploy/push-package-action@v1.1.1
🔣 Parsing inputs...
Octopus CLI, version 7.4.3576
Detected automation environment: "GitHubActions"
Found space: Steps (Spaces-902)
Space name specified, process is now running in the context of space: Steps
🤝 Handshaking with Octopus Deploy
Handshake successful. Octopus version: 2021.3.11085; API version: 3.0.0
✅ Authenticated
Pushing package: /home/runner/work/step-packages-public-feed/step-packages-public-feed/step-packages-public-feed.0.3.0-ray-add-published-time.8.zip...
Requesting signature for delta compression from the server for upload of a package with id 'step-packages-public-feed' and version '0.3.0-ray-add-published-time.8'
Calculating delta
The delta file (258,804 bytes) is 13.91 % the size of the original file (1,860,107 bytes), uploading...
Delta transfer completed
🎉 Push successful!
Run OctopusDeploy/create-release-action@v1.1.1
🔣 Parsing inputs...
Octopus CLI, version 7.4.3576
Detected automation environment: "GitHubActions"
Found space: Steps (Spaces-902)
Space name specified, process is now running in the context of space: Steps
🤝 Handshaking with Octopus Deploy
Handshake successful. Octopus version: 2021.3.11085; API version: 3.0.0
✅ Authenticated
Found environments: 
This Octopus Server supports channels
Found project: Step Packages Public Feed (Projects-5521)
Automatically selecting the best channel for this release...
Building a release plan for Channel 'Pre-Release'...
Finding deployment process at git commit a6b5cef0307615ff1ebcdfd692a75c5f0672fcf4...
This action requires permission to edit project details. None of your teams have this permission.
You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: ProjectEdit
```

### Reproduction

Unable to reproduce at the moment.
See our own projects failing: https://github.com/OctopusDeploy/step-packages-public-feed/runs/4848380460?check_suite_focus=true

### More Information

FnM thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1642636445246300

**Comment by YuKitsune** [comment]
Potential workaround:
Open the project in Octopus Deploy and make a change to either the Deployment Process or Deployment Settings.
Should see a change to the `schema_version.ocl` file in the commit.

**Comment by dylanlerch** [comment]
This was an issue with how we process Git schema migrations. 

When you access a project that has a pending Git migration we need to write some data to the project so we know that a migration is ready to run at some point in the future. This is a system task, but we were applying the user permissions to the request - if the user didn't have project edit they couldn't get any information from a project that had a pending migration.

## What are Git migrations?
These are new! We now have a bit of a framework in place that lets us make changes to the Git schema over time without requiring any manual update to your OCL files. These updates apply automatically the next time you make a change (in the UI) to anything that is version controlled. _We don't apply these immediately in the background to avoid any unexpected writes to your repository._

## Workaround
Get someone with project edit permissions to make a change either the deployment process or deployment settings. This will trigger the Git migration to write to your repository, and you should be all good. We have not got any more Git migrations coming before the fix will start rolling out, so we expect this to be a one-time workaround and the project will be good from there.

## Impacted
From what we can see, this _should_ only impact config as code that projects that were created before `2021.3.11057`, and the version controlled files haven't been edited by anyone since that version.

If you fall into this group, the workaround above should solve the problem. Please let us know if it doesn't!

This will be fixed in a version that will start rolling out shortly.

**Comment by YuKitsune** [comment]
Release notes: Fixed git schema migrations requiring `ProjectEdit` permissions

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.1 | 2022.1.410 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12055 |
| 2022.1 | 2022.1.410 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12055 |
| 2022.1 | 2022.1.410 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12055 |
| 2022.1 | 2022.1.410 |
| 2022.2+ | _all releases_ |
