### ISSUE TITLE
Attempting to save a Form without a selected Account fails validation but the Combo Box does not show as red

### ISSUE THREAD

**Issue by scottmerchant** [OctopusDeploy/Issues#7332]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

It looks like the AWS Account selection combo box does not show validation messages like other editors. See screen cap:

<img width="1053" alt="Screen Shot 2022-01-24 at 4 53 56 pm" src="https://user-images.githubusercontent.com/97430840/150733232-dec45964-cb41-474d-ae08-088a92d01e84.png">

### Reproduction

Click Infrastructure -> Deployment Targets -> Add Deployment Target -> AWS -> Amazon ECS Cluster (Add) -> Save.
See that the AWS Account Combo box is not red like the simple text input boxes below it.

**Comment by mjhilton** [comment]
Is this specific to the ECS step, or is it just a front-end behaviour for drop-downs across the product?

**Comment by scottmerchant** [comment]
> Is this specific to the ECS step, or is it just a front-end behaviour for drop-downs across the product?

It looks like it's across the product for drop-downs. I tried a similar test with the Azure Web App and only the Display name field turns red (showing a little error message) - all the drop downs including environments, roles, and the 4 azure related settings did not go red.

**Comment by mjhilton** [comment]
This looks to be consistent behaviour across all of Octopus components, so it's something that should sit with `team/front-end` instead of `team/steps`

**Comment by dyantako** [comment]
After some investigation from the frontend platform side, it looks like this issue is specific to the integration of the account select within specific pages. For the ECS step, it looks like the error prop is not passed to the AccountSelector component so it'll never go red.

Similarly, the Azure Web App deployment target form is not passing the error value through to the variable select components (it passes the prop but the value is undefined when there are errors) so this is an issue with that page.

I've tagged this issue for `team/dynamic-deployments` to handle further

**Comment by scottmerchant** [comment]
Story: [sc-9628]

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.565 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.565 |
| 2023.1+ | _all releases_ |
