### ISSUE TITLE
Azure Government Cloud Azure App Health Check Error

### ISSUE THREAD

**Issue by briggs-octo** [OctopusDeploy/Issues#7663]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking, a workaround exists under certain scenarios

### Version

Octopus Version: 2022.2.7244 , Sashimi.AzureAppService Version: 2.4.2

### Latest Version

Not applicable

### What happened?

When attempting to run a system health check on an Azure app deployment target in Azure government cloud the following error is thrown and the health check fails:

```
ClientSecretCredential authentication failed:
AADSTS900382: Confidential Client is not supported in Cross Cloud request.
Microsoft.Identity.Client.MsalServiceException
```

### Reproduction

1. Configure Azure government cloud credentials on Octopus server.
2. Configure an Azure app deployment target in Azure government cloud.
3. Run a full health check against the previously configured deployment target.

### Error and Stacktrace

```shell
ClientSecretCredential authentication failed:
AADSTS900382: Confidential Client is not supported in Cross Cloud request.
Microsoft.Identity.Client.MsalServiceException
```

### More Information

[Internal :ticket: 1](https://octopus.zendesk.com/agent/tickets/92808)
[Internal :ticket: 2](https://octopus.zendesk.com/agent/tickets/93041)
[Internal :thread:](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1657736729450509)
[Potentially Related Code :computer:](https://github.com/OctopusDeploy/Sashimi.AzureAppService/commit/07785f5b5e13b2fd971c2da4c98bac8238643545)

### Workaround

Add a system environment variable `AZURE_AUTHORITY_HOST` with the value of "https://login.microsoft.us" and restart the Octopus Server service.

** Workaround should not be used when using both Azure government and public credentials on the same Octopus instance, as `AZURE_AUTHORITY_HOST` is a shared variable and [this will cause Azure public cloud authentication health checks to break](https://github.com/OctopusDeploy/Issues/issues/7663#issuecomment-1188241084) **

**Comment by jared-koiter** [comment]
I tried testing the suggested workaround in our environment and found that setting the system environment variable `AZURE_AUTHORITY_HOST` to `https://login.microsoftonline.us` allowed us to perform a successful health check against our Azure US Government target app service. However, I can also confirm that in doing so our Azure Public cloud targets started failing their health checks on the same error. I don't believe that the workaround can be used on environments that target both Azure cloud instances.

**Comment by mjhilton** [comment]
The fix for this problem has been merged to the `2022.2` Release Stream (most recent for self-hosted customers), and `2022.3` Release Stream (current for Octopus Cloud customers). 

* The installer for the `2022.2` stream is being prepared and will hit the website for self-hosted customers to upgrade in the next few hours.
* The Octopus Cloud release will follow our standard release cycle times. As we've not yet had any reports of Cloud customers being affected, we'll just let that roll through as per normal.

This issue will be updated with the version numbers the fix is available from once they are released.

**Comment by mjhilton** [comment]
Some services in Azure are down at the moment which is having a flow-on effect to a few of our pipelines. This will eventually get automatically posted to this issue, but in the meantime:

The fix for this is available in Server Stream 2022.2 from version `2022.2.7388`. The installer is [live on the website](https://octopus.com/downloads/2022.2.7388).

*(Note: the [release notes on our website for this version](https://octopus.com/downloads/compare?from=2022.2.7362&to=2022.2.7388) are also not currently correct - we accidentally referenced #7544 instead of this issue in the PR to Octopus Server. I've corrected the source data, and this will automatically sort itself out once things are chugging along again.)*

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7388 |
| 2022.3 | 2022.3.5692 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.7388 |
| 2022.3 | 2022.3.5692 |
| 2022.4+ | _all releases_ |
