### ISSUE TITLE
Incorrect environment ordering on a project with tenanted deployments enabled

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7701]
### Team

- [X] I've assigned a team label to this issue

### Severity

Misleading

### Version

Latest

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Usually the project overview dashboard shows environments in the order they're listed in the project lifecycle. However for tenanted projects this shows environments in the global sort order.

### Reproduction

1. Create a project and enable tenanted deployments in settings
2. Use a lifecycle that has environments in a different order to the global sort order
3. Do a deployment

### More Information

Internal slack thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1659440361529739

**Comment by samdanae-octopus** [comment]
The current functionality on the project dashboard seems to cater for this scenario by ordering correctly **when grouped by channel**.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/117602873/201824718-3a707399-ca66-4cc6-97b0-89b58f3f9252.png">

When not grouped by channel (i.e. all channels sharing various lifecycles are shown together), the dashboard displays **global  (default) sort order**. This seems like a logical approach as multiple lifecycles with various orderings need to be shown together.
<img width="978" alt="image" src="https://user-images.githubusercontent.com/117602873/201824455-ab2f1ec3-277a-4b5f-b2a7-cc12b515e4e3.png">

Unless there is another instance on the UI where the ordering is broken, this issue is probably safe to close.

**Comment by mjhilton** [comment]
To provide some extra context around our decision on this issue: We’ve classed changing how this ordering works as low priority, which means we won’t work on it in the near future. We prioritize issues based on the number of people affected, the impact type, and available workarounds. 

If you’ve encountered this issue and haven’t informed our support team, please email [support@octopus.com](mailto:support@octopus.com). Knowing how many people this issue affects helps us determine its priority.
