### ISSUE TITLE
CaC Long file paths Error

### ISSUE THREAD

**Issue by domrichardson** [OctopusDeploy/Issues#7770]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking

### Version

2022.2.7362

### What happened?

When setting up version control on a project an error is flagged if the Git Repository has long file paths.

Internal Ticket: [Here](https://octopus.zendesk.com/agent/tickets/96239)

### Reproduction

* Create a git repository with subfolders creating a long file path
* Create a project and setup Version Control using the same Git Repository
* 💥

**Comment by acodrington** [comment]
This issue has been fixed in `2022.3`.

**libgit2** and **libgit2sharp** now support `core.longpaths`, and Octopus 2022.3 has been updated to use the latest version. Unfortunately, this upgrade cannot be backported to `2022.2` so any users experiencing this problem should upgrade to `2022.3` or above.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.4368 |
| 2022.4+ | _all releases_ |
