### ISSUE TITLE
OctopusDeploy Package Upload will intermittently fail with UnauthorizedAccessException if uploading multiple packages to the same machine at the same time.

### ISSUE THREAD

**Issue by eternalapprentice2000** [OctopusDeploy/Issues#7775]
### Team

- [X] I've assigned a team label to this issue

### Severity

Medium Priority

### Version

v2022.1 (build 2679)

### What happened?

When running a deploy that has many steps and many packages to upload to multiple deployment targets, sometimes the packages will not upload properly.

![image](https://user-images.githubusercontent.com/2683939/190474393-888e6a76-5f06-4911-b99a-ac978eb1a4f5.png)

### Reproduction

Create a release that contains many steps/packages with multiple deploy targets.  During the Upload Package Steps it will intermittently fail.  A retry will generally resolve this issue.

### Workaround

Guided Failure Mode -> Retry steps will generally work.

**Comment by IsaacCalligeros95** [comment]
https://github.com/OctopusDeploy/Calamari/pull/938 is a potential fix to this issue, as the issue is intermittent and flaky it's hard to be 100% certain. There are also other places where this might still occur in the Calamari codebase so if this solves the problem in this case it could be worth looking at this in the future for similar UnauthorizedAccessExceptions.
