### ISSUE TITLE
Azure CLI - Run a Script - Deployment Stuck at Login with Service Principal

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeploy/Issues#7782]
### Team

- [X] I've assigned a team label to this issue

### Severity

Workaround Exists

### Version

AZ CLI 2.40

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When executing a Run an Azure Script step, if the AZ CLI tooling version is 2.40 then the script will hang indefinitely trying to login to the Service Principal. 

This also impacts other steps which are built on top of the Azure-CLI login mechanisms, which include:
* "Deploy an Azure Web Site" step
    * Note, this is the older msdeploy-based step. The newer "Deploy an Azure App Service" step is unaffected.

### Reproduction

1. Configure a Run an Azure Script step to execute using v2.40 of the AZ CLI
2. See deployment hang

### Error and Stacktrace

```shell
N/A - Deployment hangs until cancelled
```

### More Information
[Internal Link - Slack](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1663307605843019)
[Internal Link - Ticket](https://octopus.zendesk.com/agent/tickets/96511)
[Internal Link - Ticket](https://help.octopus.com/t/az-authentication-timeout/28368)

### Workaround

Use version 2.39 of the AZ cli instead. Changing the deployment process to use the tooling bundled with Octopus should include a compatible version.

**Comment by mjhilton** [comment]
This problem is a result of a bug introduced in Az CLI `2.40`: Azure/azure-cli#23890

It results from of [a change in the AzureCLI to the way the `az` commands are launched on Windows](https://github.com/Azure/azure-cli/pull/23514). 

This seems to have resulted in a cluster of issues around `az` no longer correctly accepting different forms of input on Windows (eg https://github.com/Azure/azure-cli/issues/23891, https://github.com/Azure/azure-cli/issues/23883).

As this is functionality in Az CLI that used to work and was unintentionally broken, we expect that the Azure CLI team will be fixing it in an upcoming release. Given the number of issues cropping up in that repo, we would hope that this is done sooner rather than later. 

We will not be making a change to Octopus attempt to work around this problem. However, we will closely monitor the Azure CLI repo and related issues for any new information or progress.

Until the Azure-CLI team issues a fix, we advise affected customers to use the noted workaround of using an earlier version of Azure CLI (`2.39` or earlier) in their deployment environment. 

This would be done in different ways depending on your deployment configuration:
* If your step executes on a deployment target, downgrade the version of Az CLI on your workers to `2.39` 
* If your step executes on a private worker pool, downgrade the version of Az CLI on your workers to `2.39`
* If your step executes in a private execution container, downgrade the version of Az CLI in your image to `2.39`
* If your step executes on the Octopus Deploy Worker Tools, you will not be affected
* The Octopus Cloud Windows workers do not contain a pre-installed version of the Az CLI, so they are not affected

**Comment by mjhilton** [comment]
The Azure team has released v`2.41.0` which, according to [the Release Notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#october-11-2022), should fix this issue. We'll need to test against that updated version to check compatibility.

**Comment by toby-freemarket** [comment]
Just tested this out, this is fixed for us using Azure CLI `2.41.0` 
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.41.0

**Comment by mjhilton** [comment]
Thanks @toby-freemarket!

**Comment by michelle-luana** [comment]
Closing this as Azure resolved the issue a month ago
