### ISSUE TITLE
Disable process step

### ISSUE THREAD

**Issue by johnkors** [OctopusDeploy/Issues#779]
Hi,

There seems to be no way of disabling a Process Step temporarly. If I would want to do this today, I would have to delete the step and then add it later and re-add all variables. Would it make sense to add this a feature, or does this break anything?

**Comment by elkaz** [comment]
I don't agree that skipping a step during deployment should be the resolution for this issue, as forgetting to skip a step can be easy, and have potentially harmful consequences. 

Similarly to other applications with step based approaches (e.g. Team City), there should be an option to disable a step indefinitely, rather than having to completely delete the step, or using another workaround not intended for its purpose (such as a dummy environment).

**Comment by vanessalove** [comment]
@elkaz There is a uservoice suggestion that if you want this feature added (see Pauls link) you should vote and comment on. GitHub is our working list, and suggestions are not part of it. We will not reference back to this ticket. So please add comments where it will give the feature a better chance at being built.

**Comment by elkaz** [comment]
@vanessalove Thanks for the reply, but it appears Paul's link doesn't work (it is an admin link). Removing the admin segment from the URL redirects to a different suggestion, which doesn't cover this issue raised here.

**Comment by vanessalove** [comment]
@elkaz yes you are correct the original linked issue was merged.
Here is the current (very popular) suggestion: http://octopusdeploy.uservoice.com/forums/170787-general/suggestions/6324610-allow-steps-to-be-disabled-or-inactive
