### ISSUE TITLE
ServiceNow typo

### ISSUE THREAD

**Issue by XanderGr** [OctopusDeploy/Issues#8130]
Dear Octopus Team,

I noticed a simple typo on your documentation page for ServiceNow Approvals via https://octopus.com/docs/approvals/service-now. The word "ServiceNow" is currently spelled "Service Now" on the page subtitle "Configuring Service Now". I'd like to recommend that this be corrected to ensure the accuracy of the page.

Additionally, I noticed that the URL for the page contains a space between "Service" and "Now". This could potentially make it difficult for users to find the page when searching. Therefore, I'd like to suggest updating the URL to "https://octopus.com/docs/approvals/servicenow" to make it more user-friendly.

As this is a public issue on GitHub, please let me know if there are any additional details or actions needed on my part. Thank you for your attention to this matter.

Best regards,
Xander

**Comment by benjimac93** [comment]
@XanderGr Octopus don't monitor this repo for issues, it's more for them to internally track things.

All their docs are open source though, I've submitted a PR [here](https://github.com/OctopusDeploy/docs/pull/1853) for the typo

**Comment by harrisonmeister** [comment]
Hi @XanderGr 

Thanks for your suggestions. As part of some platform re-engineering work the content team are doing, the typo was already fixed in a new branch (`main`). 

The new docs site is still being worked on but should be published soon, this includes the typo fix you have highlighted.

In addition, I've raised a PR to move the files from `service-now` to `servicenow` - you can see that PR [here](https://github.com/OctopusDeploy/docs/pull/1857)

**Comment by harrisonmeister** [comment]
The [new PR](https://github.com/OctopusDeploy/docs/pull/1857) has been merged, so I will close this because the new docs platform will be released shortly. If you have any concerns with this, please feel free to re-open the issue.
