### ISSUE TITLE
Retain file timestamps when extracting files from packages

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#829]
http://octopus-deploy.tenderapp.com/discussions/problems/17537-timestamp-not-preserved-when-tentacle-unpacks-packages

I know the last time we looked into this we decided not to keep the timestamps, and we're compatible with how NuGet.exe works. 

But I'm not totally sure whether the way NuGet.exe works is actually the way it needs to work. Do they do that because they haven't considered keeping the stamps (was it a deliberate choice?) or has the scenario just not come up? 

I can't think of any reason not to keep the timestamps; in fact it would help with a number of "sync" features. And if people want to set the timestamp to the extraction date, it would be pretty easy to write a PreDeploy script to "touch" each of the files.

**Comment by ulf-cab** [comment]
I don't quite understand the "System.IO.Packaging doesn't capture file timestamps" comment. nupkg:s are zip-files that do store a last changed date/time. Could or rather should not that timestamp be used when extracting files?

**Comment by richard-green** [comment]
@caseymarcallen having the exact same problem as you with ETags and Last-Modified timestamps causing our load-balanced UI to be terribly inefficient :-(

Did you come up with a solution to this?

It's a huge shame that Octopus seems to be overriding the LastWriteTime of the files, since if you unzip them with 7zip they maintain the timestamps correctly.

**Comment by richard-green** [comment]
FYI I fixed it with the following powershell code:

$timestamp = (Get-Date $OctopusParameters['Octopus.Deployment.Created'])
Write-Host "Updating time stamps to $timestamp"
foreach ($file in (Get-ChildItem .\Content -recurse)) {
	$file.LastWriteTime = $timestamp
}

**Comment by rirl** [comment]
Is this actually a problem with Octopus or with Nuget?
I believe that Nuget does not write the time stamp properly on its files?
This issue is probably closed here, so I am probably speaking to the wind?

**Comment by PaulStovell** [comment]
Yes, the file format NuGet uses simply has no place to store file timestamps - even if we really wanted to do it, it's impossible with NuGet.

**Comment by ulf-cab** [comment]
Oh no, the NuGet file format is simply a ZIP file that does have a field for date/time of last modification.

But looking into a bit of code this time I see this:

* NuGet V2 uses System.IO.Packaging.Package which is documented to be a zip file but does not expose or handle or document what it does with the date/time field.

* NuGet V3 uses System.IO.Compression.ZipArchive which does expose the date/Time field but the code uses CreateEntry rather than CreateEntryFromFile so the date/time file is set to the 
time of package creation instead of the actual file time. Does not make a huge difference for binaries in an OctoPack scenario but I consider that a bug.

* OctoPack uses nuget.exe (V2 most likely)

* octo.exe pack uses PackageBuilder from a NuGet V2 library.

* 7-zip shows a date/time for the content files in a package so Package must set the file date/time to the time of package creation and 7-zip uses that for extraction.

* Calamari uses System.IO.Packaging.Package directly (for memory (and) performance reasons according to the docs but still keeps a reference to the NuGet V2 library) so it at least fails to preserve the date/time field due to not having access to it.

* The NuGet V3 library uses ZipArchive for extraction but fails to handle/preserve the date/time field, another bug. The code might have the same memory/performance problems as the V2 one, there is a lot of layers and hard to tell from a quick look.

**Comment by mmclin** [comment]
We are using to Nuget to store releases of libraries that are used by a variety of projects, and the incorrect timestamps are causing us grief as well.  I would really like to see this issue re-opened and resolved.

**Comment by cemdev** [comment]
Also causing problems here. It's quite a significant issue in any kind of load-balanced scenario. richard-green's solution will fix the issue with multiple servers, but it still results in a new version of every single js and css file on each deploy with a file time-based cache busting mechanism - even if none of them changed, which is wildly inefficient.

**Comment by cemdev** [comment]
For others who may be reading this - one solution (about to be tested) is to switch from file time based cache busting to md5 hashes. It's unfortunate, as it's actually slightly less robust (there is a small chance of collision), and slightly slower, but it's either that or ditch Octopus Deploy entirely.

**Comment by michaelnoonan** [comment]
I have just come across this issue and raised a [UserVoice Suggestion](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/11253099-preserve-file-timestamp-when-extracting-packages) to raise support around a solution for NuGet Packages.

Work is in progress on enabling packages other than `.nupkg` to be used with Octopus for packaging and deploying applications, primarily driven by Linux deployments, where `System.IO.Packaging` performs very poorly on Mono. In this case you could start using `.zip` packages which would preserve the file timestamps upon extraction.

This isn't on our public roadmap, but the work is looking promising and will likely ship in a feature release of Octopus Deploy.

**Comment by michaelnoonan** [comment]
Hi Everyone, we're just about ready to ship Octopus 3.3.0 which has support for other package formats. We have included automated testing to ensure file timestamps are preserved for all of the non-NuGet package formats. So as of Octopus 3.3.0 I'm happy to report this issue could be resolved, and I'd be very interested in your feedback!

**Comment by ulf-cab** [comment]
Hi,

Can "octopack in a project" create any of these non-nuget package formats where timestamps are preserved?

**Comment by zentron** [comment]
Calamari has now been updated in `3.3-beta2` to use the new package extractor that supports preserving timestamps.

Unfortunately @ulf-cab, octopack currently only creates NuGet packages which as described above does not preserve the timestamps, however any archival software the creates  `.zip` and `.tar.gz` file formats can be used in its place.
Packaging using  `.zip` and `.tar.gz` file formats are available for node projects using [gulp and grunt](http://docs.octopusdeploy.com/pages/viewpage.action?pageId=3049551) modules.

**Comment by ulf-cab** [comment]
Ok, please put the possibility for octopack to do that on the wish list. It is hard to get anyone to go beyond that and do "custom" packaging.

**Comment by richard-green** [comment]
This makes me very happy - thanks!!

**Comment by Myster** [comment]
From a cursory reading of this issue, https://github.com/NuGet/Home/issues/420 It appears this should be fixed in later versions of Nuget?

**Comment by ulf-cab** [comment]
Seems like it, yes.

For that to have an effect in Octopus an update of all binaries, nugets and perhaps other variants of nuget that is used in OD is needed.

**Comment by michaelnoonan** [comment]
Hi All,

@MJRichardson is busily updating all the things to NuGet 3 as part of Octopus 3.4. We have an automated test for preserving timestamps for zip files (etc) - it would be great to add one for NuGet and see how it works out. :)

Mike

**Comment by conorboyd** [comment]
Can I request an update to the [Packaging documentation](https://octopus.com/docs/packaging-applications/supported-packages) for OctopusDeploy to point out that the Zip file format does NOT store timezone information for file timestamps, whereas e.g. the Tar file format does.
We were bitten by an issue where a Zip file containing files created in the NZ timezone was NOT handled correctly when deployed by Octopus to a server with a GMT timezone (the contents of the Zip package ended up with modified timestamps considered to be in the future on the destination server).

**Comment by zentron** [comment]
That is an interesting find @conorboyd. Some compression libraries _will_ actually make use of extra file headers to store unix epoch or timezone, however the [PKZip](https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html) specs do indeed only specify the requirement of 2 bytes for date headers. In any case I had added a line to our docs page on [zips](https://octopus.com/docs/packaging-applications/creating-zip-packages) to make note of this difference.

**Comment by conorboyd** [comment]
Perfect. ;-)

Cheers,

Conor

**Comment by drewfreyling** [comment]
So even though, as of Octopus 3.4, the last write timestamp is preserved to help out with all those cache validation issues we have faced, this is still a problem for files that are variable substituted. E.g. If I have a file that is variable substituted it will have a different last write time for each target.

**Comment by michaelnoonan** [comment]
Hi @drewfreyling - we talked about this a bit internally. At this point we think it would be potentially misleading to preserve the timestamp for a file that has been updated during a deployment: if you've changed a variable value, the cached version of the file should be invalidated so the new variable value is picked up by any consumers. Otherwise you run the risk of using the cached file instead of the updated file. The only way to work around this behaviour would be to change the source file, rebuild, repack, and push a deployment through in order to invalidate the cache, instead of everything just working.

In your case where the timestamp varies across the server farm, I wonder if another solution could help? Do you have any suggestions?

**Comment by drewfreyling** [comment]
Thanks to @zentron for the suggestion I've decided to go with the following post-deploy script:
```powershell
$file = Get-ChildItem "foo\bar.js"
$file.LastWriteTime = $OctopusParameters['Octopus.Deployment.Created']
```
