### ISSUE TITLE
Override how stderr is treated

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#839]
Octopus assumes that any output written to stderr is an error, and warns when it is detected. Some programs, like git, use stderr for anything that isn't output - such as progress or verbose info. 

We'll introduce a service message that makes it possible to override how stderr output is treated: 

```
Write-Host "##octopus[stderr-ignore]"       # Ignore stderr output
Write-Host "##octopus[stderr-error]"        # Stderr is an error
Write-Host "##octopus[stderr-progress]"     # Stderr is info
Write-Host "##octopus[stderr-default]"      # Same as error, used to 'reset' behavior
```

**Comment by CumpsD** [comment]
Awesome, just needed this with docker-compose writing informational stuff to stderr

**Comment by CumpsD** [comment]
Perhaps a silly question, is this supposed to be somewhere in the UI?

Or do I just "echo ##octopus[stderr-progress]" in my Bash pre- and post-deploy?

**Comment by michaelnoonan** [comment]
Hi there. The `##octopus[XYZ]` service messages are interpreted on the Octopus Server regardless of the scripting language, so just go for it. There are some helper functions you can call from bash though: http://docs.octopusdeploy.com/display/OD/Custom+scripts#Customscripts-Logging

Hope that helps!
Mike

PS: The best way to get help is https://octopus.com/support - we don't always monitor these older issues. :)

**Comment by CumpsD** [comment]
It works, thanks :)

**Comment by Bounz** [comment]
Hi there.
It seems that "##octopus[stderr-progress]" doesn't work as expected.
I thought that after this override all messages from stderr channel would have "Info" log level, but they have "Verbose" level instead. And because of that I don't see these messages in Task Log by default; I have to click to Verbose link.
Is there any way to show messages from stderr as Info on Task Log page?

![octopus deploy - google chrome 2016-09-08 17 55 31](https://cloud.githubusercontent.com/assets/3062744/18354328/ce49ba96-75ed-11e6-9e37-bdfb1deb596d.png)

**Comment by CumpsD** [comment]
Is it possible `echo "##octopus[stderr-progress]"` is not working anymore? My Error output is again treated as errors instead of progress

**Comment by michaelnoonan** [comment]
Hi David, These changes were only for Octopus.server.exe and Tentacle.exe
which shouldn't have had any effect. I would recommend getting in contact
with our support team so we can investigate further.
https://octopus.com/support
