### ISSUE TITLE
Unable to change project lifecycle via Octopus UI on projects with no deployment process

### ISSUE THREAD

**Issue by RobMcCarther** [OctopusDeploy/Issues#8443]
### Severity

Low

### Version

2023.2.12673

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Projects without a deployment process which use Runbooks with the "Environments from Project Lifecycles" run setting are unable to change the project's lifecycle via the Octopus UI

### Reproduction

- Create new project
- Notice that the 'Lifecycle' section is not present on the right-hand side, unable to change this
- Add a simple step (Run a script)
- now, notice that the 'Lifecycle' section is present along with the option to change via the Octopus UI

### Workaround

* Manage Lifecycles via the Project Channel page ([explainer](https://github.com/OctopusDeploy/Issues/issues/8443#issuecomment-1953438388) below)
or
* Temporarily add a step to the deployment process and make the necessary change via the Process page which now shows a Lifecycle link, then remove the step

**Comment by mjhilton** [comment]
It's not quite as easy to find from a UX perspective, but it is still possible to change the available lifecycles in a Project even without a process specified.

There is a level of indirection here, in that [Lifecycles are connected to a Project via Channels](https://octopus.com/docs/releases/channels#using-channels):

```
Project <--- 1:N ---> Channel <--- 1:1 ---> Lifecycle
```

So, the way to manage the Lifecycles available to a Runbook without a Project Deployment Process defined, is:

1. Navigate to the Project
2. Choose "Channels" in the Project nav bar
3. Either 
    * Update the Default/existing channel with the Lifecycle you want to use in your runbook
    or
    * Add a new Channel with a second Lifecycle you want to have available to your runbooks

When triggering a runbook Run, all of the environments from each Channel's Lifecycle will be aggregated together and made available.

**Comment by bcullman** [comment]
@mjhilton, I just encountered this issue, and the workaround proposed here did not work for me (or is unsatisfactory - read on). 

In my case, I wanted to removed a lifecycle that was no longer needed, which was attached to a project that did not have a Deployment Process. I found it was referenced on the Channel, and so I selected another lifecycle there (just as the workaround above proposed). 

Ok, so **if** I had been able to delete the lifecycle successfully at that point, I would agree this is reasonable workaround for now, because it is intuitive that the lifecycle was still visibly associated with the project via the Channel tab.

However, I was still unable to delete the lifecycle.  So... is "_Triggering a runbook Run..._" part of the workaround as well? 

If **yes** - it can be can argued I actually did not complete the workaround steps yet - I still needed to trigger a runbook run. I have not tested this, but if it is valid, it is both non-intuitive, and potentially dangerous depending on what has been set up in the runbook.

If **no** - triggering a runbook run is actually a red herring. Removing it from channels removes all visible references to the lifecycle, yet I was still unable to delete the lifecycle. To resolve, I created a dummy step for the deployment process. Now that a step existed, I could see the lifecycle in the column on the right, and I was able to select another lifecycle. I was then able to delete the lifecycle, and then delete the dummy step I created. This is merely non-intuitive. (thanks to the community slack channel for suggesting this alternate workaround)

Please consider reprioritizing this this issue

cc @RobMcCarther

**Comment by mjhilton** [comment]
Hi @bcullman, thanks for providing the detailed extra information, and sorry for the frustration. 

I'm currently on PTO/annual leave and won't be back at work until later in the month, but I've sent a message to my team asking them to have another look at this issue. Hopefully we can help you out - I'll check back in when I return to work to make sure you get an answer.

**Comment by mjhilton** [comment]
Checking back in on this - I've just merged a change to add the ability to edit the Default Project Lifecycle in the Project Settings page, which will be available regardless of the way a project is used. It'll be available in Octopus 2024.3 - our release automation will update this issue with exact version numbers as it makes its way through the rollout pipeline.

**Comment by mjhilton** [comment]
Release Note: Added the ability to edit the Project Lifecycle from the Project Settings page

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.1202 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.1202 |
| 2024.4+ | _all releases_ |
