### ISSUE TITLE
Labels on project environments replace the name of the variable 

### ISSUE THREAD

**Issue by LewisJohnsonOctopus** [OctopusDeploy/Issues#8705]
### Version

Earliest tried was 2024.1.12087, also tried on 2024.2.2914

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When creating tenant variable templates, if adding a label to the variable and then viewing on  the tenants page, the label will override the variable name

Tenant Variable setup:
![image](https://github.com/OctopusDeploy/Issues/assets/156933367/e1c2228e-6ba3-4d65-b128-7852fdcfb10a)

Viewing from tenant page:
![image](https://github.com/OctopusDeploy/Issues/assets/156933367/0a8e7d7c-72ab-4a64-af9f-78f01edf5df4)

### Reproduction

Create a tenant variable
Give it a name and also a label
Go to Tenants
Select the Tenant and go to Variables
Expand the Variables
See that the label has overridden the variable name

### More Information

Link to ticket where customer initially raised this - (internal) https://octopus.zendesk.com/agent/tickets/176889 -

**Comment by denys-octopus** [comment]
I think there are no overriding happening, but on Tenants Page we display a label over the variable name as a title of  variable editor, which is existing behaviour. Variable name persisted correctly which can be seen in the Project -> Tenant Variables table

**Comment by Clare-Octopus** [comment]
@denys-octopus That is correct, no variable values themselves are being changed here but it is confusing for customers as we display the Label in the Tenant variables view, we should be displaying the variable name here not the label:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/aabff5af-f27c-48f1-a639-77809f251e75)

That needs to be changed from the variable label to the variable name. I am sure that was shown as the Variable name in previous Octopus versions.

Hopefully that helps clarify what the issue is but you are correct in that the variable values themselves are not being altered in any way

**Comment by Lexy2** [comment]
Customer here.
@Clare-Octopus this is the whole and sole purpose of the label - to show something user-friendly other than a technical internal name.
So I disagree with you. You should keep showing the label here, but not sort them by internal name and allow reordering. As it used to work before.

**Comment by Clare-Octopus** [comment]
@Lexy2, 

Thank you for your feedback, it is valuable to our engineers, they will take a look at this and decide if they want to switch it back. A customer mentioned it via our email support as it confused them with the label on the left of the tenant's variable page, and I am sure we used to use names here, not labels.

This comes off the back of our new Tenant page designs. The ordering is no longer the same via project variables shown on the project page and those shown on the tenants variable page.

For example here is my instance's Tenant Variable view from the Projects page (note we use Variable names here not labels and they are shown in alphabetical order). We do show the label (yellow box) but we dont organise by it:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/c276c110-1c4a-459f-b825-a2d420e70c20)

However, when switching over to the variables on the tenant page, you will note its not technically ordered alphabetically (because we are still ordering by variable name not label) - so in my example my variable name of `C` is shown third on the tenants page because its sorting by variable name not label but it looks odd as you have a name of `A - Label` showing after `B Label`.

Also, note we do show the label here (yellow box), so we are essentially duplicating things on that page. This is why it's confusing, but I can see labels being valuable, it's just we have always shown those anyway in the bit with the yellow box I highlighted, so this is a bug, or at least it is behaving differently to the way it used to.

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/d7b7b8dc-abf8-4cb6-b72a-8928413b98b4)


Thank you for your input, we will consider that when deciding what variable input we want to put on the Tenant page. I would say that using the variable name on the left (considering we are already showing the label on that page) would be a better option, but we are always open to customer feedback.

Kind Regards,
Clare

**Comment by droyad** [comment]
> That needs to be changed from the variable label to the variable name.

As Lexy2 says, the `Label` field is "What is the field name in the UI". 

We haven't changed the Tenant Variable page under Tenants recently. We're actually looking at revamping to match the new Tenant Variable page under Projects, so the different views will be eliminated.

I think the only thing to do here is fix the sorting in the new area, which is already in progress. Also make the hint text a bit clearer.
