### ISSUE TITLE
Database projection error

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#8754]
### Severity

Sev-3-low

### Version

2024.1.12401

### Latest Version

None

### What happened?

Customer is seeing warnings in their logs after upgrading from 2023.3.13001 to 2024.1.12401

### Reproduction

-

### Error and Stacktrace

```shell
A database projection predicate was not supported by the query provider. Falling back to a full-table scan.
System.NotSupportedException: Only method calls that take a single string argument and Enumerable.Contains methods are supported
   at Nevermore.QueryBuilderWhereExtensions.AddWhereClauseFromExpression[TRecord](IQueryBuilder`1 queryBuilder, Expression expr)
   at Octopus.Core.Persistence.Database.DatabaseDocumentStore`2.Project[TProjection](Expression`1 predicate, Func`2 projection, CancellationToken cancellationToken)
```

**Comment by RobMcCarther** [comment]
Customer experiencing this - https://octopus.zendesk.com/agent/tickets/191598 (internal)

**Comment by michelle-luana** [comment]
The Octopus engineering team has reviewed this issue.  
After careful consideration, we’ve classed this low priority. This means we won’t work on it in the near future. 
We prioritize issues based on the number of people affected, the impact type, and available workarounds. 
If you’ve encountered this issue and haven’t informed our support team, please email [support@octopus.com](mailto:support@octopus.com). Knowing how many people this issue affects helps us determine its priority.

**Comment by Clare-Octopus** [comment]
Another customer seeing this issue (internal) - https://octopus.zendesk.com/agent/tickets/200784

**Comment by Clare-Octopus** [comment]
We are also seeing this on cloud instances (internal) - https://customerinstance-seq.octopushq.com/#/events/?filter=@Id%20%3D%20%27event-afa51a2dc5e208dc1c88a7c106000000%27&showExpanded&permalinkId=permalink-4803

**Comment by emilol** [comment]
All relevant types have been migrated to EF as of `2024.4.1811` and will no longer hit this code path.

**Comment by IgnitePete** [comment]
Same issue daily for us

```
A database projection predicate was not supported by the query provider. Falling back to a full-table scan. "   at Nevermore.QueryBuilderWhereExtensions.AddWhereClauseFromExpression[TRecord](IQueryBuilder`1 queryBuilder, Expression expr)
     at Nevermore.QueryBuilderWhereExtensions.Where[TRecord](IQueryBuilder`1 queryBuilder, Expression`1 predicate)
     at Octopus.Core.Persistence.Database.DatabaseDocumentStore`2.ProjectAsync[TProjection](Expression`1 predicate, Func`2 projection, CancellationToken cancellationToken)"
```

**Comment by Clare-Octopus** [comment]
Good morning @IgnitePete, thank you for reaching out. That error, as of yet, has not created any issues in Octopus itself other than being put in the Octopus Server logs and our engineers have removed that error from all releases after `2024.4.1811` as they mentioned we have migrated over to a new code path so Cloud customers should no longer see that issue.

Octopus server customers are still running on the affected code path as they are running `2024.3` (being latest version for Server customers) so you will still see this in your logs until we get a `2024.4` version out to Server customers which has been migrated over to our new code path.

If you are seeing issues in Octopus please reach out to support@octopus.com as long as you are on a current valid licence and we can see where we can help but that error in the logs just seems to be a log issue rather than it creating issues in our Octopus Software. 

Hopefully that alleviates any concerns you had with seeing that in your logs.
Kind Regards,
Clare

**Comment by IgnitePete** [comment]
Thank you, shall wait until release before checking again.
