### ISSUE TITLE
Azure Web App steps failing when no resourceGroup value is set.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#8906]
### Version

Cloud - 2024.3.4218+ | Server - 2024.2.9271+

### Latest Version

None

### What happened?

The fix we implemented to resolve #8829 checks whether SCM is enabled, but it breaks when trying to resolve the resource group if you have not explicitly defined one in your step - `If not specified then all Resource Groups are searched`

### Reproduction

Use an Azure Web App step with no resource group defined.

### Workaround

Explicitly define a resource group in your Azure Web App step.

**Comment by donnybell** [comment]
Customers who were previously specifying the `Web App Slot` in parenthesis () as part of the `Web App` parameter are also affected by the changes implemented to resolve #8829.

Both the `Web App Slot` and `Web App` parameters must be filled separately, solely with the appropriate, matching string (or Variable) for these respective parameters.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.3 | 2024.3.8305 |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9329 |
| 2024.3 | _tbc_ |

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9329 |
| 2024.3 | 2024.3.8645 |

**Comment by Clare-Octopus** [comment]
Unfortunately a customer has informed us the fix has not worked so I have re-opened this issue. I have managed to replicate it on our cloud hosted test version and have informed our engineers of my test findings.

Please look out for any new information regarding this. The workaround of specifically defining the resource group either in a variable (which can be scoped to targets/environments as required) or hardcoded if its just one webapp you are deploying to still does work and I have tested a successful deployment with that variable hardcoded:

![image](https://github.com/user-attachments/assets/f2e4cae3-119f-4928-a953-7e5f9dbc733b)

**Comment by Clare-Octopus** [comment]
New R and D for this (internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1722864754356679
Another customer seeing this issue (internal) - https://octopus.zendesk.com/agent/tickets/196700

**Comment by Clare-Octopus** [comment]
All customers, please note:

The linked GitHub issue [here](https://github.com/OctopusDeploy/Issues/issues/8829) for SCM authentication has resulted in a BREAKING CHANGE:

> This breaking change effects legacy mode for Web Deploy. The SCM check requires a Resource Group to be provided and Web App and Web Slot to be stored in their respected fields. Legacy mode will no longer search all resource groups.

Actions for us moving forward:

Due to that Azure change and since we are now not able to search for all groups/slots unless one is defined in the step we are going to perform the following actions so all customers are aware of what to do if/when they upgrade and run into this issue:

- Mark the releases with breaking changes
- Update the UI to enforce the resource group
- Remove the message about searching the resource groups


This means that our [Octopus comparison](https://octopus.com/downloads/compare) page will show this as a breaking change and highlight the need for the resource group/slots to be defined in the WebApp step. We will remove the text in that step saying that if you do not define a resource group, then all will be searched. We are also enforcing the resource group field to be a required field, so you will not be able to save the step unless you define a resource group.

**Comment by Octobob** [comment]
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2024.2 | 2024.2.9329 |
| 2024.3 | 2024.3.8645 |
| 2024.4+ | _all releases_ |
