### ISSUE TITLE
Runbooks don't work after export / import from one instance to another

### ISSUE THREAD

**Issue by SeppPenner** [OctopusDeploy/Issues#9057]
### Severity

Medium

### Version

2024.4.3613

### Latest Version

None

### What happened?

After exporting all projects and importing them to another instance of Octopus Cloud, the runbooks don't work anymore and throw the error: 

> There was a problem with your request.
> There are no records in the SqlDataRecord enumeration. To send a table-valued parameter with no rows, use a null reference for the value instead.

The runbooks seem to be imported properly, however...

### Reproduction

1. Export all projects (Make sure some projects have runbooks)
2. Import all projects in another instance
3. Error occurs when running a runbook

### Error and Stacktrace

```shell
None.
```

### More Information

Our runbooks are pretty simple (Sometimes only one-liners) that call a PowerShell script, so I assume the error is not related to the content of the scripts, but more of a generic error.
![grafik](https://github.com/user-attachments/assets/b319e1e4-9ebd-44b9-a530-cc22457401eb)

### Workaround

Unknown.

**Comment by SeppPenner** [comment]
Adding a new simple runbook to the same project fails with the same error.

**Comment by FinnianDempsey** [comment]
Hey @SeppPenner I think you might have run into this issue that's just been resolved last week: https://github.com/OctopusDeploy/Issues/issues/9049

Could you please confirm if it's still an issue on versions 2024.4.3726+ which should be rolling out shortly? 

Otherwise please send through a HAR file of the request showing the error to support@octopus.com and we'd be happy to investigate it!

**Comment by SeppPenner** [comment]
Thank you for the quick reply. This is solved now.
