### ISSUE TITLE
Insights 'deployment leadtime' value may flatline with "N/A" instead of showing data when using certain filters

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#9118]
### Severity

Not blocking this customer but we ideally need to show that data when using all filters.

### Version

2024.4.6469

### Latest Version

I could not reproduce the problem

### What happened?

This seems to be only happening to one project on one customers instance so far but logging this issue in case other customers are seeing it.

When using our [Insights feature](https://octopus.com/docs/insights) some projects when using some filters only show either partial data or no data at all.

For example with the default filter of `last quarter weekly` you will see no data from 18th August:

![image](https://github.com/user-attachments/assets/83b459e4-68dc-4684-82c3-c6199511c01d)

However, changing that filter to `last month daily` you can see there is data in October. That data should be present on the `last quarter weekly` filter rather than the `N/A` value this customer is currently seeing.

![image](https://github.com/user-attachments/assets/9516ee75-6a03-4525-8065-6a8dd5e72b9b)

The `last quarter daily` filter also shows no data:

![image](https://github.com/user-attachments/assets/4f6ca581-0690-4e26-a9b4-040bea0ded4a)

For this customer's specific project, I could only see data on the `Last Month Daily` filter; all other filters seem to drop the data from around 18th August, even though there are releases deployed after then, as the `last month daily` filter shows.

Since I cannot reproduce this and its only happening to this one customer for one of their projects I assume this is down to specific data in this customers tables for that one project.

### Reproduction

N/A

### Error and Stacktrace

```shell
N/A
```

### More Information

Customer ticket (internal) - https://octopus.zendesk.com/agent/tickets/211104
R and D (Internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1730804351461659

### Workaround

Change the filter to `last month daily` if you are not seeing data in the other filters.

**Comment by droyad** [comment]
The reason the chart shows a flat lead time was that between 1-3 months ago (longer than the monthly chart but shorter than the quarterly) a release with a much higher version number (e.g. 1.5000.0) was deployed. Normal numbering was in the form `1.2.5000` and newer releases are in that range.

Although the higher version number is a mistake, the system can't tell that. The lead time calculation relies on sequential SemVer versions so that it doesn't get thrown out by "back patch" releases.

There is currently no way to fix this other than waiting for the release to age out, or bumping the version number beyond the highest previously deployed.
