### ISSUE TITLE
Artifact collection improvements

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#918]
- [x] Always collect artifacts, even if a step fails
- [ ] Provide a flag that causes artifacts to be deleted after collection
- [ ] Provide a parameter that can be used to set the artifact's collected filename, if different from the actual filename on the Tentacle machine

**Comment by yannisgu** [comment]
Hmm, why was this closed? I can't really see any of these improvments in 2.6?

**Comment by PaulStovell** [comment]
As of Octopus 3.0:

 - We now collect artifacts even if the step fails
 - You can specify a name separate to the path, instead of having to copy it

However, we didn't add the deletion flag - a workaround is to run another script afterwards that deletes the file. 

You can see an example of the syntax here: 

http://docs.octopusdeploy.com/display/OD/Artifacts
